### ISSUE TITLE
player_death not working in item_despawn.ini

### ISSUE THREAD

**Issue by TP0G** [FalsehoodMC/Fabrication#113]
In item_despawn.ini setting "player_death" doesn't work at all, no matter what I set it to. Setting "default" to anything works perfectly. I have reproduced this in a fresh install with only forgery.

**Comment by exaskye** [comment]
Hm. Forge might be replacing the code I'm attempting to patch here for its own player death events.

**Comment by exaskye** [comment]
player_death actually works fine, it just has unintuitive overshadow behavior and doesn't work unless you suffix it with `!`. Fixing this by improving overshadow rules.
