### ISSUE TITLE
Incompatibility with Carpet

### ISSUE THREAD

**Issue by drakosoldier298** [FalsehoodMC/Fabrication#115]
https://gist.github.com/drakosoldier298/00b71976e5a2df03664f7b37e930adcc
This is serverside

**Comment by exaskye** [comment]
This is between Cardinal Components and Carpet.

**Comment by exaskye** [comment]
Fabrication appears in the stack trace due to changes it makes to Mixin itself to permit fail safety.

**Comment by exaskye** [comment]
Actually might not have anything to do with Cardinal Components. Just woke up, log reading is hard enough when awake.

Point is, Fabrication doesn't touch any chunk code.
