### ISSUE TITLE
Unable to access server configs ingame

### ISSUE THREAD

**Issue by WenXin20** [FalsehoodMC/Fabrication#119]
`Minecraft v1.16.5`
`Forge v36.0.7`
`Forgery v1.3.0`

The mod is installed on both my server and client, but when clicking on the "server" button in the config menu, the tooltip says that the server does not have Fabrication installed. I did not have a chance yet to test with only Forgery.
[Debug Log](https://gist.github.com/WenXin20/6086b7322bfa18857ea45dc335ae7f07)

**Comment by exaskye** [comment]
How are you accessing the config menu ingame under Forge? Did they finally add the Mods button to the pause menu?

**Comment by WenXin20** [comment]
I think some mod allows it to be accessed by shift-clicking the options button, but I don't know which. There is a mod called [Game Menu Mod Option](https://www.curseforge.com/minecraft/mc-mods/gamemenumodoption) that allows this as well, but I don't have that installed.

**Comment by exaskye** [comment]
Cannot reproduce after adding Game Menu Mod Option in my mini test Forge modpack.

![image](https://user-images.githubusercontent.com/6185037/106068415-7bf60580-60b5-11eb-82a9-ae1ac5701fe7.png)

**Comment by WenXin20** [comment]
Strange, this is what I'm seeing.
![2021-01-27_17 38 59](https://user-images.githubusercontent.com/12000593/106068695-94225080-60c6-11eb-9ff7-3220d28a735c.png)

**Comment by exaskye** [comment]
The mixins don't show as failing to apply in the debug log, so I'm not sure what could cause this.

Is your modpack available on Curse?

**Comment by WenXin20** [comment]
Not currently. I can try to get a google drive link to it.

**Comment by exaskye** [comment]
Sorry, I won't run a giant bundle of arbitrary code from an unknown source on my dev machine. I'll look more closely at the log.

**Comment by exaskye** [comment]
There are only a few mods that may have conflicting mixins, so I'll try and repro with those later today.

**Comment by WenXin20** [comment]
It's a personal pack I made using the curseforge launcher.  But alright then.

**Comment by exaskye** [comment]
I'm not saying you're going to send me a bundle of malware, but there's also no way for me to verify a modpack you send me as a zip is unmodified files from Curse without going through the same amount of trouble as manually reconstructing the pack from a log. Mods run unsandboxed, it is *trivial* to turn a mod file into malware without making it look suspicious.

**Comment by WenXin20** [comment]
Oh, no worries, I understand the need for caution.

**Comment by exaskye** [comment]
Apparently Forgery was not registering commands properly. Please try this build: https://unascribed.com/f/270ff13e_forgery-1.3.0.jar

(Yes, this is related. The config screen partially piggybacks on the commands.)

**Comment by WenXin20** [comment]
Yep, that fixed it.

**Comment by exaskye** [comment]
:tada: 

Incredible what happens when you look up documentation instead of just going "oh, it worked like this in 1.12, so surely it still works this way?"

**Comment by WenXin20** [comment]
True! And thanks!
