### ISSUE TITLE
Incompatibility with Obfuscate

### ISSUE THREAD

**Issue by Gagliardi-Juan9** [FalsehoodMC/Fabrication#120]
I have an error when entering the game with the Obsfuscate mod, and I have been seeing problems from other users and I saw that it was solved by changing some settings, I don't know how to do it, I wanted to ask if you could send me the mod in the latest version 1.16.5 with The error is solved. If you can't, it doesn't matter but it would be amazing if you did. Thank you so much

**Comment by exaskye** [comment]
Are you using Fabrication v1.3.0? If not, update. If so, please send a debug log as instructed in the text you deleted when making the issue...

**Comment by Gagliardi-Juan9** [comment]
Sorry, I already had the version of the mod 1.2.11 before and I did not know that in this last version they had fixed the incompatibility, Thank you very much and sorry for the inconvenience
