### ISSUE TITLE
Crash right when starting the game with Bits and Chisels

### ISSUE THREAD

**Issue by vinnyg0621** [FalsehoodMC/Fabrication#122]
[here is the log](https://pastebin.com/8dYRCxF8)

**Comment by exaskye** [comment]
This likely has nothing to do with Fabrication, and it's only appearing in the stacktrace due to changes it makes to Mixin itself to allow mixins to fail soft.

Please try reproducing this *without* Fabrication. If it no longer occurs, please send a full log, not just a crash report.

**Comment by exaskye** [comment]
This appears to be because Stacc is not applying its OptiFine-specific mixin even though OptiFine is present.
