### ISSUE TITLE
Right-clicking with fire aspect does not properly emulate a flint-and-steel right-click.

### ISSUE THREAD

**Issue by torzod** [FalsehoodMC/Fabrication#138]
With flint and steel, you can right click on creepers or tnt to directly ignite them, however with this tweak enabled, that is not possible. It does not do anything when clicking on a creeper and just places fire down as if on any other block when clicking on tnt.

**Comment by exaskye** [comment]
Ah yeah, never did add handling for entity clicks. Not sure what's up with TNT, will need to look into it.
