### ISSUE TITLE
Cotton Client Commands error

### ISSUE THREAD

**Issue by srnyx** [FalsehoodMC/Fabrication#142]
**Main error lines found at [17:04:37] (when trying to connect to my server)**
https://gist.github.com/srnyx/5f253054cb80b0281a0b24ed33b68bc4

Both the client and server had the same version. This doesn't happen when using v1.3.1, only v1.3.2.
I don't have Cotton Client Commands installed, but another one of my mods may be using it.

**Comment by exaskye** [comment]
[v1.3.2_01](https://github.com/unascribed/Fabrication/releases/tag/v1.3.2_01) migrates back to Cotton Client Commands. It will be available on Curse shortly.

**Comment by srnyx** [comment]
> [v1.3.2_01](https://github.com/unascribed/Fabrication/releases/tag/v1.3.2_01) migrates back to Cotton Client Commands. It will be available on Curse shortly.

Alright, I'll wait for it to be on Curse, thanks!
