### ISSUE TITLE
Hide Armor command does not persist when spawning in Overworld.

### ISSUE THREAD

**Issue by Althexia** [FalsehoodMC/Fabrication#150]
https://github.com/unascribed/Fabrication/blob/trunk/src/main/java/com/unascribed/fabrication/mixin/b_utility/hide_armor/MixinServerPlayerEntity.java

The /hidearmor command is not copying values while respawning a player while copyFrom is called on new player entity.
Spawning in the Nether or the End seems to copy the value over. Going back to the Overworld or respawning doesn't.

**Comment by exaskye** [comment]
You'd think I'd get this right after doing it seventy thousand times but yet I always forget copyFrom.

**Comment by exaskye** [comment]
Wait, no. That mixin *does* override copyFrom. Huh?

**Comment by exaskye** [comment]
Does running /hidearmor say "No slots were hidden"? If so this is a syncing issue and only affects you seeing your own armor.

**Comment by Althexia** [comment]
Nope, it gives the message that the slots were hidden, and the slots are in fact hiding. But upon spawning in Overworld, they are showing again.

Also another issue is that the /hidearmor command makes everyone else on the server DC, at least anyone close enough to see it that is. But that one I haven't tested on a clean install yet.

**Comment by exaskye** [comment]
WTF?

**Comment by Althexia** [comment]
Okay... Sorry. I ran some tests my friend didn't seem to have done. Ran only Fabrication in single player and it worked as intended. Ran single player with all her mods and it had the issue only then. Thanks for your time, I'll try and figure out what's causing it. And maybe then, also figure out what causes people to DC, lol.

**Comment by Althexia** [comment]
I tested everything and found the culprit. There seems to be a conflict with [Immersive Portals.](https://github.com/qouteall/ImmersivePortalsMod)

I will leave them a report as well.
