### ISSUE TITLE
"Spiders can climb" features incompatible with Spiders 2.0

### ISSUE THREAD

**Issue by sharlin073** [FalsehoodMC/Fabrication#158]
https://gist.github.com/sharlin073/156522856108c88e1f06d55d184f959c

Using 1.16.5 with Forge 36.0.26

I have spider 2.0 which makes spiders climb ceilings installed, and both 'can't climb glazed terracotta' and 'can't climb while wet' options enabled in forgery.
(I also have better animal model, but I disabled it for spiders, so it probably didn't affect anything)

I built two small 2x2 spaces, one with dirt walls and the other with glazed terracotta walls. I set the weather to 'rain'.
I spawn some spiders in with spawn eggs.

Spiders and cave spiders in the dirt wall come out without any issue.

I'm not sure this is solvable, but as it still works for glazed terracotta blocks, reporting here for just in case. :)

**Comment by exaskye** [comment]
Spiders 2.0 completely reworks the spider AI and has its own tag to specify non-climbable blocks that by default contains glazed terracotta, so even that feature is not working: https://github.com/TheCyberBrick/Spiders-2.0/blob/94178399882ab8faf732388da8e44dcf6e124426/src/main/resources/data/spiderstpo/tags/blocks/non_climbable.json


This isn't really reasonable to add compat for on my side; please request a config option to prevent spiders climbing while wet from Spiders 2.0.

**Comment by sharlin073** [comment]
Okay. Thanks!
