### ISSUE TITLE
My Game crashes on Initialization due to "Runtime Exceptions"

### ISSUE THREAD

**Issue by Zockerhopper** [FalsehoodMC/Fabrication#164]
https://gist.github.com/Zockerhopper/9dd3e2a64a0dacf9fa128b0a17805868

I want to run Minecraft but when I have Fabrication (1.3.3 and 1.2_01) in My Mods folder It always says this: The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'fabrication'!
Exit-Code: -1.

I only have fabric-api-0.31.0+1.16 and fabrication-1.3.3. I have run those two Mods in fabric-loader-0.11.0-1.16.5; fabric-loader-0.11.1-1.16.5 and fabric-loader-0.11.2-1.16.5 but it always only says the same Error Message:"The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'fabrication'!
Exit-Code: -1."

If I run it on an older Fabric Version, like: fabric-loader-0.10.6+build.214-1.16.4. It says this: The game crashed whilst initializing game
Error: net.fabricmc.loader.api.EntrypointException: Exception while loading entries for entrypoint 'main' provided by 'fabric-events-interaction-v0'
Exit-Code: -1.
Which I think is an Error with the Fabric API. Can you help me?
Additionally I had Minecraft run with the Output protocol, so here ya go: https://gist.github.com/Zockerhopper/72b3722f1a3a37d20e7f10ea817202eb

**Comment by exaskye** [comment]
Your item_despawn.ini contains bad lines. Delete it if you haven't customized it for the default to be generated.

If you have customized it, post it here and I can help you correct it.
