### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by srnyx** [FalsehoodMC/Fabrication#166]
https://pastebin.com/kC4BCt4D

**Comment by exaskye** [comment]
Looks to be between FibLib and Immersive Portals.

**Comment by srnyx** [comment]
> Looks to be between FibLib and Immersive Portals.

Does Fabrication use FibLib?

**Comment by exaskye** [comment]
No.

**Comment by srnyx** [comment]
> No.

Oh

**Comment by exaskye** [comment]
The reason Fabrication appears in this crash is it's the first mod to initialize a class that has a mixin conflict. The mixin conflict is between FibLib and Immersive Portals; Fabrication is only responsible for being the first one to step in it.

**Comment by srnyx** [comment]
> The reason Fabrication appears in this crash is it's the first mod to initialize a class that has a mixin conflict. The mixin conflict is between FibLib and Immersive Portals; Fabrication is only responsible for being the first one to step in it.

Ah, thank you. I've reported it to Immersive Portals and FibLib already: https://github.com/qouteall/ImmersivePortalsMod/issues/616 & https://github.com/Hephaestus-Dev/FibLib/issues/11
