### ISSUE TITLE
Dupe with "Instant Pickup" and double-tall plants when using shears

### ISSUE THREAD

**Issue by copygirl** [FalsehoodMC/Fabrication#170]
### Versions
- **Minecraft** `1.16.5`
- **Forge** `36.0.40`
- **Forgery** `1.3.3`

### Description
When using shears while the "Instant Pickup" feature is enabled, block drops from 2-tall plants are duplicated. This happens with the flowers (sunflower, lilac, rose bush, peony all drop 2x instead of 1x) as well as tall grass and large ferns (4x grass / fern instead of 2x). This also appears to happen with some modded 2-tall plants, as I've noticed with the rice plant from *Farmer's Delight*.

### Debug Log
https://gist.github.com/copygirl/730e46ee356c1566f65fcbcf112eddce

**Comment by exaskye** [comment]
Someone else has reported this happening on Fabric as well.
