### ISSUE TITLE
Any /fabrication:client command crashes the game

### ISSUE THREAD

**Issue by htmlcsjs** [FalsehoodMC/Fabrication#180]
Log here: https://gist.github.com/htmlcsjs/97a51850c8ae8b6b5eb5c8a564ac00b8

**Comment by exaskye** [comment]
Probably an incompatibility between Cotton Client Commands and the new client commands system in Fabric API. Will need to port to that at some point..

**Comment by exaskye** [comment]
Fixed in the 1.17 branch by virtue of Cotton Client Commands not existing, and fixed in 269ada5c for 1.16.
