### ISSUE TITLE
better_pause_freezing clock hacks cause incredibly bad server lag when unpausing

### ISSUE THREAD

**Issue by IdrisQe** [FalsehoodMC/Fabrication#2]
After installing this mod and activating many features, entered a singleplayer world to do some testing. 

After a while, I paused then unpaused, and all mobs ceased movement, and everything just stopped working.
Checking the MultiMC console, i recieved the following messages despite being on a singleplayer world:
[15:57:31] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 130486ms or 2609 ticks behind
[15:58:37] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 51161ms or 1023 ticks behind
[15:59:06] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 13959ms or 279 ticks behind
with no other error messages, unfortunately.
So something, after installing just this mod, caused even a singleplayer world to almost completely cease ticking.
Had to kill the instance since the world wouldn't save and quit. Unknown cause- bad mod interactions maybe? 
I'll have to do more testing. In the meantime just thought I'd bring it to your attention in case you may have any ideas.

Singleplayer mod list for reference:
(Yes, I know Optifine is terrible, and Optifabric is unsupported, but unfortunately, I require it for most of the features of my resource packs to function, as there are no alternatives for many of the features. Also OF is clientside so it shouldn't be causing this if it's an interaction with the mod?... I think?)
accurate-block-placement-1.0.7.jar
appleskin-mc1.16-fabric-1.0.11.jar
borderless-mining-1.0.6+1.16.2.jar
cleancut-mc1.16-2.1-fabric.jar
clear-skies-mc116-1.5.48.jar
cleardespawn-1.16.2-fabric0.17.2-1.1.1.jar
CompactStatusEffects-1.2.2.jar
darkness-mc116-1.6.50.jar
DynamicSoundFilters-1.1.3+1.16.2.jar
EnchantedToolTips-1.3.4-1.16.jar
Fabric-1.16.3-TillItBreaks-0.1.jar
fabric-api-0.24.1+build.412-1.16.jar
fabric-language-kotlin-1.4.0+build.1.jar
fabrication-1.0.2.jar
horse-stats-vanilla-4.1.4.jar
i-am-very-smart-2.1.0+mc1.16.1.jar
illuminations-1.2.2.jar
light-overlay-5.5.3.jar
lock_minecart_view-for-MC1.16.2-1.2.1.jar
microDurability-0.2.0+1.16.3.jar
modlist.txt
modmenu-1.14.6+build.31.jar
mousewheelie-1.5.7+mc1.16.2-pre1.jar
nightvisionflashbegone-1.0.0.jar
nomoreglowingpots-1.0.2.jar
optifabric-1.6.4.jar
OptiFine_1.16.3_HD_U_G3.jar
phosphor-fabric-mc1.16.1-0.6.0+build.7.jar
potiondescriptions-1.16.3-fabric-1.0.0.jar
PresenceFootsteps-r28+1.16.2.jar
RoughlyEnoughItems-5.6.1.jar
slight-gui-modifications-1.4.0.jar
stepup-1.16.2-fabric0.17.2-1.1.jar
tooltipfix-1.0.2-1.16.jar
torohealth-1.16.3-fabric-1.jar
XaerosWorldMap_1.11.0_Fabric_1.16.3.jar
Xaeros_Minimap_20.26.0_Fabric_1.16.3.jar
[1.16.2]bettermodbutton-1.1.4.jar

**Comment by exaskye** [comment]
Try disabling better_pause_freezing.

**Comment by IdrisQe** [comment]
That does appear to have solved it, or at the very least I've been unable to reproduce the issue.

**Comment by exaskye** [comment]
Yeah I figured making the game clock stop while paused was a Bad Idea™.

Will remove that.
