### ISSUE TITLE
Startup crash with KubeJS

### ISSUE THREAD

**Issue by Lykrast** [FalsehoodMC/Fabrication#20]
Crash on startup with both Fabrication and KubeJS, both mods work fine individually. I have no idea how to read those particular errors but Fabrication is the one who appears in the error so that's where I'm reporting.

Minecraft - 1.16.4
Fabric API - 0.25.1
Fabrication - 1.2.2
KubeJS Fabric - 1.6.0
Rhino - 1.7.13.7

The log file gets cut off before the exception so here's the copied MultiMC log (so it has extra stuff at the top) : https://gist.github.com/Lykrast/47aec9660a9c013cb698222ef60f82d9

**Comment by exaskye** [comment]
...The hell?

**Comment by exaskye** [comment]
This may be related to 1.16.4, not KubeJS. Unclear. I've seen this crash for a few different reasons...

**Comment by exaskye** [comment]
`[13:33:30] [main/INFO] [Fabrication]: Injecting mutable resource pack provider set, as no-one else has yet.`

Fixed, at the cost of giving me another Java 15 incompatibility.

**Comment by exaskye** [comment]
https://github.com/unascribed/Fabrication/releases/tag/v1.2.2_01
