### ISSUE TITLE
add enchanted_block_preserve_enchantments

### ISSUE THREAD

**Issue by Neubulae** [FalsehoodMC/Fabrication#21]
Shulkerboxes with Fire Protection still burns after placing down and picking up, rendering them kinda useless.
However it seems like this could potentially be a feature quite hard to implement, if that's so then just implement to shulkerboxes or a limited set of blocks

**Comment by exaskye** [comment]
Shulker Boxes aren't enchantable in vanilla and therefore can't accept Fire Prot with just Fabrication; whatever mod you're using to add enchantments to shulker boxes is hardcoded to keep only its enchantments.

I wouldn't quite call that a bug in the other mod, but it makes the logic of putting shulker box enchantment code into Fabrication questionable. This would fall under a separate tweak that also makes shulker boxes enchantable.

Doing this generically for any block that happens to be enchantable would be very painful and hacky.

**Comment by Neubulae** [comment]
I'd imagine tricking the server into thinking that players are in creative mode, therefore enabling players to bam the enchantments on the anvil.
However, keeping blocks enchanted *after* placing down would be painful

**Comment by exaskye** [comment]
I don't think this is in-scope for Fabrication.
