### ISSUE TITLE
Crash when rendering a glowing entity with a shield with a banner pattern applied 

### ISSUE THREAD

**Issue by TheOldOne822** [FalsehoodMC/Fabrication#211]
As title says the game crashes with "Forgery" installed when rendering an entity with the glowing effect holding a shield with a banner pattern applied to it. 
Crash does not happen if "Forgery" is removed

quick steeps to reproduce would be to summon via command any entity with a shield with a banner pattern applied and apply the glowing effect to it, example command using armor stand

/summon armor_stand ~ ~ ~1 {HandItems:[{id: "minecraft:shield", Count: 1b, tag: {Damage: 0, BlockEntityTag: {id: "minecraft:banner", Patterns: [{Pattern: "cr", Color: 0}, {Pattern: "sc", Color: 14}, {Pattern: "cbo", Color: 0}], Base: 14}}}]}

/effect give @e minecraft:glowing 20

https://gist.github.com/TheOldOne822/5a49d6957775cf52d3f0e76cac2d8734

There was no "debug.log" only a "latest.log" as such experience with most devs tells me this will never even be attempted to be fixed

**Comment by exaskye** [comment]
Interesting. Shouldn't be hard to fix.
