### ISSUE TITLE
Disconnect when someone does /hidearmor when armor is already hidden

### ISSUE THREAD

**Issue by s351929** [FalsehoodMC/Fabrication#212]
Everybody in the vicinity gets disconnected from the server. Not sure whether this happens if only Fabrication is loaded, sorry can't test without stopping the server and making other people test with me, and I'm not gonna do that.

**Comment by s351929** [comment]
Steps to reproduce:
Type "/hidearmor"
Type "/hidearmor" again

**Comment by Cynosphere** [comment]
Cannot replicate on vanilla server, just get "All specified slots are already hidden" in chat. Modlist?

**Comment by s351929** [comment]
BetterCaves
BetterMineshafts
Better-Signs-And-Frames
BettersleepPlus
Environmental Creepers
Fabric API
Fabrication
Carpet
FastFurnace
Lithium
Phosphor
ore-readout
SaveMyStronghold
vanish (now that i think of it this might be it, they too edit armor packets)
YungsApi

**Comment by Cynosphere** [comment]
Still can't replicate even with those mods. Maybe one of them updating fixed it somehow.

Versions if you want to compare:
![image](https://user-images.githubusercontent.com/1606710/115749712-9ce89280-a354-11eb-90bb-439552cbe3b1.png)

**Comment by s351929** [comment]
Thanks! I appreciate the help, I'll update them and see if it helps.

**Comment by s351929** [comment]
Only carpet was out of date, and that didn't fix it. Hard to say what it is 🤷‍♀️ Thanks again for the help :)
At least it's not game breaking haha
