### ISSUE TITLE
[Urgent]Items with rightclick functionalities will dupe upon break

### ISSUE THREAD

**Issue by Neubulae** [FalsehoodMC/Fabrication#22]
of course I'm describing the `return_on_break` functionality.
Seems like it will be calculated twice instead of once.

**Comment by exaskye** [comment]
Does this happen for all tools (esp. vanilla tools) or just specific ones?

There are a couple things other mods could do that would cause this, and I haven't had this issue with just Fabrication installed.

**Comment by Neubulae** [comment]
> Does this happen for all tools (esp. vanilla tools) or just specific ones?
> 
> There are a couple things other mods could do that would cause this, and I haven't had this issue with just Fabrication installed.

Specific ones that has **right-click** functionalities. i.e. they break upon a right-click. For instance, shears, flint and steel, etc.

**Comment by exaskye** [comment]
Er, sorry. I can't read.

**Comment by Neubulae** [comment]
Netherite hoes are suddenly very useful :thonk:

**Comment by exaskye** [comment]
Root cause is in some cases items could end up breaking twice, so I added an NBT tag that prevents further drops.

**Comment by exaskye** [comment]
Fix released as [v1.2.3_02](https://github.com/unascribed/Fabrication/releases/tag/v1.2.3_02).
