### ISSUE TITLE
Forgery isn't referred to as Forgery in-mod, but as Fabrication instead

### ISSUE THREAD

**Issue by saltyseadoggo** [FalsehoodMC/Fabrication#237]
https://gist.github.com/saltyseadoggo/4c71ef4bf20d75b3f94b9f089b1ad165

[Fabrication] Toggle Stance, under the Controls menu, should be [Forgery] Toggle Stance in Forgery.

![2021-05-18_14 49 38](https://user-images.githubusercontent.com/69029346/118728234-aeed1200-b7e8-11eb-9e5e-c38bec830120.png)

Edit: Also occurs in Forge's mod list. I can see this being confusing for anyone with a big mod list who is unaware of Fabrication and its relation to Forgery, who could thusly end up scratching their head for an hour trying to figure out what Fabrication is.
![2021-05-18_14 59 58](https://user-images.githubusercontent.com/69029346/118729054-0f308380-b7ea-11eb-9647-ae166e22d129.png)

**Comment by Cynosphere** [comment]
Forgery technically refers to the runtime to get Fabrication working on Forge. Even though the mod is shipped as "Forgery", it is still referred to as Fabrication.

I personally see no point in adding extra code to fix this just for a case of semantics.

**Comment by saltyseadoggo** [comment]
I can see it being confusing for players who aren't aware of the relation between the two mods. *"What the hell is Fabrication? I don't have a mod by that name loaded..."* They might struggle to find the config to tweak its features as well if searching 'Forgery' in the mod list doesn't yield anything. Not everyone will put together that *"Forgery is really a disguised version of Fabrication"* means "This is literally Fabrication, ignore the Curseforge page and .jar name." And, finally, simply having the branding be consistent would look more polished in my opinion.

**Comment by exaskye** [comment]
Yes, this is confusing, and I'd like to do something about it. Just haven't bothered yet.

**Comment by pm065** [comment]
For me it was more 'Huh? Where's the forgery config?' instead of 'What the heck is fabrication?'. But yeah, support. And take as long as you like, since it's not critical by any stretch of the imagination :)
