### ISSUE TITLE
Error upon connection to the Hypixel Server Network.

### ISSUE THREAD

**Issue by torzod** [FalsehoodMC/Fabrication#238]
This error seems to only occur when connecting to Hypixel, and it seems that the same error occurs several times in a row. One of these several error instances has been copied into [this gist](https://gist.github.com/torzod/ac6dff77448b53b8c7418f299b90b4e4), as the others are identical. It's curious that ☃ is used but I know very little about Java, it's possible this is maybe a placeholder?

**Comment by exaskye** [comment]
The snowman is a placeholder for obfuscated variable names used by Minecraft. The history on why this happens is a little complicated and not relevant here.

The NPE is somewhere in vanilla code and is related to scoreboard teams. Hypixel has various forms of mod prevention and an absolutely horrifying protocol hackery layer they use to run the servers on 1.8 but allow newer clients to connect, so I don't think I can really consider this a supported configuration.

**Comment by exaskye** [comment]
Not closing pending some research once I'm back working on mods, but it's likely this is a wontfix.

**Comment by exaskye** [comment]
Yeah, I can't support a server network that is actively hostile to mods. Closing.
