### ISSUE TITLE
Arclight conflicts with note block tweaks

### ISSUE THREAD

**Issue by zijiren233** [FalsehoodMC/Fabrication#241]
[debug.log](https://github.com/unascribed/Fabrication/files/6533337/debug.log)

**Comment by exaskye** [comment]
Arclight is conflicting with Fabrication's note block tweaks. Turn them off.

Generally when other invasive mods are present, I would recommend setting Fabrication's profile to Green and disabling Runtime Checks, and only enabling features you explicitly want.

Closing as I can't really be expected to support a mod that infests a normal modded environment with an API with as much legacy baggage as Bukkit.
