### ISSUE TITLE
Grindstone Disenchantment Not Working

### ISSUE THREAD

**Issue by Sixdd6** [FalsehoodMC/Fabrication#242]
When I try to put a book in the bottom slot on the grindstone it just doesn't accept it, even shift-clicking doesn't move the book to the slot. Please note the first log provided is from version 1.3.3 however the same behavior was observed with version 1.3.4 as well in the second log.

[version 1.3.3 debug.log](https://gist.github.com/Sixdd6/04a7cb02ce9c7ca54a3bfeac1068250e)
[version 1.3.4 debug.log](https://gist.github.com/Sixdd6/6e1e9f5b8cfbc1cf1997f4bcbffe00d0)

**Comment by exaskye** [comment]
Cannot reproduce in an environment with just Forgery.

You have Charm, so this is likely actually #281.
