### ISSUE TITLE
Crash when Forgery meets ImmersivePortals

### ISSUE THREAD

**Issue by Ziffle1** [FalsehoodMC/Fabrication#256]
[latest.log](https://github.com/unascribed/Fabrication/files/6743254/latest.log)

With forgery active in a world with existing immersiveportals, minecraft crashes to desktop
With forgery active in a world without any immersiveportals, minecraft crashes to desktop when creating a portal

**Comment by Cynosphere** [comment]
Nothing in the log show that its Fabrication's fault. Immersive Portals for Forge is purposely unsupported and unmaintained as is.

**Comment by Ziffle1** [comment]
Makes sense, i just wish it was maintained. sad

**Comment by exaskye** [comment]
This is a *gigantic* modpack and the implicated part of code is something Fabrication does not patch.
