### ISSUE TITLE
Failed to submit Matomo data

### ISSUE THREAD

**Issue by S-K-Tiger** [FalsehoodMC/Fabrication#257]
While I'm not experiencing problems I can attribute to the mod I still wanted to report this.

[latest.log](https://gist.github.com/S-K-Tiger/7c5dba0ff651338a5f0c3546166598b8)
[fabricationConfig.zip](https://github.com/unascribed/Fabrication/files/6784232/fabricationConfig.zip)

Steps:
1. Using [MultiMC](https://multimc.org/) 0.6.12 created a new Minecraft 1.16.5 instance (Also adds 'LWJGL 3' 3.2.2)
2. Used MultiMC to install Fabric 0.11.6 (Also installs Intermediary Mappings 1.16.5)
3. Added Fabric API 0.36.0+1.16 and Fabrication 1.3.4
4. Ran instance. While there where warnings these would be reported.
5. Closed instance. Replaced configs with those linked above and ran instance again.
6. Logs mention failure to submit Matomo data.

Let me know if you need/want to know anything else to fix this issue and others mentioned in the logs.

**Comment by exaskye** [comment]
My Matomo instance is down due to PHP being a nightmare; I've been doing other things so I didn't notice. Fixing this now.
