### ISSUE TITLE
Forgery/Potion of Bees crash when throwing said potion

### ISSUE THREAD

**Issue by Freshah** [FalsehoodMC/Fabrication#258]
Hello, when Forgery is installed alongside [Potion of Bees](https://www.curseforge.com/minecraft/mc-mods/potion-of-bees), upon using the items the game crashes.

I know this mod has a lot of toggle-able features and fixes.  even if a change can't be made on your end, is there a potential conflict I could disable?

Thanks for your time.

[debug.log](https://github.com/unascribed/Fabrication/files/6788066/debug.log)
[crash-2021-07-08_21.16.11-server.txt](https://github.com/unascribed/Fabrication/files/6788067/crash-2021-07-08_21.16.11-server.txt)

**Comment by Bluberry-Kat** [comment]
for now, try turning off Cracking Spawn Eggs, found in the Tweaks section

**Comment by Freshah** [comment]
...and in under 2 minutes, my issue is fixed!  Thanks!  Apologies if this was a known issue.

**Comment by exaskye** [comment]
I believe this was already fixed in #239, but that's only available in a prerelease right now, and at the time of the creation of this issue, there was no prerelease.
