### ISSUE TITLE
Minecraft block logo looks weird

### ISSUE THREAD

**Issue by samozoid** [FalsehoodMC/Fabrication#259]
The only reason I suggested the dirt background was to fix this issue and thought that this issue could be fixed as its in the mod not outside, I guess that was a waste of my time as the same issue happens here.

https://imgur.com/a/JPdq9Hy

**Comment by exaskye** [comment]
????????

Could you send a crash report so I can see your system specs and such? (Hold F3+C for 10 seconds then release to force a crash, even in the menu)

**Comment by exaskye** [comment]
No response, closing as cannot reproduce.
