### ISSUE TITLE
[1.17] Tridents get duplicated heavily on Fabrication 2.0.0 pre2

### ISSUE THREAD

**Issue by LambdAurora** [FalsehoodMC/Fabrication#276]
## Steps to reproduce:

 - Enable `tweaks.tridents_in_void_return`
 - Get a loyalty trident
 - Throw it anywhere
 - When returning the trident entity doesn't despawn and you get tridents infinitely.
 
 ## Screenshot
![image](https://user-images.githubusercontent.com/12587332/128548210-656dfdf6-8d39-4156-8e35-fa72fdb389e4.png)

## Logs

[The logs](https://gist.github.com/LambdAurora/bc0535aa9443967cd74563880149c5ac)

## Additional notes

The issue wasn't happening with Fabrication 1.3.4 (1.16) on 1.17.1.

**Comment by exaskye** [comment]
Fix released with [v2.0.0-pre3](https://github.com/unascribed/Fabrication/releases/tag/v2.0.0-pre3)
