### ISSUE TITLE
Sync Attacker Yaw not working

### ISSUE THREAD

**Issue by emortaldev** [FalsehoodMC/Fabrication#28]
Sync Attacker Yaw seems to stop working (goes back to default behavior) after player dies

Mods:
- fabric api
- lithium
- starlight
- fabrication (obviously)
- overworld two

I am using Java 15 OpenJ9 (but I doubt that would be the problem)

**Comment by exaskye** [comment]
Grr. I think I know exactly what is wrong here and it's such a silly mistake...
