### ISSUE TITLE
Incompatbility with Item Physics (Physics Mod, Interactic)

### ISSUE THREAD

**Issue by Kryllex** [FalsehoodMC/Fabrication#280]
No crashes, but for some reason even with every single feature set to banned or disabled thru the preset (of course after game launch to confirm changes), 3D item physics specifically in the form of items flipping through the air, landing flat on the ground, being "objects" is cancelled out by the Fabrication mod and all subsequent items are shown as the regular, floating variant. 

Very specific issue, but decided it was worth mentioning.

**Comment by Toilet-Lord** [comment]
Bump, I have this problem since a long time and I absolutely would love this issue to be fixed

**Comment by SFort** [comment]
cannot reproduce using fabrication 2.3.0-exp2 and [ItemPhyscs 1.4.0](https://github.com/MorningSage/ItemPhysicLite-Fabric/releases/tag/1.4.0)

**Comment by Toilet-Lord** [comment]
> cannot reproduce using fabrication 2.3.0-exp2 and [ItemPhyscs 1.4.0](https://github.com/MorningSage/ItemPhysicLite-Fabric/releases/tag/1.4.0)

Use [1.18+] Interactic - 0.1.8

**Comment by SFort** [comment]
![screenshot](https://user-images.githubusercontent.com/1879846/155316095-6e52b4cd-2601-477d-9f3c-2d2c9bcd85a5.png)
