### ISSUE TITLE
Grindstone Disenchanting is incompatible with Grind Enchantments and Charm's ExtractEnchantments

### ISSUE THREAD

**Issue by deftesthawk** [FalsehoodMC/Fabrication#281]
When I combine these 3 mods together and try to extract enchantments from a tool/weapon/armor they conflict.
(I used a diamond pickaxe in my test examples) 

----------------------------------------------------------------------------------------------------------------------------------------------

### **Test 1**

Charm Config: "ExtractEnchantments Enabled" = true

Grind enchantments mod enabled 

Results: everything works as it should

----------------------------------------------------------------------------------------------------------------------------------------------

### **Test 2** 
Charm Config: "ExtractEnchantments Enabled" = true

Fabrication/Features Config: grindstone_disenchanting=(false/true/unset all give the same result)

Grind enchantments mod (enabled/disabled both cause same results) 

Results: Having the pickaxe in the top slot causes the pickaxe to duplicate, I don't get the enchantments back and it costs XP. 

----------------------------------------------------------------------------------------------------------------------------------------------

### **Test 3** 

Charm Config: "ExtractEnchantments Enabled" = false

Fabrication/Features Config: grindstone_disenchanting=true

Grind enchantments mod enabled 

Results: Having the pickaxe in the top slot causes the pickaxe to duplicate, I do get the enchantments applied to the book and it costs XP. 

----------------------------------------------------------------------------------------------------------------------------------------------

### **Test 4** 

Charm Config: "ExtractEnchantments Enabled" = false

Fabrication/Features Config: grindstone_disenchanting=true

Results: everything works as it should

----------------------------------------------------------------------------------------------------------------------------------------------

### **Test 5** 

Charm Config: "ExtractEnchantments Enabled" = true

Fabrication/Features Config: grindstone_disenchanting=false

Results: Having the pickaxe in the top slot causes the pickaxe to duplicate, I don't get the enchantments back and it costs XP. 

----------------------------------------------------------------------------------------------------------------------------------------------

### ** My request**

1.) Could you either add a feature that allows you to separate enchantments by putting an enchanted book with an empty book in the Grindstone as this is why I want to use the Grind enchantments mod.

2.) Or could you fix the conflict, weirdly enough I'd expect the unset option to allow the mods to work together as in my theory it shouldn't touch the code if it's set to unset.

**Comment by exaskye** [comment]
> I'd expect the unset option to allow the mods to work together as in my theory it shouldn't touch the code if it's set to unset.

It won't touch the code if set to `false` (`banned` in 2.0) and the game is then restarted to unload the mixin. `unset` is a "soft" disable if the profile is set to Green, otherwise what it means depends on your selected profile.

I can add Grind Enchantments as a conflicting mod for Grindstone Disenchanting.

**Comment by SFort** [comment]
i'd also add it to `invisibility_splash_on_inanimates` as charm causes an item generation bug whenever frames are invisible

**Comment by deftesthawk** [comment]
Thanks, I just tried the banned option and that seemed to allow all 3 to work together :)
Didn't know that was an option as I've been changing the configs using notepad, not mod menu. as my modpack takes a while to load. It doesn't show the banned in the config

**Comment by deftesthawk** [comment]
+ yeah I forgot to mention I was using the green profile. Thanks for the absolutely incredible config file you've created, it is so easy to understand all the options. Other mod configs aren't done to this level of perfection

**Comment by deftesthawk** [comment]
So for anyone in the future, to get them working together do the following:

Charm Config: "ExtractEnchantments Enabled" = true

Fabrication/Features Config: grindstone_disenchanting=banned

Grind enchantments mod enabled/installed

**Comment by exaskye** [comment]
> Didn't know that was an option as I've been changing the configs using notepad, not mod menu. as my modpack takes a while to load. It doesn't show the banned in the config

Oh yeah, I never updated that. Oops.
