### ISSUE TITLE
Fullres Banner Shields crash when rendering a spawner of strays holding a shield

### ISSUE THREAD

**Issue by TheVisionaryOne** [FalsehoodMC/Fabrication#284]
I'm not sure if this is exclusive to strays, or even related to spawner blocks themselves, but I encountered crashing near stray spawners, and it seemed exaggerated when I was looking at the spawner blocks themselves.

This was on a 1.16.5 Forge custom modpack, using Forgery (a fork of Fabrication) with ~150 mods, so it's very possible the issue is more complex. What led me to pinning Forgery as the culprit of the crash was when I noticed multiple mentions of "janky arm" in the crash report. Also lots of stuff about banner shields and crossbows. From what I can gather, Forgery's janky arm feature should only affect the player, not mobs, but I thought I might as well drop this crash report here and see if anything of value can be gathered from it.

I've removed Forgery from the modpack, and the pack's been running absolutely fine. It appears that Forgery is indeed the culprit, but I'm a little weirded out as to why. Side note...if the Janky Arm feature is indeed the culprit, is there an easy way for me to toggle it off, and continue using Forgery without it? I don't have much experience with this mod, but I don't see a config file.

Here's the crash report: 
[crash-2021-08-28_13.07.56-client.txt](https://github.com/unascribed/Fabrication/files/7073039/crash-2021-08-28_13.07.56-client.txt)

**Comment by exaskye** [comment]
Forgery is not a fork of Fabrication, it *is* Fabrication.

Janky Arm has nothing to do with this, it's Fullres Banner Shields. You can go to the Fabrication config screen under Mods and set any feature to disabled and restart the game to prevent the mixin from loading.

Try updating to v1.3.5 RC2, I believe this bug is fixed in that version. I'll be making a proper v1.3.5 release soon.

**Comment by exaskye** [comment]
Yeah, this was fixed in commit a7e1d50de5f13c40ab17aefd5068dc855c4eecbc for #211, but the commit is only in v1.3.5 at this point.

**Comment by exaskye** [comment]
Lacking any additional feedback, I'm fairly certain this is already fixed as described. Feel free to let me know if this isn't the case.
