### ISSUE TITLE
Trident appears as 3D with billboard items on

### ISSUE THREAD

**Issue by Simple205** [FalsehoodMC/Fabrication#286]
![image](https://user-images.githubusercontent.com/73256738/132590849-087b8be8-b295-4a8a-8db0-096c4c392dc9.png)

(I cant say if this issue happens on the forge version as well, I assume it does but I don't know since I've only played on the fabric version.)

**Comment by exaskye** [comment]
The trident has a ton of special cases in the vanilla item renderer. Will have to look into why this happens...
