### ISSUE TITLE
Incompatible with Mixin v0.8.4+

### ISSUE THREAD

**Issue by WenXin20** [FalsehoodMC/Fabrication#290]
`Minecraft v1.16.5`
`Forge v36.2.5`
`Forgery v1.3.5-rc2`

After updating my server to Forge v36.2.5, it started crashing on load with mixins. No other mods are installed. According to the Forge changelog, Mixins were bumped up to v0.8.4. Going back to Forge v36.2.4 works for now.
[Debug Log](https://gist.github.com/WenXin20/d41d4d573b5fc798e989930bcf2254e3)

**Comment by Corvus20** [comment]
It is also incompatible with Forge 36.2.6 as well.

**Comment by exaskye** [comment]
This seems to have come up again but under Fabric. I don't know why, I ported this fix to the 1.17 branch, and I tested v2.1.0 with FLoader v0.12.7 (the latest) before releasing it...

**Comment by gniftygnome** [comment]
Regarding the testing part you just mentioned, it loads fine for me unless Vistas is also present (which is why I conflated it for the other issue).

**Comment by exaskye** [comment]
...What happened is that Mixin has changed *again*. The fix *was* applied, but they broke the same API in basically the same way.

God damn it.

**Comment by gniftygnome** [comment]
Heh!  Well that's ... about par for the course, lately.

**Comment by gniftygnome** [comment]
Confirmed fixed, lightning fast.  Thanks =)
