### ISSUE TITLE
Reference map 'pride-refmap.json' for pride.mixins.json could not be read.

### ISSUE THREAD

**Issue by FewerFlaws** [FalsehoodMC/Fabrication#302]
https://gist.github.com/FewerFlaws/d9dd128d76ac158db9b037f70639c690
`Reference map 'pride-refmap.json' for pride.mixins.json could not be read. If this is a development environment you can ignore this message` appears in my logs.

**Comment by Cynosphere** [comment]
Non issue. Anything tagged WARN is mostly debugging and can be safely ignored.

**Comment by exaskye** [comment]
The cause is PrideLib, a dependency of Fabrication, contains boilerplate for using mixins but does not actually have any mixins.

Cynosphere is right that this is safe to ignore and therefore incredibly low priority.

**Comment by exaskye** [comment]
Fixed by Queerbric/pridelib#4
