### ISSUE TITLE
Obsidian Tears and Respawn Anchor

### ISSUE THREAD

**Issue by Whataheckisasonic** [FalsehoodMC/Fabrication#311]
i didnt receive any crash-log but theres a thing it that makes no sense. you can use obsidian tears to set a respawn point in the nether. which makes no sense because.... whats the point of the respawn anchor then? i think it should only work in the overworld.

**Comment by exaskye** [comment]
Obsidian tears respawn is imperfect, giving you below full health, no saturation, and below full food.

**Comment by Whataheckisasonic** [comment]
oh well. - i didnt see any of that. so i did rather deactivate it.
