### ISSUE TITLE
[Déjà Void] only works if you jumped from a full block and it can kill you in creative

### ISSUE THREAD

**Issue by MSandro** [FalsehoodMC/Fabrication#312]
Hi, I've included your mod in my Modpack Sky FABRICation 2. 
I would like to use the Feature Déjà Void, but it does not work if a player falls from a slab or any other not full sized block.
And the feature can kill you in creative. I think this is not intended.

I hope you can improve the feature. Despite the problems, I would like to use the function. It would be a lot better than my KubeJS script.

**Comment by exaskye** [comment]
Deja Void deals void damage, which bypasses creative. This is intended.

I guess the thing that is trying to fix your respawn location is ignoring slabs.

**Comment by MSandro** [comment]
okay thanks.
True, I fail when respawning through e.g. slabs and chests. It may be enough to increase the Y level by one block.
