### ISSUE TITLE
Make renaming items always cost 1 level regardless of "RepairCost"

### ISSUE THREAD

**Issue by Insane96** [FalsehoodMC/Fabrication#32]

**Comment by exaskye** [comment]
"RepairCost" is the "prior work penalty" disabled by the current anvil feature.

I've wanted to make a "renaming always costs 1" tweak since 1.0 but the necessary Mixin was surprisingly complex so it got postponed. Will look at it again soon.

**Comment by exaskye** [comment]
I was definitely overcomplicating this when I looked into it before. It was pretty easy to implement.
