### ISSUE TITLE
Incompatibility with Vistas (Crash)

### ISSUE THREAD

**Issue by Qendolin** [FalsehoodMC/Fabrication#327]
Fabrication 2.0.0 is incompatible with the [Vistas Mod](https://www.curseforge.com/minecraft/mc-mods/vistas) because of a clash in `net/minecraft/client/gui/screen/TitleScreen`.

Versions:
- Fabric API 0.40.1
- Vistas 1.4.4
- Fabrication 2.0.0_01
- Fabric Loader 0.12.5
- Minecraft 1.17.1

[Log](https://paste.ee/p/4fGco)

**Comment by Cynosphere** [comment]
Could probably also add `configAvailable="*.dirt_screen"` to the dirt screen's EligibleIf annotation as a fix but I'd rather have Vistas fix it on their end for other mods as well.

**Comment by Qendolin** [comment]
I'm not sure what `configAvailable` does but I'ld expect `dirt_screen=banned` in the config to fix the issue but it doesn't.

**Comment by exaskye** [comment]
`configAvailable` is the part of Fabrication's internal "EligibleIf" annotation that determines what mixins belong to which features. The absence of it on the dirt screen mixin made that mixin be considered non-optional instead of being assigned to a feature and allowed to fail soft.

**Comment by gniftygnome** [comment]
Is this expected to be resolved in fabrication 2.1.0_01?  Because a fresh install with the following mods still crashes with what appears to be roughly the same stack trace.

fabric loader 0.12.8
fabric-api-0.43.1+1.17.jar
fabrication-1.17-2.1.0_01.jar
vistas-2.0.0.jar

```
Caused by: java.lang.NoSuchMethodError: 'org.spongepowered.asm.mixin.refmap.IMixinContext org.spongepowered.asm.mixin.injection.struct.InjectionInfo.getContext()'
	at com.unascribed.fabrication.support.injection.Failsoft.postInject(Failsoft.java:97) ~[fabrication-1.17-2.1.0_01.jar:?]
	at com.unascribed.fabrication.support.injection.FailsoftRedirectInjectionInfo.postInject(FailsoftRedirectInjectionInfo.java:21) ~[fabrication-1.17-2.1.0_01.jar:?]
[...]
```

**Comment by exaskye** [comment]
Not even slightly the same error. This is #290.

**Comment by gniftygnome** [comment]
I don't understand ... do you mean Fabric has ported some Forge functionality and brought over a forge bug?

**Comment by gniftygnome** [comment]
Adding a gist with the entire log just in case it's useful.
https://gist.github.com/gniftygnome/16f650161f66377eb8c7c7dbe9b933f2#file-fabrication-vistas-latest-log

**Comment by exaskye** [comment]
#290 is about Forge updating Mixin. Fabric has now also updated Mixin.

**Comment by gniftygnome** [comment]
Ahh, OK.  Sorry to have muddied the waters then.  Fortunately we can run without Fabrication on the clients for now (various other mods involved have forced us to move our mod pack to loader versions > 0.12.5).
