### ISSUE TITLE
Issues With weird_tweaks.repelling_void 

### ISSUE THREAD

**Issue by IAmSneak** [FalsehoodMC/Fabrication#34]
Sometimes when jumping into the void you will get teleported to the surface and take 1 tick of void damage then die, even if at full health. This will put your items at the surface, but won't allow you to live. This is somewhat inconsistent,

When attempting to void jump in the end you fall out of the world and it doesn't teleport you at all.

**Comment by exaskye** [comment]
I can't reproduce this. Please send a complete game log.

**Comment by exaskye** [comment]
Reproduced entirely on accident under Forge. At least I think it's the same bug.

**Comment by exaskye** [comment]
I believe this is fixed in 2.0.0 due to a change in how it hooks.

I'll be backporting this to 1.16/1.x soon.
