### ISSUE TITLE
[1.18] Crawling through 1x1 spaces is impossible

### ISSUE THREAD

**Issue by SplendidAlakey** [FalsehoodMC/Fabrication#347]
**MC** 1.18
**Fabric** loader 0.12.8; API 0.41.3
*Fabrication** 1.18-2.1.0-exp2

To reproduce:

1. Enable crawling
2. Build or find a 1x1 space between blocks
3. Try to crawl into it
4. Constantly rubberband out

Logs: https://gist.github.com/Footage2-Amply-Pounce/94457dd8f20c56ba95215ca93ebadc15

**Comment by Cynosphere** [comment]
Ensure the server has Fabrication installed with Crawling enabled serverside.

**Comment by exaskye** [comment]
I was going to say this, but the log is singleplayer.

**Comment by SplendidAlakey** [comment]
This happens in single-player.

Just tested with every single feature, except crawling, banned - same result, crawling with a keybind rubberbands me out of 1 block high spaces. I can still cram myself with a trapdoor. I first discovered it on a server that had the mod installed and crawling enabled, but it behaves the same in single-player.

**Comment by SplendidAlakey** [comment]
I don't see any commits related to this issue, but it's fixed in fabrication-1.18-2.2.0-exp3.

**Comment by Lv44EnderShaman** [comment]
I hate to be the bearer of bad news, but I believe this issue should be re-opened.

MC Version: 1.18.2
Fabrication Version: fabrication 1.18-2.3.1-exp3
Fabric Loader: 0.13.3
Fabric API: 0.48.0-1.18.2
Java Version: Eclipse Adoptium JDK 17.0.2.8-Hotspot
OS: Windows 11 Pro (21H2)

I've been using fabrication-1.18-2.3.1-exp3 and it looks as if this has been reverted by an unknown change somewhere; the player's collision box, when attempting to enter a 1-block high space, acts as if it cannot enter the area. The model begins to subtly rubberband out again, stuttering in both first-person and third-person views.

I have tested it with my usual options enabled (of focus, typically Toggle Stance and Crawling together among them) and with just Crawling enabled by itself, as well as just Crawling and Toggle Stance. Same result in all three instances.

I believe it may be related to the player's detectable collision box, as trapdoors can still compress a player down into the crawling stance, but attempting to enter a 1-block high space outside of it causes the rubberbanding issue; maybe the player's collision box isn't being translated or transformed correctly from the standing and sneaking stances down to the crawling stance?

EDIT: I should note, this is happening -- once again -- in Single-Player. Tested within a Creative world, Superflat.

**Comment by SplendidAlakey** [comment]
Yeah, the issue reappeared in 1.18.2.

**Comment by Lv44EnderShaman** [comment]
I see that @SFort has made a commit that references this. I'm guessing that my analysis was closer to the mark than I thought, then, and that the player entity's hitbox isn't translating to the crawling/swimming stance correctly?

**Comment by SFort** [comment]
the issue was i fucked up at some point which caused the crawl packet to be ignored by the server depending on the mixin load order. ~kinda a good thing i did i guess?~ since i've also  fixed another issue while i was at it
