### ISSUE TITLE
Special item status data is not saved

### ISSUE THREAD

**Issue by IAmSneak** [FalsehoodMC/Fabrication#35]
Player drops set to invincible when dying in the nether can burn and get destroyed. If it is a specific item set to not burn, the item will not burn and will work fine. This works as expected in the overworld.

**Comment by exaskye** [comment]
Forge or Fabric?

**Comment by IAmSneak** [comment]
fabric for both reports

**Comment by IAmSneak** [comment]
this seems to also be an issue when dying in the end

**Comment by exaskye** [comment]
Reproduced. How strange.

**Comment by exaskye** [comment]
True cause: Invincibility/etc state of items is not saved. If the chunk unloads, the special item despawn rules will end up being ignored.

If you had a Respawn Anchor right next to where your items dropped, then this wouldn't occur.
