### ISSUE TITLE
Error with Forgery - "Cannot look up value for config key general.runtime_checks with no default"

### ISSUE THREAD

**Issue by SpedicyWasTaken** [FalsehoodMC/Fabrication#353]
Hi, I have this error with Forgery, "Cannot look up value for config key general.runtime_checks with no default", and I think it may be what is preventing my game from starting. (Also, if this isn't the place to report errors with the forge port of this mod, let me know.)

![image_2021-12-04_204856](https://user-images.githubusercontent.com/82922884/144732688-3bfa8996-6302-4c1e-9706-6cf891e870fe.png)
[latest.log](https://github.com/unascribed/Fabrication/files/7655182/latest.log)

**Comment by exaskye** [comment]
The latest 1.x pre-release is kind of busted. I'm going to scrap it and replace the 1.16 builds with a backport of the new 2.x code.

**Comment by exaskye** [comment]
v2.2.1 for 1.16 has been released.

**Comment by SpedicyWasTaken** [comment]
Thank you
