### ISSUE TITLE
Failures to initialize certain features

### ISSUE THREAD

**Issue by IdrisQe** [FalsehoodMC/Fabrication#357]
Tried the new version in a clean 1.16.5 instance with only Forge and Forgery. The following features failed to initialize despite that:
_Mobs Drop Less Metal
Dropped Items Don't Stack
Full Enchanting Cost_

https://gist.github.com/IdrisQe/f2c426d3960558579bc475b601c23610

**Comment by exaskye** [comment]
Known, actually. I was putting off fixing these as it was 4 AM.
