### ISSUE TITLE
Config not saving

### ISSUE THREAD

**Issue by IdrisQe** [FalsehoodMC/Fabrication#358]
In 1.16.5 I tried the new version of Forgery, and realized after quitting the game that my config changes applied through the config menu hadn't actually saved. I made a new instance with only the same Forge and Minecraft version I was using, and Forgery, and tried again, and the same thing happened. The configs appear to save, you can exit the menu and go back to the mod menu, and re-open the menu, and it still shows your changes. But upon checking the file or closing the game, you'll find that everything is back to being unset.

https://gist.github.com/IdrisQe/f2c426d3960558579bc475b601c23610

**Comment by exaskye** [comment]
God damn it, again?
