### ISSUE TITLE
[Fabric 1.18] Crash on startup with Fabrication 2.2.0 and 2.2.1

### ISSUE THREAD

**Issue by AnotherVagabond** [FalsehoodMC/Fabrication#359]
"Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: LVT in net/minecraft/class_1686::method_7500()V has incompatible changes at opcode 102 in callback fabrication.mixins.json:e_mechanics.enhanced_moistness.MixinPotionEntity->@Inject::damageEntitiesHurtByWater(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;Lnet/minecraft/class_238;)V from mod fabrication."

https://pastebin.com/AgSieaam

Reverting to Fabrication 1.0.0 fixes the crash.

**Comment by exaskye** [comment]
Set `enhanced_moistness` in config/fabrication/features.ini to `banned`. Another mod you have installed is overwriting a method Fabrication injects into.

**Comment by AnotherVagabond** [comment]
Huh, that did fix it, even though nothing else changed. Just out of curiosity, did you change the way you handle the moistness thing? It went from working pre-update to not working after the updates, and nothing about any of the other mods changed. Though modded Minecraft seems to crash if you sneeze in its general direction, so I guess it could literally be for no reason at all.

Anyway, thanks! It's working again.

**Comment by exaskye** [comment]
If you can narrow down which mod is incompatible, I can look further into this.

**Comment by AnotherVagabond** [comment]
I don't really know where I'd look, since none of the other mods had even been updated, and none of them mess around with splash water bottles or Endermen as far as I'm aware. And to be completely honest I don't really have the patience for a 50/50 test. I'm okay with just turning the water thing off for now, thanks for the help though.
