### ISSUE TITLE
Mixin conflict with Chest Cavity results in launch crash

### ISSUE THREAD

**Issue by AeiouEnigma** [FalsehoodMC/Fabrication#372]
[latest.log gist](https://gist.github.com/AeiouEnigma/ef8d9ec1c95ade7c5bbeec517ffbd1f6)

[conflicting Inject in Chest Cavity](https://github.com/Tigereye504/chestcavity/blob/0d45d167f31bb020422dec7a3718915e8b275634/src/main/java/net/tigereye/chestcavity/mixin/MixinPotionEntity.java#L38)

Chest Cavity's Inject into PotionEntity::damageEntitiesHurtByWater prevents Fabrication's Inject from being able to access the local Box variable. A possible fix might be to adjust the priority of Fabrication's MixinPotionEntity class, but I'm unsure whether there's a better solution than that.

**Comment by Tigereye504** [comment]
Conflict fixed in Chest Cavity 2.13.4. Changing the priority of my injection worked.

**Comment by exaskye** [comment]
...Why does a TAIL inject like this rearrange the LVT?

Sigh. Whatever. If this is fixed on the other end I'll close this.

**Comment by Tigereye504** [comment]
I don't know, I am as confused about it as you are. I thought that my injections were about as conflict-safe as they can get but here we are.
