### ISSUE TITLE
Encroaching Emeralds setting causes crash upon creating new world

### ISSUE THREAD

**Issue by aisukuma** [FalsehoodMC/Fabrication#373]
Whenever I try to create a new world, this setting seems to cause a crash. 

To reproduce this:
- Enable Encroaching Emeralds setting
- Save settings and exit Minecraft and restart instance
- Try to create a new world

[Gist link](https://gist.github.com/aisukuma/bb171fc20dc941fdb09940e9ce809a99)

**Comment by exaskye** [comment]
Fix (finally) released in 2.3.0_01.
