### ISSUE TITLE
'No Sneak Bypass' breaks Sculk Sensor sneaking

### ISSUE THREAD

**Issue by DarianLStephens** [FalsehoodMC/Fabrication#375]
No crashes, just incorrect behaviour.
With the option enabled, attempting to sneak past Sculk Sensors will instead trigger them, breaking their whole sound-based sneak mechanic.
Reproduced with only Fabrication and Fabric API using vanilla Sculk Sensors, but it also affects mods using the sculk system, like the recent [Sculk Worm](https://www.curseforge.com/minecraft/mc-mods/fabric-sculk-worm) mod, and presumably the future Warden and Deep Dark.
![2021-12-16_14 47 19](https://user-images.githubusercontent.com/15375876/146304842-14e2ee51-ee20-470d-9e4b-2fe4c06b463b.png)
![2021-12-16_14 47 36](https://user-images.githubusercontent.com/15375876/146304845-ab0bcd88-ec53-4519-b916-9917fb6891a0.png)

**Comment by SFort** [comment]
unless una says otherwise, working as inteded.
feel free to make a feature request with an identical function that won't do this though

**Comment by DarianLStephens** [comment]
It breaks an advertised, intentional, vanilla feature, though. Especially when the Deep Dark comes out, if this feature remains unchanged, the entire stealth system will be useless.

**Comment by SFort** [comment]
and therefore there should be a new feature that doesn't do that. 
which you can turn on instead of this one which is meant to "break the entire stealth system"

**Comment by DarianLStephens** [comment]
At the very least, maybe this feature shouldn't be on by default?

**Comment by Pannoniae** [comment]
Considering it is in the tweaks category; it should not break an *entire vanilla mechanic*. Either move it to balance/weird tweaks or patch it so sculk sensors do not get triggered, please.

**Comment by exaskye** [comment]
This feature should not break sculk sensors. This is for things like magma blocks...

Should probably get moved to Extra regardless.
