### ISSUE TITLE
Colorful Redstone doesn't work with Lithium

### ISSUE THREAD

**Issue by Pepe20129** [FalsehoodMC/Fabrication#376]
Log: https://gist.github.com/Pepe20129/36002f05dc51bdb07f3f2f4c70d80375

Colorful Redstone doesn't work with Lithium installed
![2021-12-16_17 30 04](https://user-images.githubusercontent.com/72659707/146417825-2d5f94c5-6a49-4912-b14f-91c99ca5d8c4.png)

**Comment by exaskye** [comment]
Unsurprising.

**Comment by exaskye** [comment]
Add `mixin.block.redstone_wire=false` to the Lithium config.

I can't really fix this in Fabrication as this feature is only conditionally enabled, and I don't want to force Lithium's redstone optimizations off if Colorful Redstone is off.
