### ISSUE TITLE
Blinking Drops is incompatible with Iris

### ISSUE THREAD

**Issue by marrub--** [FalsehoodMC/Fabrication#377]
`iris-mc1.17-1.1.3.jar` + `fabrication-1.17-2.3.0.jar` + shaders on = o no
issue occurs with any version combination of iris and fabrication, tested with the last 3 versions of each

enabled (any shaderpack)
![2021-12-16_17 19 38](https://user-images.githubusercontent.com/5544603/146468095-9672f171-a35a-41d9-b3f9-c581b677fc74.png)

disabled
![2021-12-16_17 19 51](https://user-images.githubusercontent.com/5544603/146468098-0d058c44-8a4d-4958-9cc4-bdbe12be5e3d.png)

either "trivial to fix" or "literally impossible to fix" but i am unfortunately too lazy to figure out how to run renderdoc on a java program, apologies

**Comment by exaskye** [comment]
...Does Iris not implement the white part of the overlay texture?

**Comment by exaskye** [comment]
https://user-images.githubusercontent.com/6185037/180595505-1e9525fc-8dfc-4875-ad5c-650bbf05d62a.mp4

This no longer seems to occur. Assuming this was fixed on Iris' end.
