### ISSUE TITLE
Chat Markdown: Illegal Characters In Chat, Kick From Server

### ISSUE THREAD

**Issue by IdrisQe** [FalsehoodMC/Fabrication#378]
Debug Log: https://gist.github.com/IdrisQe/e428e5bce5f1f8f0bf3d905ae24b8b23
Tested on a fresh 1.16.5 instance with Forge 36.2.20, Forgery 2.3.0-exp2, and no other mods installed, and the only setting changed being "Chat Markdown" set to enabled. Issue occurs in both Singleplayer, and on a Multiplayer server with the mod installed and configured identically both sides.

Issue happens as follows:

-Change Chat Markdown to enabled
-Enter game
-Type \* followed by anything and then another \* such as "\*Test\*"
-Chat message does not send, kicked from server for having "illegal characters" in chat message

**Comment by exaskye** [comment]
Chat Markdown is being removed from Forgery.
