### ISSUE TITLE
Effect level support "Boundless Levels"

### ISSUE THREAD

**Issue by Pepe20129** [FalsehoodMC/Fabrication#38]
Pretty self explanatory.
Allow effect levels to work with Boundless Levels.

**Comment by exaskye** [comment]
Ah, I forgot that vanilla has a hardcoded limit for showing the potion level.

Boundless Levels already patches in support for potion levels in the lang, but the limit in the renderer has to get lifted.

**Comment by exaskye** [comment]
![image](https://user-images.githubusercontent.com/6185037/103491123-ecbb4200-4dd5-11eb-9138-05e591dd500b.png)

**Comment by exaskye** [comment]
Released in [v1.2.8-pre2](https://github.com/unascribed/Fabrication/releases/tag/v1.2.8-pre2).
