### ISSUE TITLE
Utterly baffling incompatibility with Applied Energistics 2 in 1.18.1

### ISSUE THREAD

**Issue by marrub--** [FalsehoodMC/Fabrication#382]
[Log](https://gist.github.com/marrub--/f16a4bf99288d67964e16ab1ed1e3df8)
[Config](https://gist.github.com/marrub--/7badc3e911d4c31b4d0be4805422446a) (I'm using Green with everything disabled set to banned and removed all the comments so you can just search =true)

I'm honestly not sure how this could even happen. Am I cursed, or is AE2? It works with every other mod I throw at it, just specifically combining it with Fabrication -- as noted in the log, nothing else is installed besides AE2, Fabrication, and some mods for better error messages -- murderinates it while populating the world generator data after opening the "new world" dialogue.

**Comment by marrub--** [comment]
It appears that multiple mods create this issue, but AE2 is the only one I could isolate. Same error for all of them in BiomeSource. Additionally, this happens in 1.18-2.3.0 but not 1.18-2.2.1-exp4.

**Comment by SFort** [comment]
#373 it's just a issue not a conflict
(set weird_tweaks.extra.encroaching_emeralds to banned should fix it for now)

**Comment by marrub--** [comment]
Ah, thanks!
