### ISSUE TITLE
Billboard items not accurate

### ISSUE THREAD

**Issue by JimmyHarmel** [FalsehoodMC/Fabrication#389]
"Billboard" items will render a enchant glint which isn't bad but versions that supported enchanting with 2d items (1.0-1.7.10) did not show the glint regardless if the item was enchanted. If this is intentional could you add another option to disable the items enchant glint? Also, items will render with their shading which fast graphics items did not. This makes items look very dark from certain perpectives
![item_lighting_bug](https://user-images.githubusercontent.com/86896069/147702035-9e56af58-0278-4ed1-a759-52432f913fe2.png)
.

**Comment by exaskye** [comment]
Billboard Drops is a shoddy reimplementation that works by rendering modern item models but rescaled to be extremely thin.

Rendering the glint is a feature. The shading bug is known but more complex than it seems.

<sub>I like that you went to the trouble of taking this screenshot in a Shattered Savanna like all my demo videos and screenshots. :P</sub>

**Comment by DarianLStephens** [comment]
To add to this, the billboard items have a weird thing where the shading changes drastically depending on which direction they're facing, which doesn't feel right.
I believe it should just be flat lighting across the whole item based on the light level at its position.

**Comment by exaskye** [comment]
3.1 contains billboard_drops_2d, a more faithful reimplementation of this with poorer compatibility.
