### ISSUE TITLE
[Suggestion] mod_end_tools_useful_in_end

### ISSUE THREAD

**Issue by saltyseadoggo** [FalsehoodMC/Fabrication#39]
I find gold_tools_useful_in_nether to have some interesting potential for modpack development: for example, players can have the choice to start in the Nether or in the Overworld, and the tools that they have available naturally specialize them to life in their respective environments and encourage trading.

I would like to request an extension of this functionality by allowing one to add tools to new **fabrication:end_blocks** and **fabrication:end_blocks_only_in_end** tags that deal 50x durability damage to tools not in a **fabrication:end_tools** tag. This would be useful in mod packs that add new biomes and tool types to the End to make it a viable starting location; without these mods, of course, it would be useless, save for the niche use in making some weird tool super effective against End blocks in vanilla.

In addition to this, as many mods such as Better End or BYG that would be used in such a modpack add new wood or stone types that create the default wooden or stone tools, a tag similar to the 'fungal' tag that modpack creators could apply to wooden or stone tools crafted with these wood/stone types would be appreciated. They could be named 'End Wooden ___' or 'End Stone ___' for widespread compatibility with different material types.~

**Comment by exaskye** [comment]
Folding into #41
