### ISSUE TITLE
Incompatibility with DashLoader when Old Lava is enabled.

### ISSUE THREAD

**Issue by forkiesassds** [FalsehoodMC/Fabrication#392]
When using DashLoader along side Old Lava causes the texture atlas to fail mapping and cause the game to lock up.
[2022-01-05-5.log](https://github.com/unascribed/Fabrication/files/7817671/2022-01-05-5.log)

**Comment by SFort** [comment]
This seams to have been fixed by one of the DashLoader devs. (tested with fabrication 3.4.3, dashloader 4.1.3)
Thanks you very much to whoever it was as i honestly suck at these things.
