### ISSUE TITLE
Increase despawn timer for certain items

### ISSUE THREAD

**Issue by copygirl** [FalsehoodMC/Fabrication#4]
To go with `enchanted_item_long_despawn`, it would be nice if certain special items (based on a whitelist?) could also be set to despawn later. Something that comes up in my mind right away is a shulker box, as it could contain any number of enchanted items itself.

**Comment by exaskye** [comment]
I'd like to make this configurable, but my config loader is a mess. enchanted_item_long_despawn is a stopgap.

**Comment by exaskye** [comment]
Y'know, I could just use a separate INI file instead of lumping it into fabrication.ini.

Then it's not an issue.

![](https://blob.jortage.com/blobs/3/c42/3c42f229ff3fc9c8266090b5e805377ff76809ce262d73e7d6bb676af225d3f9405bde57a154f5f48726c5a8e6cf3d442f99860092113a891689851aae21b687)
