### ISSUE TITLE
gold_tools_useful_in_nether doesn't respect stone tools made from blackstone

### ISSUE THREAD

**Issue by saltyseadoggo** [FalsehoodMC/Fabrication#40]
The option gold_tools_useful_in_nether adds an nbt tag to wooden tools produced from crimson or warped planks to allow them to evade the 50x durability penalty, as they are made from a Nether substance. This is good! However, stone tools can be made from blackstone, and they do not recieve a similar tag. Adding a tag to the tools produced by these blackstone recipes that gives them this boon and renames them to 'Blackstone ___' would be appreciated.~

**Comment by exaskye** [comment]
Folding into #41
