### ISSUE TITLE
Random players on player manager list but not in-game

### ISSUE THREAD

**Issue by aisukuma** [FalsehoodMC/Fabrication#405]
On my console, it shows that there are 12 players on my server player list, yet they are not in-game. I am unable to view actual players in my console because of this. There are no server crashes, but I'll provide a latest.log. Tried looking to see if anyone had the same issue but no luck.

[The latest.log for the server](https://gist.github.com/aisukuma/a1a8413782f7fd1643f25d6920148cb4).

This is on a vanilla client looking at the server list:
![image](https://user-images.githubusercontent.com/22802219/151463190-e1775233-9901-42fb-a1c3-7311563128b5.png)

This is what shows on the player manager list:
![image](https://user-images.githubusercontent.com/22802219/151463320-38b3fc9b-d838-4389-aa82-5d602948e154.png)

**Comment by exaskye** [comment]
Disable `utility.ping_privacy`. This is a *feature*.

**Comment by aisukuma** [comment]
Thank you!
