### ISSUE TITLE
Flat/Billboard Items Looks

### ISSUE THREAD

**Issue by NPC-Master3304** [FalsehoodMC/Fabrication#407]
it's a pretty easy issue to fix, but the items don't always face the player. so if your above the item, it acts like the 3d items but as a 2d item without the rotation.
this mod accurately fixes this issue incase u need a src code reference or something: https://www.curseforge.com/minecraft/mc-mods/retro-items/

**Comment by exaskye** [comment]
![image](https://user-images.githubusercontent.com/6185037/153057126-f8ac849d-d424-478d-8c4d-fd8e630bd364.png)

**Comment by NPC-Master3304** [comment]
oh. nvm then lol
