### ISSUE TITLE
Forgery crashes with exit code 1 when "mobs_dont_drop_ingots=true" - doesn't happen when unset - other config settings unaffected

### ISSUE THREAD

**Issue by Boltzmania** [FalsehoodMC/Fabrication#412]
[Log]
https://pastebin.com/iBNn01LA

[Ini FIle]
https://pastebin.com/4rsg7Mw6

Forge version is 36.2.28 (also happens as far back as 21)

**Comment by exaskye** [comment]
Forgery v1.x is no longer supported. Update to v2.3.0.
