### ISSUE TITLE
Pick up skeleton arrows

### ISSUE THREAD

**Issue by Moonyol** [FalsehoodMC/Fabrication#413]
v2.3.0 fabric
if pick up skeleton arrows is on and you try to pick up a stray arrow it will look like this and be purple
![image](https://user-images.githubusercontent.com/92951072/155032332-def4bd4b-16fc-4055-bb16-883ab80940eb.png)

**Comment by SFort** [comment]
a stray is a skeleton and that is a stray arrow. would you like pickup skeleton arrows to exsclude strays? or would you like the arrow renamed? i'm not sure what you're asking for

**Comment by Moonyol** [comment]
renamed and the arrow make it not be purple
![image](https://user-images.githubusercontent.com/92951072/155128099-15c88d40-f458-4055-8121-bb82761995a3.png)
