### ISSUE TITLE
[Suggestion] shield_banner_fix

### ISSUE THREAD

**Issue by saltyseadoggo** [FalsehoodMC/Fabrication#42]
I would like to see a tweak to force banner patterns applied to shields to render at their full resolution, as seen on the banner block itself, instead of the weird half resolution used on vanilla shields, which makes most banner patterns look ugly.

[This resource pack](https://www.curseforge.com/minecraft/texture-packs/shieldcorrections) fixes this issue and adds other features as well. However, reading through previous reports, I understand that you would like Fabrication/Forgery to be a one stop shop for fixes and tweaks, and that you aren't afraid of fixing things that other mods fix to assert this.

**Comment by exaskye** [comment]
This is better to fix from a mod anyway; a resource pack has to explicitly support any custom banner patterns.

**Comment by saltyseadoggo** [comment]
I hadn't thought of that, but nyah! I didn't know how banner patterns and that resource pack work under the hood exactly.~

**Comment by exaskye** [comment]
![2021-01-07_22 23 41](https://user-images.githubusercontent.com/6185037/103981613-042c5f00-5137-11eb-95a2-884c1b2783bc.png)
![2021-01-07_22 23 45](https://user-images.githubusercontent.com/6185037/103981616-04c4f580-5137-11eb-9f60-d60047a9e8be.png)

It took reimplementing the entire banner renderer to get this working to my liking, but the result is good.

**Comment by exaskye** [comment]
If you are particularly itching to use this feature, it's available in [v1.2.10-pre1](https://github.com/unascribed/Fabrication/releases/tag/v1.2.10-pre1).
