### ISSUE TITLE
Rendering Issue with Essential mod

### ISSUE THREAD

**Issue by Rafii2198** [FalsehoodMC/Fabrication#428]
[Essential](https://essential.gg) is a useful, social oriented mod. One of it features is character customization which display your Minecraft character. When Fabrication is also present then that character is askew.

This is how it looks when only Essential is installed:
![obraz](https://user-images.githubusercontent.com/26695327/159172729-8aacb22d-348a-4917-810e-c398e1e0e7e6.png)

This is how it looks when both mods are installed:
![obraz](https://user-images.githubusercontent.com/26695327/159172635-4a42c2b1-9f17-49f1-89cf-39ac9796f282.png)

With Fabrication, it is also following the mouse which is not normal behavior. 
Latest Gist: https://gist.github.com/Rafii2198/c637ee8a52bee0a096ea58fb7cfe11d6

**Comment by SFort** [comment]
neither me or una wish to install a closed source mod with with microtransactions and a fairly sized ToS / Privacy Policy (something that's required to debug it)
fairly sure PRs are always welcome,
best of luck with the essential devs (assuming they fix conflicts)

**Comment by Rafii2198** [comment]
Understandable. My friend found what was the issue: He believed that they copied code from player inventory screen which means Omniscent Player forces it to rotate, disabling that module fixes the issue.
_(Btw is it Omniscent or Omniscient?)_
