### ISSUE TITLE
[Suggestion] legible_signs

### ISSUE THREAD

**Issue by saltyseadoggo** [FalsehoodMC/Fabrication#43]
I've found it frustrating on multiple occasions that dyeing sign text is usually impractical because the text colours are dark and difficult to read on most sign types. It's also frustrating that white text appears grey, pink appears almost purple...

I would like to suggest a legible_signs tweak that makes two changes to sign text:
- Increase the brightness of the sign text colours so they actually match their dyes. No more "white" text appearing as grey.
- Give coloured sign text a shadow like the menu button font has, to separate the text from the background and make the text easier to distinguish and read.

**Comment by exaskye** [comment]
This also bothers me; dunno why I didn't think of making a tweak to fix it..

**Comment by exaskye** [comment]
![2021-01-07_20 42 40](https://user-images.githubusercontent.com/6185037/103975477-14d5d880-5129-11eb-86f9-72f07201742e.png)
![2021-01-07_20 42 37](https://user-images.githubusercontent.com/6185037/103975480-156e6f00-5129-11eb-820c-ee45439f9351.png)

**Comment by exaskye** [comment]
For some incredibly Mojang-y reason, all sign colors are set to 40% brightness. No clue why.

Made everything use the "normal" dye colors, except gray, black, and brown.

**Comment by exaskye** [comment]
I'm not quite sure on the shadows thing; will decide closer to the release of 1.2.10.

**Comment by saltyseadoggo** [comment]
Honestly, these are looking much better and more legible already. I'd be fine with just this fix.~

**Comment by exaskye** [comment]
If you are particularly itching to use this feature, it's available in [v1.2.10-pre1](https://github.com/unascribed/Fabrication/releases/tag/v1.2.10-pre1).
