### ISSUE TITLE
Game instantly crashes upon launch

### ISSUE THREAD

**Issue by gazecube** [FalsehoodMC/Fabrication#430]
Log is attached below.
[launcher_log.txt](https://github.com/unascribed/Fabrication/files/8321151/launcher_log.txt)
The mod never did this sort of thing before. Maybe it's 1.18.2?

**Comment by exaskye** [comment]
Guess the 1.18.2 port doesn't work. How (un)surprising.

**Comment by SFort** [comment]
`No refMap loaded.`

**Comment by exaskye** [comment]
Oh, of course. I figured it was my fault.

I missed that because this log is so full of garbage from the launcher being used.

**Comment by exaskye** [comment]
v2.3.1-exp2 released. This time I actually made sure it launches

**Comment by exaskye** [comment]
v2.3.1-exp2 released. This time I actually made sure it launches
