### ISSUE TITLE
Incompatibility with Inspecio

### ISSUE THREAD

**Issue by sleepingdragoninn** [FalsehoodMC/Fabrication#431]
Latest.log - https://paste.ee/p/OIKr3

Occurs on startup, assumedly an incompatibility with tweaks that affect tooltips

With just Fabrication-1.18.2-exp2, Inspecio 1.3.0, FAPI

Also posted here https://github.com/Queerbric/Inspecio/issues/67

If it's possible to isolate the issue by banning features, this might also be useful.

**Comment by sleepingdragoninn** [comment]
Confirmed doesn't occur with all features banned, looking into it by category.

Edit: Narrowed to "Weird Tweaks"

Edit: Confirmed that "Use items while riding" causes the issue

**Comment by sleepingdragoninn** [comment]
Confirmed as not occurring when all features are banned, and occurring when all features are banned except "Use items while Riding" - incompatibility can be avoided this way, however the feature also prevents players from loading into worlds (with "invalid packet") without inspecio, so it might be a related issue with 1.18.2.

**Comment by exaskye** [comment]
exp3 has been released, which may fix this issue: https://github.com/unascribed/Fabrication/releases/download/v2.3.0/fabrication-1.18.2-2.3.1-exp3.jar

**Comment by sleepingdragoninn** [comment]
Confirmed working on exp3 
![image](https://user-images.githubusercontent.com/55819817/160265442-20083f28-00a3-4deb-a8a8-dad668fab853.png)
![image](https://user-images.githubusercontent.com/55819817/160265501-89aec573-a94f-40e7-b33c-100b99a53e0e.png)
(shown doubled up with charm's map preview, ignore that)
