### ISSUE TITLE
Allow features that failed to initialize to be banned

### ISSUE THREAD

**Issue by sleepingdragoninn** [FalsehoodMC/Fabrication#432]
Currently the switcher locks up completely (as features clearly can't be "enabled") when something fails to load, however it would be useful for e.g. configuring modpacks with unavoidable mod incompatibilities to be able to ban failing features from the UI.

**Comment by SFort** [comment]
I'd rather the options remain grayed out and just don't lock.
as failed to load is almost always something that will be fixed when reported.
