### ISSUE TITLE
[Suggestion] unused sound effects

### ISSUE THREAD

**Issue by RyanCR03** [FalsehoodMC/Fabrication#44]
four unused sound effects are currently still in the game; ghast affectionate scream, wolf howl, player breath, and silverfish step. my ideas on the usage of these four sounds would be for the affectionate scream to happen while a ghast is in the overworld, the howl would be made from wild wolfs at night, the silverfish is kinda obvious it would happen when a silverfish moves, and the player breath maybe when the player gets out of water after almost drowning.

**Comment by saltyseadoggo** [comment]
*Campanion* (https://github.com/TerraformersMC/Campanion) implements howling wolves, so I would like to request care be made to prevent conflict between this mod's implementation and theirs.~

**Comment by exaskye** [comment]
Ghast scream: Sure
Wolf howl: I can implement this, and make it disable itself if Campanion is present
Player breath: This is a... weird sound, definitely not fitting for escaping drowning. It's not panicked.
Silverfish step: Sure

**Comment by exaskye** [comment]
Part of the reason the wolf howl is unimplemented is probably just because this sound is *not very good*. Campanion uses custom sounds and an AI goal for its impl.

**Comment by exaskye** [comment]
The silverfish step sound *does* play, it's just very quiet, as it probably should be.

**Comment by exaskye** [comment]
Yeah, I keep listening to the unused wolf howl sound and it's just... not good.

Closing this as I've implemented the Ghast one and don't think I'll implement any of the others for previously explained reasons.

**Comment by exaskye** [comment]
If you are particularly itching to use this feature, it's available in [v1.2.10-pre1](https://github.com/unascribed/Fabrication/releases/tag/v1.2.10-pre1).

**Comment by RyanCR03** [comment]
the silverfish step doesnt play. the sound effect has the subtitle that says "footsteps" but you don't see it with silverfish...

**Comment by exaskye** [comment]
I say it already plays because I was inspecting the code for the silverfish class to find the best place to patch, but saw it already has code to play the sound. It's only 15% volume, though.

**Comment by RyanCR03** [comment]
you cant hear it in game... i had my headphones at max volume and heard nothing but the ambient sound? maybe some coding oversight which makes the sound unused?

**Comment by exaskye** [comment]
Silverfish apparently override a method Yarn maps as `canClimb` to return `false`; a better name for this method, considering the *only place it is used*, is `hasStepSound`. So, yes, you're right. While testing this the other day it was (and it is again today) loud in my house and it was very hard to tell if the sound wasn't playing or if I just couldn't hear it.

**Comment by exaskye** [comment]
Oh my god I hate this step sound so much. It's fixed though.

**Comment by exaskye** [comment]
If the method weren't mismapped in Yarn I would've realized this issue immediately. Sorry for dismissing it and not doing enough research.

**Comment by RyanCR03** [comment]
thank you i know its creepy but I'm pretty sure that was intended for the silverfish but they were just annoying thanks for adding this level of immersion to fabrication!

**Comment by exaskye** [comment]
Available in [v1.2.10-pre2](https://github.com/unascribed/Fabrication/releases/tag/v1.2.10-pre2).
