### ISSUE TITLE
3.0 todos

### ISSUE THREAD

**Issue by exaskye** [FalsehoodMC/Fabrication#448]
- [ ] ~~Polish new UI added to config screen~~
  - [ ] ~~New transition animation for going to a subscreen similar to Android Lollipop app launch animation~~
- [ ] Add missing subconfig screens / improve existing
  - [x] block_logo
  - [x] classic_block_drops
  - [ ] dimensional_tools
  - [x] fscript (needs to inform when errors)
  - [ ] gear_components
  - [ ] item_despawn
  - [x] taggable_players
  - [x] yeet_recipes
- ~~Go through all features enabled in the Vienna profile and move some to Extra~~ Superseded
- ~~Ensure features have correct defaults~~ Superseded
- [x] Replace profile system with a per-category on switch
- [ ] ~~Stress test the new Hijack features in a large modpack~~
- [x] Change our base branch to 1.18
- ~~1.18.2/1.18.1 Agnos for tags (the merged PR that shoves us over to post-1.18.2-only is a stopgap)~~
- [x] test world settings when new features are added
- [x] Now that we have weird build-time remap stuff, FabRefl should get modified to use it
- [x] Currently FabRefMap is failing for block_logo / swap_conflicing_enchats
- [x] OH GOD FORGERY
  - ~~Rework to a forge-loom-based subproject? Maybe?????~~
  - [x] ~~Nope just remove a bunch of features on Forge~~
- [x] [muffled screaming]

Removed a bunch of stuff. Just want to get this released and out of my hair.

**Comment by SFort** [comment]
at some point i was tempted to try a 1.12 liteloader port, might still although i'm fairly sure i'd be a one off (also what would even it be called?)
(edit: [libel](https://github.com/sfort/MC-Libel))

**Comment by exaskye** [comment]
> what would even it be called?

Libel

Li from Lite, kinda a similar word meaning zone to Fabrication and Forgery

~~Also it's a bad idea~~

**Comment by SFort** [comment]
with a cool name like that now i have to do it

**Comment by exaskye** [comment]
If you do, you should probably use MixinBootstrap rather than LiteLoader, so you can run on the server side and for less painful integration with Forge

**Comment by SFort** [comment]
~as for forge, would it be a esier / even possible to just use the actuall obfuscated stuff~

**Comment by SFort** [comment]
> Are we gonna continue maintaining 1.16

if regular 1.16 backports end that's fine, i'd do irregular ones (whenever there isn't a massive todo list around like this one)

**Comment by SFort** [comment]
> profile system sucks

maybe enable by category?

**Comment by exaskye** [comment]
> maybe enable by category?

Accomplishes basically the same thing and makes a lot more sense. I dunno why I didn't think of this.

**Comment by StereoMadnessss** [comment]
I am guessing that 3.0 is for 1.19 since it's coming out in two days

**Comment by SFort** [comment]
> I am guessing that 3.0 is for 1.19 since it's coming out in two days

3.0 was for 1.17 (and is) it's um just got dellayed ... a little
(i don't wanna do the remaining todos as the UIs i made/make are pretty trash and una is probably busy/doesn't wanna)
