### ISSUE TITLE
Forgery + OptiFine freezes the game for a while on launch

### ISSUE THREAD

**Issue by Pannoniae** [FalsehoodMC/Fabrication#46]
The game freezes for a fairly long period of time after "mod loading complete" with both mods. It also throws it back to the loading screen for more atlas stitching after reaching the main menu.

**Comment by exaskye** [comment]
Please run the game with the JVM argument `-Dfabrication.debug=true` and send the full log.

**Comment by Pannoniae** [comment]
https://hastebin.com/itepavetab.sql

**Comment by exaskye** [comment]
Does this still occur if you disable tnt_is_dynamite and oak_is_apple?

**Comment by Pannoniae** [comment]
I'll try.

**Comment by Pannoniae** [comment]
It's still frozen after mod loading complete, but for a shorter time. The double-loading is gone.

**Comment by exaskye** [comment]
The game isn't crashing and OptiFine is a closed-source hunk of garbage so I'm just going to call this fine.
