### ISSUE TITLE
Spawn egg cracking

### ISSUE THREAD

**Issue by RyanCR03** [FalsehoodMC/Fabrication#47]
if spawn eggs make mobs come from them how come the eggs don't crack?

**Comment by exaskye** [comment]
As in, particle effects when the mob is spawned?

**Comment by RyanCR03** [comment]
yes

**Comment by exaskye** [comment]
The item crack particles don't honor sprite recoloration, like the spawn eggs use...

**Comment by exaskye** [comment]
Available in [v1.2.10-pre2](https://github.com/unascribed/Fabrication/releases/tag/v1.2.10-pre2) along with a fix for item crack particles not honoring sprite recolor.
