### ISSUE TITLE
When Crawl, Sneak Should  can not be used.

### ISSUE THREAD

**Issue by ardissaps** [FalsehoodMC/Fabrication#473]
Currently, when we crawl and press sneak, it have weird stance (like combined). If Crawl triggered, sneak should disabled (instead of combined). They should work indepently.

**Comment by SFort** [comment]
fabrication crawl behaves exactly the same as vanilla.

sneaking and crawling just prevents you from going off ledges, i don't see how this is a problem

**Comment by ardissaps** [comment]
> fabrication crawl behaves exactly the same as vanilla.
> 
> sneaking and crawling just prevents you from going off ledges, i don't see how this is a problem

The problem is if we toggle Crawl, try press sneak(the non toggle version) when crawl aktife. It is like Crawl+Sneak which make the animation look weird, face on the floor.
