### ISSUE TITLE
Fabrication Crashes on Boot with OptiFine

### ISSUE THREAD

**Issue by satwik9aari** [FalsehoodMC/Fabrication#48]
The game crashes on boot when OptiFine is used with Fabrication.

Versions used are: MineCraft 1.16.4, Fabric 10.8, FabricAPI 0.29.3, OptiFine G6 pre10, OptiFabric 1.8.16, Fabrication 1.2.9.

Crash Report: [crash.txt](https://github.com/unascribed/Fabrication/files/5791698/crash.txt)
Log from GDLauncher: [log_gdl.log](https://github.com/unascribed/Fabrication/files/5791699/log_gdl.log)
Log from MineCraft: [log_mc.log](https://github.com/unascribed/Fabrication/files/5791700/log_mc.log)

**Comment by exaskye** [comment]
Workaround: Disable `mechanics.obsidian_tears`.
