### ISSUE TITLE
[Crawl] Body Touch Ground (or at least lower it more than current) & Tilt Face Up (little bit) + Toggle Crawl independet from 3 position

### ISSUE THREAD

**Issue by ardissaps** [FalsehoodMC/Fabrication#480]
Thank you for the last fixes! :)

Would you please make body touch ground (or at least lower it more than currently flying/hovering land) & and tilt the face up more (only little bit). ~~Also would be great if can instantly crawl from standing without needing to crouch first. Pardon didnt realize it is already there~~ Toggle Crawl (example Z) going from standing up to crawl instant switch vice versa (not hold).

**Comment by exaskye** [comment]
The crawling feature only enables using vanilla's swimming while on dry land on request instead of needing a trapdoor. Changing the rendering is out of scope for Fabrication.

**Comment by ardissaps** [comment]
> The crawling feature only enables using vanilla's swimming while on dry land on request instead of needing a trapdoor. Changing the rendering is out of scope for Fabrication.

I see, it is ok then. Also I just figured out that if we crawl from standing up, the hand spinning like a drill.
