### ISSUE TITLE
Mixed Slab Mods Partial Breaking Support

### ISSUE THREAD

**Issue by ardissaps** [FalsehoodMC/Fabrication#482]
Hello again, I hope you are not get boring of my post! :)

Fabrication feature that can destroy half slab is very good and functional. However, it does not work on mixed slab mod that have feature of mixing different slab (included modded slab) into 1 block.

When I click half of the slab, it destroyed whole block instead of half part of it.
![image](https://user-images.githubusercontent.com/82106625/174322129-86298d19-37ea-494f-9af8-932655222144.png) 
![image](https://user-images.githubusercontent.com/82106625/174322647-c94d860b-d600-4001-8ea7-ef5ffc5b81a2.png)

Would you like to support breaking half slab for mixed slab? (https://www.curseforge.com/minecraft/mc-mods/rectified-slabs)

Thank you very much!

**Comment by exaskye** [comment]
Rectified Slabs majorly changes how slabs are implemented, and in general Fabrication is designed to tweak vanilla features, so I don't believe explicit compatibility here is in scope (and may be undesirable if there are future changes to Rectified Slabs)

I would suggest instead making a feature request to Rectified Slabs to add KleeSlabs "break one at a time" behavior.

**Comment by ardissaps** [comment]
@unascribed hello the partial block slab now works fine with Fabrication Gradual Block Breaking in combination with
- Vanilla Parts (https://www.curseforge.com/minecraft/mc-mods/vanilla-parts) with 
- Multipart lib included (https://www.curseforge.com/minecraft/mc-mods/lib-multipart)

Can break same slab and mixed slab including slab from other mods, no need Kleeslab.
Thank you for the great mods of Fabrication!

**Comment by exaskye** [comment]
In that case it's because LibMultipart implements individual part breakage itself; nothing to do with Fabrication. Glad you found a solution.

**Comment by ardissaps** [comment]
> In that case it's because LibMultipart implements individual part breakage itself; nothing to do with Fabrication. Glad you found a solution.

If I disable Fabrication function, libmultipart only destroy half if it mixed slab, if it is same slab it destroy both. Still need function from Fabrication.

**Comment by exaskye** [comment]
Really? Huh.

**Comment by SFort** [comment]
gradual block breaking works on anything with `SlabBlock.TYPE` or `SnowBlock.LAYERS`
it is very easy to extend, it works by:
setting the state to the part you're breaking
letting minecraft run it's normal drop code
setting the state to the part/s you waren't breaking

i'm guessing (without looking at the code)
they have a custom property that defines the rotation of the block, but still keeping `SlabBlock.TYPE` for the relative block shape

**Comment by ardissaps** [comment]
> Really? Huh.

Yeah, maybe because multipart change the block to their stuff when combined (name also changed to "Lib Container"). As for vanilla (slab) combined to full block as normal vanilla fullblock. (probably) :D
Also I removed Rectified Slab mentioned earlier as it incompatible with Create Fabric and some mods.
