### ISSUE TITLE
Old Lava textures enabled all the time, despite it being disabled in config

### ISSUE THREAD

**Issue by BugmanBugman** [FalsehoodMC/Fabrication#49]
On default settings, light mode where the old lava option is disabled, it still keeps applying in my game.
With fabrication on default settings
![2021-01-10_14 55 26](https://user-images.githubusercontent.com/40730042/104136904-bb56ef00-535e-11eb-9fce-34ec8bb646b5.png)
Without fabrication
![2021-01-10_15 56 28](https://user-images.githubusercontent.com/40730042/104136906-bbef8580-535e-11eb-8d60-b71e536023b0.png)

**Comment by exaskye** [comment]
Cannot reproduce. Please run your game with the JVM argument `-Dfabrication.debug=true` and send your log.

**Comment by exaskye** [comment]
Cause found by accident while fixing #50
