### ISSUE TITLE
Multiconnect breaks version checking, making you unable to edit server config through modmenu

### ISSUE THREAD

**Issue by JumperREDACTED** [FalsehoodMC/Fabrication#491]
![image](https://user-images.githubusercontent.com/83337894/174792324-01114f3f-48cf-443f-ae80-3f60814cbf6d.png)

client log
https://mclo.gs/cj8djXV
server log
https://mclo.gs/JRr65lz

Multiconnect: https://github.com/Earthcomputer/multiconnect/issues/385

**Comment by exaskye** [comment]
Multiconnect is breaking basic vanilla functionality. Won't fix.
