### ISSUE TITLE
Alternate Current breaks Colorful Redstone

### ISSUE THREAD

**Issue by ardissaps** [FalsehoodMC/Fabrication#494]
![image](https://user-images.githubusercontent.com/82106625/174965486-34ee67dc-40ee-482b-835c-ce83e77e4bfd.png)

**Comment by SFort** [comment]
![screenshot](https://user-images.githubusercontent.com/1879846/175050070-755cc898-f611-4b0c-b7dd-cef7491a8b53.png)

tested on 1.18 in dev env so i'm guessing this is a mod conflict

**Comment by SFort** [comment]
To be clear, we cannot fix a conflict if we have no idea what the cause is.
please find out what mods are causing the conflict, and report back

**Comment by ardissaps** [comment]
My mod list :
![image](https://user-images.githubusercontent.com/82106625/175760892-3f12a361-8e07-43d6-be8a-9c37cd0c59fe.png)

**Comment by SFort** [comment]
i'm not downloading ~250 mods.
you'll need to figure out what's actually causing this.
if you need an explanation on how to do that, you can reach me on [unas matrix stuff](https://matrix.sleeping.town/)

**Comment by YumatanGames** [comment]
Wow, that's a lot of mods my dude! I would start by disabling every mod that could even remotely mess with redstone logic, that includes alternate current and wired redstone. By looking at your modlist There's a good possibility that Alternate current might be the culprit, so I would start with it if I were you.

**Comment by SFort** [comment]
add `-Dmixin.debug.export=true` to the java args, re-launch minecraft load a save and send over `.minecraft/.mixin.out/class/net/minecraft/class_2457`

**Comment by ardissaps** [comment]
@SFort I can confirm it is caused by [AlternateCurrent](https://modrinth.com/mod/alternate-current). I disabled that mod and colorful redstone working as intended.
![image](https://user-images.githubusercontent.com/82106625/177033559-ff2e6fec-0426-4818-ad65-91b6bab9446c.png)

> There's a good possibility that Alternate current might be the culprit, so I would start with it if I were you.

Yeah it actually the cause, does the mod actually improving redstone as it claimed?

**Comment by exaskye** [comment]
AC does improve redstone performance by quite a bit, but inherently it ends up bypassing the code that Fabrication patches. Supporting AC in Colorful Redstone would defeat a lot of the purpose of using AC in the first place, as checking for wool under redstone is pretty expensive.

**Comment by ardissaps** [comment]
> AC does improve redstone performance by quite a bit, but inherently it ends up bypassing the code that Fabrication patches. Supporting AC in Colorful Redstone would defeat a lot of the purpose of using AC in the first place, as checking for wool under redstone is pretty expensive.

I see, thank you for the answer! Ok I decide disabling colorful redstone wool and install [ChromaticCurrent](https://modrinth.com/mod/chromatic-currents) and [Wired Redstone](https://modrinth.com/mod/wiredredstone) to separate dust line. And keep using AC for regular redstone build, and use Fabrication for other awesome tweaks! It works with 400 mods++ currently used with carefully chosen configuration. :D
