### ISSUE TITLE
[REQUEST] Would You like to add KEYBIND to instantly open Fabrication Settings menu?

### ISSUE THREAD

**Issue by ardissaps** [FalsehoodMC/Fabrication#499]
Instead of opening ModMenu first. Nice idea cool isn't?
THANK YOU! :)

**Comment by exaskye** [comment]
If you want a quick shortcut, you can use the /fabrication command. I believe SFort added a subcommand to open the config GUI semi-recently.

I dislike adding keybinds for ultimately no reason; Mod Menu is the officially designated place for things like this, and Fabrication is no longer accepting feature requests.

**Comment by ardissaps** [comment]
I tried "/fabrication config" produce error message.

**Comment by SFort** [comment]
`/fabrication:client ui` iirc

**Comment by ardissaps** [comment]
> /fabrication:client ui

Thanks, now I can use [Command GUI](https://modrinth.com/mod/command-gui-buttons) to quickly open Fabrication Menu!
![image](https://user-images.githubusercontent.com/82106625/177042373-2a51a461-d364-4ae4-9c11-a55f1b29d985.png)
