### ISSUE TITLE
Sign mixin crash with Upgrade Aquatic

### ISSUE THREAD

**Issue by BugmanBugman** [FalsehoodMC/Fabrication#50]
[debug.log](https://github.com/unascribed/Fabrication/files/5793408/debug.log)

**Comment by unascribed** [comment]
Cannot reproduce.

**Comment by exaskye** [comment]
Conflict with Upgrade Aquatic.

**Comment by exaskye** [comment]
The mixin responsible on the Upgrade Aquatic side was the one that makes Glowing Ink work on signs; and that looks really good in combination with Fabrication's Legible Signs.

Fix released with v1.2.10_01, by the way. Available on Curse and on GitHub.
