### ISSUE TITLE
Incompatible with Paradox Slabs

### ISSUE THREAD

**Issue by ZekerZhayard** [FalsehoodMC/Fabrication#500]
Paradox Slabs: https://modrinth.com/mod/paradox-slabs
log: https://gist.github.com/ZekerZhayard/5ca468e4f71405d64662c3bb36984316 (the exported class is attached to the gist)

https://github.com/auoeke/paradox-slabs/blob/4e24671ef0dcb6206449c43240dfe46f777d5a1e/source/paradoxslabs/mixin/ServerPlayerInteractionManagerMixin.java#L60

**Comment by SFort** [comment]
This has to be the best bug report i've ever seen, it has everything you could want in it, thanks!
