### ISSUE TITLE
[Question] Villager Trade Limit

### ISSUE THREAD

**Issue by ardissaps** [FalsehoodMC/Fabrication#504]
If I turn on Village trade reset, and their maximum level Master reached and all trade finish, do they become permanently cannot trade anymore? thx

**Comment by Cynosphere** [comment]
Trade resets doesn't affect the villager's level. Everytime they restock (which is usually every in game day) they will have their trades changed.

**Comment by ardissaps** [comment]
In vanilla, do trader never change the trades forever?

**Comment by Cynosphere** [comment]
Correct. Restocking only unblocks blocked trades in vanilla.

**Comment by ardissaps** [comment]
Is it possible to make reset trade without limiting 1 trade per level?

**Comment by SFort** [comment]
increasing the amount of simultanious trades lowers rarity too much,
as you have lots of trades and they all reshuffle every 5minutes at least (assuming the villiger is working).
there is no option to increase the trade count and i'll not be adding one

**Comment by ardissaps** [comment]
No problem. Still worth to enable the option as we sometimes want to stay in 1 village and get bored with same item sold by trader but dont want to travel whole map just to find another trader.  Thank you very much!
