### ISSUE TITLE
Fabrication crashes game when using OptiFabric

### ISSUE THREAD

**Issue by Zepicre** [FalsehoodMC/Fabrication#505]
https://gist.github.com/Zepicre/104c97d18aa9b7134f715f4f3714c2e8

**Comment by Yu-Vitaqua-fer-Chronos** [comment]
Not a dev or anything but it is highly recommended to use anything other than Optifine with Fabric... Good alternatives are Lithium, Sodium and Phosphor (other optimisation mods can be found here: <https://lambdaurora.dev/optifine_alternatives/>)

**Comment by exaskye** [comment]
Don't use OptiFine.
