### ISSUE TITLE
Option to disable hand swaying

### ISSUE THREAD

**Issue by Qonsyuma** [FalsehoodMC/Fabrication#51]
When the camera is moved (doesn't matter if walking or not), the arm sways a bit delayed until it's at its normal place (while the camera is still). This is not to be confused with View Bobbing, which is the hand swaying from left to right while walking.
This hand swaying on camera movement was introducted after Beta 1.7.3, an option to remove it would provide extra nostalgia.

**Comment by Qonsyuma** [comment]
Is there a way to add your tags yourself? I couldn't find any option, sorry if I'm missing something obvious

**Comment by exaskye** [comment]
Nope, only collaborators can add labels.

I should set up GitHub's multiple issue templates thing, those can include predefined labels.

**Comment by Qonsyuma** [comment]
Ah I see, I was wondering why there was no selection for templates. Thank you!

**Comment by exaskye** [comment]
I've received an overwhelming number of feature requests over the week and they are filling up the issue tracker and making it difficult to keep track of what is even going on. I've enabled [Discussions](https://github.com/unascribed/Fabrication/discussions) on the repo as a new location for feature requests. Unfortunately, GitHub has "temporarily" disabled the ability to convert issues to discussions, so I'm closing all feature request issues. However, I'm tracking all the closed issues in a Project board; despite being closed, they're still on my radar on the board. **All new feature requests *must* go to Discussions. Feature requests opened as issues going forward will be closed.**
