### ISSUE TITLE
Void fog spawns at wrong -Y coordinate below bedrock

### ISSUE THREAD

**Issue by Thspooks** [FalsehoodMC/Fabrication#511]
![image](https://user-images.githubusercontent.com/54241208/179750358-ba88b26d-dfda-4e50-889f-68406c527cb5.png)
The only mods are Fabric api and Fabrication.

Create world and for comprasion i located ancient city
The fog spawns below Bedrock as on picture included.

Version:
fabrication-3.0-pre6+1.19.jar

**Comment by Thspooks** [comment]
![image](https://user-images.githubusercontent.com/54241208/179750823-37759c6a-c56d-4bd0-a35e-f1d4c353332d.png)
forgot to include this picture. The fog ends on bedrock, it wont go up

**Comment by SFort** [comment]
# 1.19

![](https://user-images.githubusercontent.com/1879846/179781089-5c3af69f-63bf-499d-a87d-37ef92f12244.png)

# 1.4

![](https://user-images.githubusercontent.com/1879846/179782093-ca6b7df8-4f19-4b2e-912a-3f01e1213ad8.png)
![](https://user-images.githubusercontent.com/1879846/179782225-87e81802-a7e9-47c1-b86c-cc51e8647480.png)

**Comment by SFort** [comment]
as far as i can tell void fog particles are identical to how they ware before removal
(minor diffrences including it not bugging out at high coords anymore)

it might feeel diffrent because i didn't get around to adding the actuall fog closing in?

**Comment by Thspooks** [comment]
Yeah , and honestly i thinkit feels different  since mc has now different depths, so i were expecting to see a bit of fog in the ancient city

**Comment by exaskye** [comment]
Void fog is out of scope for the void particles feature. Closing as a feature request, as it seems the particles are in fact accurate; they just seem different without the fog. (Though this may get added later anyway)
