### ISSUE TITLE
[Mod Incompability] WOINA Blinking Item Drops causes some items in EMI to not render.

### ISSUE THREAD

**Issue by f-raZ0R** [FalsehoodMC/Fabrication#518]
LOG: https://gist.github.com/f-raZ0R/35c89a2e8aa41a940ada334c9e6fb043

Turning on Blinking Item Drops in WOINA, causes some items in the EMI display to not render. Turning the option back off causes them to render properly again.

![2022-07-31_10 57 10](https://user-images.githubusercontent.com/30442287/182032315-cc8c97c4-1bd3-477a-9387-8b14292dcd20.png)
.

**Comment by exaskye** [comment]
I *wrote* the EMI render batcher and have no idea why this happens.

**Comment by forkiesassds** [comment]
Can also happen even with vanilla interfaces. Keep in mind, I don't even have EMI installed in this instance.
![image](https://user-images.githubusercontent.com/54495659/193448940-714dcebd-fc6b-46aa-a9f1-06ee90d9c4ed.png)
