### ISSUE TITLE
Incompatibility | OptiFabric + Fabrication

### ISSUE THREAD

**Issue by SylisMC** [FalsehoodMC/Fabrication#52]
**Description**
Bootup crash
Other Mods Issue post [[Here]](https://github.com/Chocohead/OptiFabric/issues/148)

**Temp Fix**
set `obsidian_tears=false` in main\config\fabrication\features.ini

**Versions**
- **fabrication-1.2.10_01.jar**
- **Optifabric-1.8.16.jar**
- OptiFine_1.16.4_HD_U_G5

**Log**
[Crash - OptiFabric + Fabrication.txt](https://github.com/unascribed/Fabrication/files/5798958/Crash.-.OptiFabric.%2B.Fabrication.txt)

**Comment by exaskye** [comment]
I thought I fixed this. :/

Workaround: Disable Mechanics > Obsidian Tears.
