### ISSUE TITLE
Block Logo models randomize each frame

### ISSUE THREAD

**Issue by dopadream** [FalsehoodMC/Fabrication#527]
my bals

**Comment by exaskye** [comment]
Reported on Discord, gave permission to make a minimal issue.

![](https://cdn.discordapp.com/attachments/1006416232318255154/1007201488898101298/javaw_EziE3GRbKz.gif)

**Comment by dopadream** [comment]
oh also do you think you can make it so you can change the block it uses in config🙂

**Comment by exaskye** [comment]
You can already, check config/fabrication/block_logo.ini

https://github.com/unascribed/Fabrication/blob/3.0/1.18/src/main/resources/default_block_logo_config.ini

**Comment by SFort** [comment]
also it's fairy jank and the main menu wont update till it's reloaded in some way.
but the in game config menu is at least usefull for viewing diffrent blocks

https://user-images.githubusercontent.com/1879846/184097202-dd304463-7852-4ae7-a1f0-22b8ec04854b.mp4

**Comment by SFort** [comment]
can't reproduce on 3.0/1.19 in dev, is this on 1.19.1/2 ?

**Comment by dopadream** [comment]
2

**Comment by SFort** [comment]
can't reproduce on 1.19.2  
guessing it's a mod conflict?

**Comment by dopadream** [comment]
sodium maybe idk
it only happens with the stone block

**Comment by dopadream** [comment]
Found out that this issue does not occur on the next unreleased build of sodium, so I'm considering this issue irrelevant and closing it
