### ISSUE TITLE
End Portal Parallax changes with Y

### ISSUE THREAD

**Issue by DarianLStephens** [FalsehoodMC/Fabrication#530]
While the feature states that it might not be entirely accurate, this is a thing that I believe is just a rendering/shader error and can be corrected.
When moving up and down, or crouching or flying or anything, the starfield appears to shift and morph, which is very much distracting.

It looks as though the starfield is plastered on the surface of the block, only minimally changing its perspective based on your height, rather than appearing as an actual drop in to the void.

Aside from that, and what seems like a tendency towards a deeper blue versus original blueish green, it's very nice to see this back in any capacity. It was one of the small things they changed which had a big impact on the look and feel of the game, and it's unfortunate that it appears a bug prompted them to give up on the old render and change to this cutout.

Log: There is no crash, and no direct error, so I don't know what to do about that.

**Comment by DarianLStephens** [comment]
Looking at it closer, it seems that the layers of the starfield are being distorted towards -X -Z the closer to the surface of the block the camera gets.
It seems like the layers also get closer together, instead of maintaining their depth?

I don't know if that helps debugging it, but I'm trying!

**Comment by DarianLStephens** [comment]
There's also a lot of jitter in the effect the closer you get to it, most visible by Spectator-ing right up to the surface of the portal and moving/looking around.
That seems like it might just be floating point inaccuracies in the shader, though, related to the weird edge spikes on the stars when you get _really_ close.

**Comment by exaskye** [comment]
I tried specifically to *not* do this, and suspect it's related to #529. Does this still happen in 3.0.1? That's before that was merged.

**Comment by SFort** [comment]
it's not related to 529

**Comment by DarianLStephens** [comment]
Here's a video demonstrating the problem:
https://www.youtube.com/watch?v=cXDY-G6nh9Y

That's taken on 3.0.1, so it doesn't seem like it was related to #529.

**Comment by exaskye** [comment]
#531 should fix this.

**Comment by SFort** [comment]
Fixed by #531
