### ISSUE TITLE
Possible to make Mending prevent repairs from increasing Prior Work Penalty?

### ISSUE THREAD

**Issue by DarianLStephens** [FalsehoodMC/Fabrication#533]
Rather than the all-or-nothing options (Disable Mending and/or the Prior Work Penalty), it could be interesting if the Mending enchantment prevented the work penalty from increasing due to repairs, allowing infinite anvil repairs while keeping the cost increase from applying books.
Or even if the Prior Work Penalty option could apply only to repairs, or if there was a new option which stopped repairs specifically from increasing the penalty.

I know you're not taking feature requests anymore, but this seemed quite along the lines of some features already in here, and it could be argued that these are just additional options to the already-existing suite of relevant tweaks?

**Comment by SFort** [comment]
i'm willing to try add fscript support to disable_prior_work_penalty allowing you to disable prior work penalty only for items with mending / whatever item you'd like to specify via script. if i do i'll also provide the script that would do that.

i don't think it's a good idea to add too many feature varients unless fabrications config user interfaces get reworked to display the extend tag in a more user friendly way that doesn't pile onto the feature count.

**Comment by SFort** [comment]
added by #534


https://user-images.githubusercontent.com/1879846/185719330-87ee2b9e-1afd-42ce-a00d-18811b92e311.mp4

this is just disable_prior_work_penalty applied only to items enchanted with mending.

sorry if it's not quite what you ware looking for, but i don't want to spend time figuring out a good injection point for repair only anvil cost right now

**Comment by DarianLStephens** [comment]
I was just thinking about this again.
Would it be at all feasible to make it so that Mending, when applied, resets the Prior Work Penalty of a tool and removes itself?

**Comment by SFort** [comment]
that would be a feature requset and in general we're not adding them atm
