### ISSUE TITLE
Grindstone Disenchanting no Experience cost?

### ISSUE THREAD

**Issue by MSandro** [FalsehoodMC/Fabrication#538]
There is no XP cost if I have Grindstone Disenchanting enabled.
Is it possible to set XP Cost in the Config? I can not find it!

**Comment by SFort** [comment]
grindstone disenchanting has no config to add xp cost.
iirc the mechanics downside is that it forces all the enchants to be transfered at once.
adding a xp cost would be a new feature and atm we're are not adding feature requests.
