### ISSUE TITLE
Forgery is incompatible with Rubidium and causes a crash

### ISSUE THREAD

**Issue by coderepo8593** [FalsehoodMC/Fabrication#539]
It crashes either as soon as it joins the world before being able to see the world render or shortly after the world has rendered. When I see water, it does not render at and causes an odd occlusion effect.

I troubleshooted this by looking at the render mixins of the call and removed each one until the bug + crash stopped. I then tested to see if I added all the other mods with render mixins back except for Forgery if it would have problems or work, and it worked just fine.

Example of what I am seeing.
https://user-images.githubusercontent.com/100347283/186530358-15ba2f98-90b5-4d5f-9288-da431dff1ff0.png

https://gist.github.com/coderepo8593/3856f7db762132977d936f538bf8a647

Related;
See this issue https://github.com/Asek3/Rubidium/issues/262 and this issue https://github.com/Asek3/Rubidium/issues/250 on Rubidium issue tracker.

**Comment by DoodlyDrawn** [comment]
https://github.com/Asek3/Rubidium/issues/250
[crash-2022-08-31_00.10.53-client.txt](https://github.com/unascribed/Fabrication/files/9456757/crash-2022-08-31_00.10.53-client.txt)


i'm adding this to your issue in forgery for the sake of easy access,
as i've written in my own issue, it seems that rubidium, when installed with both betterend 2.5 and forgery 1.4.0_01 causes the issue
![2022-08-31_00 19 10](https://user-images.githubusercontent.com/100347283/187546600-3917f3d5-3a4e-4214-bb72-fd3a280e0ab5.png)

**Comment by SFort** [comment]
this is a conflict between rubidium and betterend.
it has nothing todo with forgery (at least not on 3.0/1.16 didn't test older)
