### ISSUE TITLE
Swap conflicting enchants not working as expected for multi protection armor

### ISSUE THREAD

**Issue by Nezgal** [FalsehoodMC/Fabrication#545]
When enchanting an armor with more than 2 different types of protection, swapping between them instead swaps between 2 states : one with only one protection (the last one applied I think), and the other with ALL the other protections at once.

I don't know if swapping between protections was the intended goal of this mod or if it was initially thought for weapons and tools enchantments. Even if fixed, how would it work for boots with the 4 protections enchants + frost walker and depth strider ? Is there a deterministic order ? Swapping at random between the 8 possible states seems kinda tedious.

[latest.log](https://github.com/unascribed/Fabrication/files/9607401/latest.log)

**Comment by SFort** [comment]
it swaps at random, because i couldn't think of a good way to balance it for smite/bane of arthropods/sharpness so the random swaping was half peeled bandage of a solution
