### ISSUE TITLE
Forgery 3.0.3 and Optifine HD_U_H8/H9 crash on world load

### ISSUE THREAD

**Issue by Punkin-GH** [FalsehoodMC/Fabrication#557]
**Description**

When loading Forgery 3.0.3 and Optifine HD_U_H8 or Optifine HD_U_H9 on Minecraft 1.18.2, the game will crash upon trying to load a world.

**To reproduce**
1. Start Minecraft 1.18.2 (Forge 40.1.79)
2. Load any new or existing world

**Crash report and debug log**

[crash-2022-10-18_19.15.30-client.txt](https://github.com/unascribed/Fabrication/files/9815785/crash-2022-10-18_19.15.30-client.txt)

[debug.log](https://github.com/unascribed/Fabrication/files/9815786/debug.log)

**Comment by LemmaEOF** [comment]
Sadly, this isn't fixable on Fabrication or Forgery's end - OptiFine is closed-source, meaning that we can't actually see what it's doing or adapt for its behavior. I can't see where Forgery's code is touching this stuff either, so we're kinda out of luck on being able to fix it.

**Comment by SFort** [comment]
start setting features to banned figure out what feature causes is and then just don't use said feature. (can also use limit_runtime_configs)

**Comment by Punkin-GH** [comment]
looks like banning all the features stopped the crash! stand by while i figure out which one is causing problems.

**Comment by Punkin-GH** [comment]
Interestingly enough, the culprit was the old procedural lava texture, under W.O.I.N.A! If you ban that feature, everything else is fine 👍

**Comment by LemmaEOF** [comment]
Makes sense - that does Fancy Rendering Stuff that OptiFine doesn't know how to handle.

**Comment by Punkin-GH** [comment]
Just glad I could figure that out so if anyone else has that problem, they now have the solution ^^

**Comment by Punkin-GH** [comment]
And if anyone _really needs_ to replace their molten cheese with pasta sauce, [Vanilla Tweaks](https://vanillatweaks.net/picker/resource-packs/) has an option for the retro lava texture that can be used in place of the Forgery feature.
