### ISSUE TITLE
[From Curse] tweaks.custom_attacker_animations

### ISSUE THREAD

**Issue by exaskye** [FalsehoodMC/Fabrication#56]
"Fall damage should pan (not rotate) the camera down and then pan it back up again; and fire damage should make the screen shrink and expand, to make the damage sources a bit more clear. Exactly upwards and exactly downwards hits should also pan the camera like I suggested for fall damage."

This would be the first feature that expressly depends on another feature. Exciting.

How this should probably work is adding an "attacker pitch" field, and setting that to 180 for fall damage, and NaN for "self" damage like starvation, fire tick, etc.

**Comment by unascribed** [comment]
Responding to my own issue to test something.

**Comment by unascribed** [comment]
Testing again
