### ISSUE TITLE
"No Hunger" feature isn't working

### ISSUE THREAD

**Issue by pl0xdev** [FalsehoodMC/Fabrication#561]
https://gist.github.com/pl0xdev/f6cc882a94f537c4e20e99e0357bc98c

The No Hunger option seems bugged right now, bar is still visible & functions like vanilla.

**Comment by SFort** [comment]
for legacy reasons no_hunger is a part of taggable_players.
disable taggable_players
or go to `.minecraft/config/fabrication/taggable_players.ini` and remove no_hunger from it
