### ISSUE TITLE
Fabrication/Forgery renders server as unavailable on server list + extra armor/health applied by Apotheosis is flickering on armor/health bar

### ISSUE THREAD

**Issue by cl0ck-byte** [FalsehoodMC/Fabrication#563]
latest.log: https://gist.github.com/cl0ck-byte/b0d4a12b4740fa275818aad07e490c11

a) For some reason Fabrication renders server as unavailable while in fact I can connect to it.
![server_list](https://user-images.githubusercontent.com/35605833/198850185-16275af5-0c9a-4fdb-99b7-c14f8f30fdc0.png)

b) Weird health/armor bar flickering while wearing Apotheosis armor that applies extra armor/effects such as extra health.

Happens only on multiplayer instances.

https://user-images.githubusercontent.com/35605833/198850357-9fafa7af-9003-484d-b3c7-9872672ce80c.mp4

Example armor I was wearing: 
![armor](https://user-images.githubusercontent.com/35605833/198850220-88066c6c-d363-463c-b9e8-20f786347297.png)

As you can see, the speed boost is applied, but is quickly reverted back just to be applied again.

Modpack list:
Apotheosis-1.19.2-6.0.1.jar
forgery-3.1.1+1.19.jar
Patchouli-1.19.2-77.jar
Placebo-1.19.2-7.0.1.jar

**Comment by SFort** [comment]
Closing in favour of #602 (fixed) and #578
