### ISSUE TITLE
Inanimate invisability has unwanted effect with item frames

### ISSUE THREAD

**Issue by SFort** [FalsehoodMC/Fabrication#57]
Normally when an item frame is invisible the item inside it would still be visable
this is not the case when inanimates_can_be_invisible is enabled
without mod | with mod
:--------------------------------:|:-------------------:
![screenshot](https://user-images.githubusercontent.com/1879846/104452106-70c1b680-559a-11eb-934a-10aca85bd089.png) | ![screenshot](https://user-images.githubusercontent.com/1879846/104452243-9ea6fb00-559a-11eb-9805-c168c440c3b4.png)

**Comment by exaskye** [comment]
Wasn't aware item frames had custom handling for the Invisible flag.

**Comment by SFort** [comment]
just in case it's a bug invisibility_splash_on_inanimates doesn't work on armor stands

**Comment by exaskye** [comment]
Armor stands are technically living entities. I'll add special handling.

**Comment by exaskye** [comment]
This should be compatible with basically everything; it uses ASM to scan entity renderer classes and checks if they invoke isInvisible.

![image](https://user-images.githubusercontent.com/6185037/104502998-66e98480-5595-11eb-8b61-cef42f896e93.png)

**Comment by SFort** [comment]
Didn't know this was possible in java, neat. ty
