### ISSUE TITLE
Incompatibility with Lithium

### ISSUE THREAD

**Issue by Ethernalll** [FalsehoodMC/Fabrication#570]
Log: https://gist.github.com/Ethernalll/5a91d60c1eb83eae5e2e5bc3bc6fb5df

Mods Installed:
- Lithium
- Fabrication
- Fabric API

**Comment by magneticflux-** [comment]
Duplicate of https://github.com/unascribed/Fabrication/issues/566

This is fixed in eb9ac6a414a56fa5cb25c2ab725c5bdf46d97f53, which will be included in 3.1.3.

**Comment by Ethernalll** [comment]
Ah ok, that issue said it was C2ME and upon searching for "lithium" in issues nothing came up, so I figured it wasn't reported yet. thanks!
