### ISSUE TITLE
"Alt Absorption Sound" Crashes Game On Taking Damage

### ISSUE THREAD

**Issue by ghost** [FalsehoodMC/Fabrication#571]
Full Log: https://mclo.gs/zXl8tKz

**Comment by SFort** [comment]
i'm guessing this is the issue where loading fabrication with the feature set to false and then turning it on crashes.
if i guessed wrong please reopen

**Comment by ghost** [comment]
> if i guessed wrong please reopen

Might have to as I never even configured Fabrication from within the game, rather, I modified the config file and _then_ started my game.
I should have attached this too:
![image](https://user-images.githubusercontent.com/24266948/199952563-6d4d883a-fd09-4e35-9fcb-e3754d043643.png)

EDIT: As far as I can tell I don't even have the ability to reopen this myself. Will need your help for that!

**Comment by SFort** [comment]
i used "resolve" to try avoid gh auto closing the issue.

the commit probably fixes the issue (i say probably because i haven't gotten the crash possibly world specific/mod conflict no clue)

EDIT: i guess comment to reopen / open another in case it's still broke
