### ISSUE TITLE
Gray Creeper Heads

### ISSUE THREAD

**Issue by WenXin20** [FalsehoodMC/Fabrication#575]
```
Minecraft v1.19.2
Forge v43.1.52
Forgery v3.1.3
```

When the option "Foliage Creepers" is enabled, creeper heads render as gray in the inventory and when placed.
[Debug Log](https://gist.github.com/WenXin20/a82a0f922c06fff09440d818e73df159)

![image](https://user-images.githubusercontent.com/12000593/202973243-38cba548-127e-4ab9-ba2d-23bbaeb7cb5e.png)

![image](https://user-images.githubusercontent.com/12000593/202973322-ee521ffd-f2c7-414b-996c-cf2c4c0c5b20.png)

**Comment by SFort** [comment]
the 1.19.2 implementation of foliage creepers is super jank because mojang changed stuff and i was loosing my patiance i need to re do it at some point

**Comment by SFort** [comment]
i'm not getting gray creeper heads though. 
![screenshot](https://user-images.githubusercontent.com/1879846/202974814-54d27a17-bd0c-45d9-81ee-bfa4e6ac3ab4.png)

please try without any other mods installed, see if it's a conflict?

**Comment by WenXin20** [comment]
Hmm, I'll try without other mods. I should also mention this was on a server, and I have rubidium installed

**Comment by WenXin20** [comment]
This is odd, I reloaded the game, and now the heads are rendering normally.

**Comment by WenXin20** [comment]
I reloaded the game & server with the same mods, and once again the head is gray

**Comment by SFort** [comment]
1.19 foliage creepers was a disaster, should be fixed in the next release

**Comment by WenXin20** [comment]
Thanks!
