### ISSUE TITLE
1.19.2 Crash with Origins, Forge

### ISSUE THREAD

**Issue by Xaikii** [FalsehoodMC/Fabrication#576]
https://gist.github.com/Xaikii/8bbad566cc72d9470158040fea023b69

Forge: 43.1.57
Forgery: 3.1.3+1.19
Origins: 1.19.2-1.5.0.6
(Dependency)
Caelus API: 1.19.2-3.0.0.6

**Comment by SFort** [comment]
set `tweaks.less_restrictive_note_blocks` to banned for now or set it to false if you use limit_runtime_configs, and the game will hopefully boot.

forgery is currently in a state of barley existing on newer versions, which probably isn't changing soon

**Comment by Xaikii** [comment]
setting the config to false did not help, still crashes

**Comment by SFort** [comment]
> set tweaks.less_restrictive_note_blocks to banned

once you've done that it, if there's another crash it will be diffrent, so upload the new one if it still crashes after

**Comment by Xaikii** [comment]
https://gist.github.com/Xaikii/01aaf592b449fef2a3911eddaeb71159

**Comment by SFort** [comment]
that time it's `weird_tweaks.foliage_creepers`

**Comment by SFort** [comment]
also the debug has `Required config key tweaks.less_restrictive_note_blocks is not banned`
so could be loading the config isn't loading? (i'd make sure `config/forgery/features.ini` has the correct thing set to banned), also turn on limit_runtime_configs.
hope that gets the game runnig for now but if it doesn't i'll take a look a bit later

**Comment by Xaikii** [comment]
Well the crash is happening before the config is even generated, the only reason I do have the config is because I let it generate before.
And yes I am modifying the correct file.
setting creepers to false gave yet another crash.
https://gist.github.com/Xaikii/ad82cac36255f7b02ac166d0a8f02871

**Comment by Xaikii** [comment]
After setting "limit_runtime_configs" to true, the game now loaded
