### ISSUE TITLE
[1.19.2] [Forgery] Multiplayer server connect screen indicates as 'unable to connect' if Forgery is installed on the server

### ISSUE THREAD

**Issue by Not-February** [FalsehoodMC/Fabrication#578]
It appears as though the server is offline from the client's end even if it's not. Attempting to connect to the server anyways works just fine, it's just visually confusing.

Custom config values are not a factor, generating the defaults and attempting to connect leads to the same effect.

Whether Forgery is installed on the client or not makes no difference, the same immediate "cannot connect to server" message on screen and the same error message in the game log when it occurs:

`[Render thread/ERROR] [net.minecraft.client.multiplayer.ServerStatusPinger/]: Can't ping (server IP): Internal Exception: io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: Index 25 out of bounds for length 2`

Confirmed to occur with nothing but Forge and Forgery installed to a 1.19.2 dedicated server. It stops happening if Forgery is removed.

``Minecraft 1.19.2``
``Forge 43.1.52``
``Forgery 3.1.3``

Client logs:
[latest.log](https://gist.github.com/Not-February/76b75caad7afb1f18be0dec18906ad42)
[debug.log](https://gist.github.com/Not-February/4562965da26155531255ffa7723faab2)

Server logs:
[latest.log](https://gist.github.com/Not-February/5d6bc93a4a6abeb3572cb4cf4b7be837)
[debug.log](https://gist.github.com/Not-February/2e6c92b3d5c7336559da6e97f20df8fa)

**Comment by UDTakerBean** [comment]
Try setting `ping_privacy` to banned?

**Comment by Not-February** [comment]
Interesting if it's that, since I have my entire config set up to only enable features if I expressly enable them, and that particular feature is currently ``unset`` in my config... though I guess if the config isn't working, that would explain it.

Toggling it to false on the server's end doesn't seem to have changed anything.

**Comment by exaskye** [comment]
Forgery doesn't contain a version handler, and Forge defaults to assuming all mods cause breakage. Needs to get added; Forgery was my first post-1.14 Forge mod.

**Comment by Hyperbuss** [comment]
> Author

did changing the ping setting fix it? I'm having the same issue on 1,19,2 with the 3.2.7+1.19 version of the mod
