### ISSUE TITLE
[1.19.2][Bush Walk Doesn't Hurt With Armor] Wiki differ from in game logic

### ISSUE THREAD

**Issue by zeid0ne** [FalsehoodMC/Fabrication#579]
Wiki say : "with both leggings and boots equipped not deal damage"
But in game leggings without boots prevent damage (tested with netherite leggings).

**Comment by SFort** [comment]
tested on 1.19/1.18, it's working as described on the wiki.
dunno, any chance you sneaked after putting the leggings on? that's also a [feature](https://unascribed.com/fabrication/#tweaks.bush_walk_doesnt_hurt_when_sneaking)

**Comment by zeid0ne** [comment]
Could not reproduce again, yes maybe
