### ISSUE TITLE
Horse dual riding.

### ISSUE THREAD

**Issue by K0-RR** [FalsehoodMC/Fabrication#58]
Like in the boats.

![image](https://user-images.githubusercontent.com/43277609/104513214-93ca8580-55ef-11eb-9327-09cfebc1fd1d.png)

**Comment by exaskye** [comment]
This might be simple or this might be nigh-impossible. Need to look into it.

**Comment by SFort** [comment]
[curseforge](https://www.curseforge.com/minecraft/mc-mods/dual-riders)
