### ISSUE TITLE
[1.16] Crash when Eidolon is installed

### ISSUE THREAD

**Issue by Weedoof** [FalsehoodMC/Fabrication#580]
As the title.
Any version of Forgery 3.1+ causes a crash when Eidolon is installed.
Happens in a clean instance with only the two mods (Plus eidolon's prereq, curios).

latest.log uploaded here.
https://gist.github.com/Weedoof/dbb27a7f4a1adc5f1d72059f68a19f0b

(Oh, and on a more personal note - thanks for still updating 1.16!)

**Comment by SFort** [comment]
set `utility.mob_ids` to `banned`. (of if you use limit_runtime_configs it can be false).

**Comment by Weedoof** [comment]
Well, mixed news.
Setting mob_ids to banned didn't work for eidolon, but false with limited runtime configs worked.
Only issue is that now there are other mods causing issues. They did earlier too, I just didn't notice them earlier since they were buried under a small mountain of errors. Those other mods being Simple Planes and Twilight Forest.

I assume the errors are the same, but if not here's the latest.log for each.
https://gist.github.com/Weedoof/4f3291a219d210991fc98c675c5e30b7 - Simple planes
https://gist.github.com/Weedoof/6ab1815094c84a7cb59517ec3b892522 - Twilight Forest

**Comment by SFort** [comment]
that would be because it wasn't actually mod_ids and i missed the actual reason in the original log
