### ISSUE TITLE
Sculk Catalyst does nothing when Disable EXP is on

### ISSUE THREAD

**Issue by Noobulus** [FalsehoodMC/Fabrication#582]
Technically this is just a knock-on effect of the intended behavior, but it deserves mention. Sculk Catalysts do not produce any sculk blocks when a mob dies near them with Fabrication's Disable Exp feature enabled. Some method of creating additional sculk blocks with this feature enabled (or just a tweak to catalysts to make them work correctly) would be nice to have. Thanks!

**Comment by exaskye** [comment]
Most features under "Extra" are such because they are invasive and cause major mechanic breakage; No EXP is not an exception, due to its nature as a nuclear "remove this mechanic" feature.

Works as intended.

**Comment by exaskye** [comment]
To note,  a more nuanced feature, such as one that splits off the anvil and enchanting table effects, would be the solution to this. But "No Experience causes a new experience-based mechanic to not work" is not a bug.

**Comment by Noobulus** [comment]
so i didn't know that sculk catalysts required player kills instead of just any death around them. this feature actually works completely fine. 🤦
