### ISSUE TITLE
[1.19.2] Foliage Creepers & Continuity

### ISSUE THREAD

**Issue by JLUsr** [FalsehoodMC/Fabrication#585]
No log since this isn't a crash and, honestly, I forgot to ask for one from the person who is actually having this issue and am too lazy to reproduce it for myself.

When the `Foliage Creepers` feature is enabled [`Continuity`](https://www.curseforge.com/minecraft/mc-mods/continuity) simply doesn't work. I don't need the feature myself; however, seeing as there wasn't an issue posted for it I thought I might as well submit one.

**Comment by SFort** [comment]
so currently foliage creepers works by
- changing the creeper texture identifier namespace to "fabrication_grayscale" from "minecraft"
- adding a ResourcePackProvider to MinecraftClient's ResourcePackManager, which creates grayscale textures for anything with a "fabrication_grayscale" id
- changing the render color to the biome foliage color

i have no idea why this would interfeare with connected textures. but it clearly does so i'm just going to mention @PepperCode1 and hope that notifies them and they don't mind being notified, maybe even know what's going on already. if not, i'll try and look into it when i can.

**Comment by SFort** [comment]
this was totaly my fault, if peppercode did get a notification for this, sorry.
