### ISSUE TITLE
With Infinity on Crossbows, Infinity can only be applied to the vanilla crossbow.

### ISSUE THREAD

**Issue by RecyclingTiger** [FalsehoodMC/Fabrication#586]
Tested with crossbows from various mods, like spartan weaponry, dungeons gear, and upgraded netherite in 1.16.5
and tested with dungeons gear in 1.19.2.

With an anvil in survival mode, it can only be put on the vanilla one.
However it does work on modded crossbows if applied through creative or cheats.
It even works on crossbows that fire special projectiles like the heavy crossbow from spartan.
The issue is that it just can't be applied to them in the first place

Debug 1.16
[debug.log](https://github.com/FalsehoodMC/Fabrication/files/10691805/debug.log)
Debug 1.19
[debug.log](https://github.com/FalsehoodMC/Fabrication/files/10692683/debug.log)

**Comment by SFort** [comment]
having infinity on moded crossbows is bound to be janky in some way.
added `woina.extra.infinity_crossbows_modded`
