### ISSUE TITLE
Toggle Sprint fails injection on forgery

### ISSUE THREAD

**Issue by Aceplante** [FalsehoodMC/Fabrication#588]
FabInjector failed to find injection point for net/minecraft/client/player/LocalPlayer;m_8107_()V	Lnet/minecraft/client/KeyMapping;m_90857_()Z
 located in com.unascribed.fabrication.mixin.b_utility.toggle_sprint.MixinClientPlayerEntity

nvm it wasnt your mod but still this part^

**Comment by SFort** [comment]
i'd need the mixin export to make sure, but i'm assuming some other mod modifies the same bit of the game. making the injection fail and toggle_sprint getting turned off (it shouldn't crash though, correct me if it does)

**Comment by SFort** [comment]
i'd like to find out what mod is causing it, to have something to test with when i get around to it. could you please add `-Dmixin.debug.export=true` to the java args, launch the game and send over `.minecraft/.mixin.out/class/net/minecraft/client/player/LocalPlayer.class`

**Comment by Aceplante** [comment]
At the time i was trying to use better combat which seems to be the cause of the crash. After disabling it, your mode works fine and I do not seem to get that message

**Comment by Aceplante** [comment]
Im not sure how to do what you mentioned

**Comment by SFort** [comment]
if you're using the vanilla launcher you click launch options, turn on advanced settings, turn on JVM arguments, add `-Dmixin.debug.export=true` to the args which will export the class to the before mentioned path.

**Comment by SFort** [comment]
the other way to check what mod causes it would be to add/remove mods untill toggle sprint doesn't show up when you type `#failed` into the UIs feature search.

that takes a bit though and this is probably fixed in 3.2.1 anyway
