### ISSUE TITLE
inanimates_can_be_invisible doesn't work correctly with glow frames

### ISSUE THREAD

**Issue by SplendidAlakey** [FalsehoodMC/Fabrication#590]
**MC** 1.19.2
**Fabric** loader 0.14.17 ] API 0.75.1
**[Improved Signs](https://www.curseforge.com/minecraft/mc-mods/improved-signs)** 1.2.0
**Fabrication** 3.2.0

To reproduce:

1. Install both mods and run the game with default configs
2. Create/load into a world, place a glow item frame anywhere you want
3. Place any item into the frame
4. Make the item frame invisible with the amethyst shard
5. Hit the frame to make it visible again
6. Receive no shard back, which is the intended behaviour of Improved Signs

Disabling/unsetting `inanimates_can_be_invisible` restores the intended behaviour.

Logs: https://gist.github.com/SplendidAlakey/b305d639c04b4604110a17f80fa61866

**Comment by exaskye** [comment]
Improved Signs on its own does not return Amethyst Shards when un-invisible-ing item frames — I checked the code and tested in a fresh instance. The modpack you experienced the drop behavior in probably has Charm, which is duplicating amethyst shards when frames are made invisible by other mods. In this case it's not a dupe as the other mod is also using an amethyst shard. See https://github.com/svenhjol/Charm/issues/639 — we have a workaround on our side ("Fix Charm Amethyst Dupe" feature) but Charm has not (and likely never will) fix the underlying issue.

**Comment by SplendidAlakey** [comment]
Sorry, the shard does indeed not return with just Improved Signs.

However, there's still a bug between Fabrication and Improved Signs: the item itself in the glow frame becomes invisible, when you make the frame invisible. I completely forgot to mention this in the initial report... Should I make a new one?

Quick edit:

Unless that's what the rule should do and I completely misunderstood it, however, then the bug is the opposite - the regular frame doesn't get affected.

With the rule enabled:
![2023-03-16_05 25 42](https://user-images.githubusercontent.com/86702831/225514579-7d24bf97-adb3-4fff-aec9-7e2aad704d7d.png)

Without the rule:

![2023-03-16_05 27 09](https://user-images.githubusercontent.com/86702831/225514587-3d81e39f-2484-47dd-a43c-f1de2ab03d66.png)

**Comment by SFort** [comment]
so this is #57 but with a modded frame.
i removed the reflection in 72bbbbc because of #559 
the reflection should probably be re-added? was just not up to it at the time

**Comment by SplendidAlakey** [comment]
It's only "modded" in a sense, that the invisibility feature is added by a mod, the frame itself is vanilla glow item frame. Just to be clear.

**Comment by SFort** [comment]
ye i skimmed through this way too quickly the first time.
this isn't a mod conflict i just made a mistake and the feature dosn't work with glow frames

**Comment by SFort** [comment]
fixed in the next release ( 06317b0 )
