### ISSUE TITLE
Water Halves fall damage option?

### ISSUE THREAD

**Issue by Aceplante** [FalsehoodMC/Fabrication#591]
There is one for lava, why not water too?

Or even better if it could be removed altogether. Water can already slows the player to a point where they wouldnt take fall damage anyways it doesnt need to negate it completely. Its like terraria wings for some reason.

**Comment by SFort** [comment]
> There is one for lava, why not water too?

`lava_causes_fall_damage` causes the fall damage immediatly on contact with the lava, it just didn't feel right with water i guess.


> Or even better if it could be removed altogether. Water can already slows the player to a point where they wouldnt take fall damage anyways it doesnt need to negate it completely. Its like terraria wings for some reason.

i think the simplest solution for this is to make it gradually ramp down falldamage based on velocity.

note that vanilla minecraft fall damage isn't based on velocity, but distance.
so for example if i would just disable waters falldamage reseting and then walk into a 23 block deep water filled hole and then slowly sink without any real speed it'd still kill.

**Comment by SFort** [comment]
added in 40ebbd9 (release 3.2.1)

**Comment by Aceplante** [comment]
Thank you ill try it now
