### ISSUE TITLE
Void particles z-fighting

### ISSUE THREAD

**Issue by Abalieno** [FalsehoodMC/Fabrication#599]
I tried asking in Discord a few days ago.

I also tried removing everything, including sodium & co, but without any difference.

![739](https://user-images.githubusercontent.com/4656436/235431098-bea171c9-c3e6-4261-8797-64c17aab771b.png)

I'd like to know if this is a known problem and if the cause is avoidable... Before turning it off in the modpack and forget about it.

**Comment by SFort** [comment]
what fabrication version / minecraft version?
might be a mod conflict, did you try with just fabrication installed?

**Comment by Abalieno** [comment]
Yeah, pretty much a clean modpack. Using fabrication-3.1.9+1.19

EDIT: I meant 3.2.6, but it was the same with 3.1.9

But I've noticed the problem in earlier versions.

**Comment by SFort** [comment]
i'm not getting it and i have no clue what's going on, maybe una does?

https://user-images.githubusercontent.com/1879846/235437863-ccad254c-9cfa-4f44-94a5-731ae13f1221.mp4

**Comment by exaskye** [comment]
It seems like the particle is getting a texture somehow?

Could you send us a crash report and game log? Hold F3+C for 10 seconds to crash the game even though it's working normally — crash reports contain a lot of useful debug info.

**Comment by Abalieno** [comment]
[crash-2023-05-02_03.21.12-client.txt](https://github.com/FalsehoodMC/Fabrication/files/11368999/crash-2023-05-02_03.21.12-client.txt)
[latest.log](https://github.com/FalsehoodMC/Fabrication/files/11369008/latest.log)

**Comment by exaskye** [comment]
Normal GPU (not some jank Intel thing, or some antique card), Windows, no OptiFine or even Sodium, nothing exceptional in the log. Hmm.

**Comment by Abalieno** [comment]
![Recording 2023-05-02 at 05 41 55](https://user-images.githubusercontent.com/4656436/235574747-2a51fc94-0d21-411c-aa86-e4b4652d15c6.gif)

**Comment by exaskye** [comment]
So they are actually flickering, that's strange...

**Comment by SFort** [comment]
the zip has two versions of fabrication please try each one. this is probably just my blunder mixing up max/min UV
(as to why it only happens you, i have no clue)
[test.zip](https://github.com/FalsehoodMC/Fabrication/files/11377041/test.zip)

**Comment by Abalieno** [comment]
Both seem to work. The wool one has a gray wool texture (working normally).
