### ISSUE TITLE
Protection I-IV on items with varying effects based on enchantment tier

### ISSUE THREAD

**Issue by Enesore** [FalsehoodMC/Fabrication#60]
To elaborate, Protection I would prevent cactus damage, Protection II would prevent fire damage, Protection III would prevent lava damage, and Protection IV would prevent explosive damage. The effects would be additive, so Protection IV would protect the item from every source of damage, except for void damage.

**Comment by exaskye** [comment]
This sounds like a good way of handling this. The current fire_protection_on_any_item tweak just ignores the level and it's a little odd.

**Comment by exaskye** [comment]
I've received an overwhelming number of feature requests over the week and they are filling up the issue tracker and making it difficult to keep track of what is even going on. I've enabled [Discussions](https://github.com/unascribed/Fabrication/discussions) on the repo as a new location for feature requests. Unfortunately, GitHub has "temporarily" disabled the ability to convert issues to discussions, so I'm closing all feature request issues. However, I'm tracking all the closed issues in a Project board; despite being closed, they're still on my radar on the board. **All new feature requests *must* go to Discussions. Feature requests opened as issues going forward will be closed.**
