### ISSUE TITLE
Pink Textures Everywhere

### ISSUE THREAD

**Issue by Aetrnl94** [FalsehoodMC/Fabrication#600]
There was no crash report, but every time I try and load in Forgery the entire game turns pink, making it impossible to play. I'm not sure if it's an issue with Optifine or not, but I can't find any more info on how to resolve it.
![2023-05-01_14 43 59](https://user-images.githubusercontent.com/131720204/235518557-b9fe886a-78fe-458e-b404-0642bc739a54.png)

**Comment by Aetrnl94** [comment]
I tried removing all of my resource packs other than the ones that this mod forces in, and the only difference is what color the shades are, either bluish or purplish.

**Comment by SFort** [comment]
tried with optifine with forgery 3.2.6, on 1.19.4 and i'm not getting it on that version please figure out what exactly is causing it, maybe a shader or another mod?

**Comment by Aetrnl94** [comment]
Yeah, I'm running through my other mods to see what might be the cause. I have 145 installed (all working other than Forgery), so bear with me >.>

**Comment by Aetrnl94** [comment]
OK so I managed to get the issue resolved (it was CheatUtilities -> Fullbright), but now I'm unable to load the game due to not enough Java heap space. If I remove Forgery, the issue resolves itself. Any idea what could be causing the heap space issue?

**Comment by SFort** [comment]
post a crash log and narrow it down to the minimum amount of mods that are required for the crash.

**Comment by SFort** [comment]
ended up testing CheatUtilities fullbright, all it does is give you night vision it is not the cause of the original issue. (guessing you have another mod installed that somehow causes this when forgery is installed and the player has night vission)
please start with forgery and gradually re-add the mods, to narrow it down the conflict, to something i can reproduce
