### ISSUE TITLE
[1.16.5][Forgery]Re-entering world via any means causes item drops in world to flash at a seizure-inducing rate

### ISSUE THREAD

**Issue by NighthowlerStudios** [FalsehoodMC/Fabrication#601]
Using a portal to teleport back to the same world as the item drop or reloading the world after closing it via any means causes the item's flashing to speed up exponentially until it is very distracting and possibly seizure inducingly fast.  I have a feeling the timer is somehow misloading its parameters when it's required to derive data from the save file in this fashion.

**Comment by SFort** [comment]
(thanks for this, since it turns out i accidently removed blinking drops from 1.16 and didn't notice, the reason you still got the feature was i didn't accidently remove the obfuscale compat which i assume you have installed)

Please install the newest forgery when it comes out, check if it this still happens (it probably will) andfigure out the minimum required mods to reproduce this as i'm not getting it when installing forgery on it's own.

**Comment by NighthowlerStudios** [comment]
Thanks for the information.  Unfortunately I do not have Obfuscate Library installed, so I am unsure my issue is related to that.  I will still be waiting for the curseforge release and will test for it anyways, though.

**Comment by SFort** [comment]
oh you're issue is purley with `despawning_items_blink` i assumed it was also `blinking_drops` (the feature that's been re-added), ye the new version deffinatly won't change anything then.

i'm still not getting the issue though so i'm gonna need instructions as to how to reproduce it.


https://user-images.githubusercontent.com/1879846/236623796-6867e2df-7c67-4202-aaea-dacd9b4f3939.mp4

**Comment by NighthowlerStudios** [comment]
That blinking in your video is not what I am experiencing, no.  What I'm seeing is a flash of white, which I would really love to have.  But if I leave that world and come back, all dropped items are flashing that white colour at a rapid rate.  I was able to stop this via disabling blinking_drops.  I don't think you've kept track of the separate blink types.  there are two even in 1.16.5

the blinking you are demonstrating in your video is strictly the despawning_items_blink, which doesn't work at all for me (or at least I don't remember it working).  so I'm starting to believe it may be a client side issue.

I will send you a video of both what happens when I have blinking_drops enabled, and when I have them disabled

the config I'm setting is here and responsible for the bug I'm posting this for is represented in this text:
```
; Forward ports of forgotten tidbits.
; 
[woina]
	; Client Only
	; 
	; Back in Survival Test, drops blinked white to make them 
	; stand out more. This is an implementation of that.
	; If Utility > 
	; Despawning Items Blink is enabled, that tweak's disappear-flashing 
	; will be disabled, and instead this tweak's white flashing will get 
	; faster and faster as despawn approaches. 
	; 
	; 
	; Demonstration video: https://unascribed.com/fabrication/blinking_drops.mp4
	; Survival Test video, for reference: https://unascribed.com/fabrication/survival_test.mp4
	blinking_drops=banned

**Comment by NighthowlerStudios** [comment]
Note how the config makes it clear the algorithm involving it is meant to speed up the flashing as despawn approaches.  I theorize that whatever timer is being used for this may be getting a negative or zero value in time elapsed which causes the flashing to switch for every frame the client renders.

**Comment by SFort** [comment]
the following zip contains the dev build of the 1.16 branch, if you're testing with blinking_drops you might as well use it to avoid any potential re-testing headaches [forgery.zip](https://github.com/FalsehoodMC/Fabrication/files/11412698/forgery.zip)

**Comment by NighthowlerStudios** [comment]
Understood, I will install that version and start testing immediately.  I will still upload footage as necessary

**Comment by NighthowlerStudios** [comment]
If you feel it better you can get in touch with me via Discord if you wish not to clutter this git issue.  Kaleidio#1714

**Comment by SFort** [comment]
i don't really mind since github at least reliably notifies me.
if you prefer you can use una's catch all [discord](https://discord.gg/8WBauq2eYK), don't have an account but the channels get bridged to me, so that works as long as i'm online, haven't tested if i get notifications while i'm offline, probably not matrix is an abomination

**Comment by NighthowlerStudios** [comment]
the dev build you gave does not have the flashing at all regardless of having that option unset nor banned.  I have no clue what has happened between then and now.  but if I revert back to public 3.2.6, the white flashing comes back.

is it intended for that feature to not be working at all at the moment?

**Comment by SFort** [comment]
if you loaded the game with the setting set to banned the feature will not get injected and cannot be enabled untill restart

**Comment by NighthowlerStudios** [comment]
> if you loaded the game with the setting set to banned the feature will not get injected and cannot be enabled untill restart

that is not the case here sadly as I did restart the modpack twice after verifying I set the setting to "unset" instead of "banned" :(

**Comment by NighthowlerStudios** [comment]
I have dinner to get to so I will be a couple hours, when I come back I will send footage of the white flashing I was on about in 3.2.6 and demonstrate it breaking for you.  Then afterward I will see if my mod list has any incompats, though that may not be done for a couple of weeks as sadly I have university assignment submissions upcoming.

**Comment by SFort** [comment]
could you send the log for the dev version as it should work i'm getting the opposite and 3.2.6 doesn't

**Comment by NighthowlerStudios** [comment]
it has absolutely nothing interesting in it, nor any errors related to Forgery at all, but here you go I guess.  It may also help indicate the modlist for you if you spot any possible problems.

I just got back from dinner and will be recording what I'm on about now

note I'm still using Kaleidio's Battle Pack: KBP - 5.3.0-pre7, for testing. it is available on CurseForge if you wish to install and test as well, and should be configured to have the flashing on already, and reproduce the issue in the way I originally posted through it.

[latest.log](https://github.com/FalsehoodMC/Fabrication/files/11412961/latest.log)

**Comment by NighthowlerStudios** [comment]
I finally gathered some footage for you and have discovered it is not based on dimension/loading at all.  in fact, it is the "high speed mode" of the flashing timer is just straight up broken.  I will edit down the footage to show you and send it in a few minutes

**Comment by NighthowlerStudios** [comment]
https://www.youtube.com/watch?v=uQWHSB6ZWMw

note here the pistol was dropped first before all other items, about 8 minutes before this footage was found.  notice how it's flashing absurdly fast.

the white effect will not show at all in 3.2.7, but it does here, and it breaks if the item exists long enough

**Comment by SFort** [comment]
using the pack, the issue did appear,
this is what it looks like on latest dev build in your pack:

https://user-images.githubusercontent.com/1879846/236643010-4df220e1-d4a3-4f30-b178-26aa5ed32c54.mp4

the blinking twords the end isn't perfectly accurate since something in the pack changes despawn times

**Comment by NighthowlerStudios** [comment]
That makes a ton of sense as my pack changes despawn time to some different amount of minutes (i can't remember the exact ticks i used in the config) via Item Physics mod.  Hopefully the commit fixed that.  Thanks a bunch

**Comment by NighthowlerStudios** [comment]
Tested 3.2.7 on curseforge, and for whatever reason the white blinking still isn't happening at all, but the transparent blinking is.  is it only supposed to happen after a specific age of the item?

**Comment by SFort** [comment]
<details>
<summary>
one quick and dirty ffmpeg command later i have a video small enough to be uploaded to github (sorry but that means painfully low framerates)
</summary>

`ffmpeg -i in.mkv -vf "crop=2722:1280:580:580,scale=-2:480,setpts=0.125*PTS,fps=16,format=yuv420p,tpad=stop_mode=clone:stop_duration=3" -sws_flags spline -c:v libx264 -profile:v high -preset veryslow -c:a aac -an out.mp4`

</details>

summary:
- do a fresh install of your pack
- replace the old forgery with the new one
- launch the game it crashes for mysterious reasons
- launch it again
- throw a pistol and a block on the ground
- it blink

soo i dunno what's going on seams to work?


https://user-images.githubusercontent.com/1879846/236691692-7a8e6bd7-3c79-474b-b3ca-b0aacd3a80db.mp4

**Comment by NighthowlerStudios** [comment]
Can you send a log of the mysterious crash?  Wanna put it on my "wtf" list as there's a bunch of crashes i have been tracking hence the beta pre7

I will reinstall forgery as many times as needed to see if I can force it to start working.

**Comment by SFort** [comment]
i may have labeled the crash, "log" and the log, "crash" by accident

[crash.txt](https://github.com/FalsehoodMC/Fabrication/files/11415682/crash.txt)
[log.txt](https://github.com/FalsehoodMC/Fabrication/files/11415683/log.txt)

my best guess as to why blinking is working for me and not for you might be because you have a dev build of your pack and i had a fresh install?

**Comment by NighthowlerStudios** [comment]
I am unsure at this point, I am still working on a dev instance of pre8 but not much is different between it and pre7.

the crash you had is known and on my todo list.  for whatever reason a mod is somehow forcing the game to *not* register blocks until a time such mod specifies, causing structure generators to try accessing data that doesn't exist yet.  it is completely random and thread race based.  I have yet to figure out which mod is at fault for that one
