### ISSUE TITLE
Incompatibility with Apotheosis: Armor attributes flickering

### ISSUE THREAD

**Issue by LuizLoyola** [FalsehoodMC/Fabrication#602]
When wearing armor that changes player attributes (max health, extra armor, speed, etc...) the attributes flicker constantly.
This only happens on a dedicated server.

Steps to reproduce:  
- Create a Forge server with Forgery and Apotheosis only
- Connect to the server
- Get an Apotheosis armor that changes attributes (Command `/apoth lootify ancient` converts a piece of armor in your hand)
- Wear it
- If it has speed, the FOV will change repeatedly
- If it has extra max health/armor, the hearts/armor bars will change constantly

Note: Tested this with vanilla armor with added attributes and the bug did not happen. This is related to Apotheosis specifically.

Versions:
Minecraft 1.19.2
Forge: 43.2.10
Apotheosis: 6.1.5
Forgery: 3.2.6+1.19
Patchouli: 1.19.2-77
Placebo: 7.1.8

Server debug.log: https://gist.github.com/LuizLoyola/e106e77e924c5547381a3298be7b8bb7
Client debug.log: https://gist.github.com/LuizLoyola/600b12441fef235b252c3b6ac1bb4c21

**Comment by LuizLoyola** [comment]
Related Apotheosis Issue: https://github.com/Shadows-of-Fire/Apotheosis/issues/752

**Comment by SFort** [comment]
thanks for pointing of the command, it was helpfull in debugging since i'm not that fammiliar with the mod
