### ISSUE TITLE
Game Freezes

### ISSUE THREAD

**Issue by muhammedesadcomert** [FalsehoodMC/Fabrication#603]
The game freezes when trying to render a creeper provided by the Foliage Creepers feature.

Minecraft: `1.19.4`
Fabrication: `3.2.7`

You can see the `features.ini changed` info at the last of the log, and there is nothing except this. However the game does not crash (I force-closed it), it just freezes and I think it's a client-side issue because the server won't stop, for instance, you can be killed by a zombie while the freezing issue.

Logs: https://mclo.gs/9YlivJV

**Comment by SFort** [comment]
i'm not getting the issue with only fabrication installed please figure out the minimum mods required to reproduce the issue
