### ISSUE TITLE
Backporting 1.18 mob spawning changes

### ISSUE THREAD

**Issue by anoomolu** [FalsehoodMC/Fabrication#604]
Hiya! Love all the little tweaks that this mod offers, and I just wanted to suggest another one that backports the 1.18 mob spawning changes to 1.16. With this, mobs would only spawn at blocklight = 0 rather than the current light level <= 7. I think it's a nice change that reduces the need for weird torch patterns and whatnot.

That being said, I understand if it's not quite in line with what Forgery/Fabrication aims for. Cheers ^^

**Comment by SFort** [comment]
added `no_block_lit_mob_spawning` in 3.3.4
