### ISSUE TITLE
Hyperspeed Furnace Minecart not going hyperspeed

### ISSUE THREAD

**Issue by anoomolu** [FalsehoodMC/Fabrication#606]
debug log: https://gist.github.com/anoomolu/1ce1a347a32572f9a0bc4902545e8c61

Hiya. I did some quick testing with the "Hyperspeed Furnace Minecart" tweak on 1.16.5 with only Forgery installed, and found that there's no difference in minecart speed when the tweak is enabled/disabled. In both cases, the furnace minecart moves 20 blocks in around 5 seconds, or 4 m/s.

It'd be amazing to have this working as intended, as minecarts are an often forgotten mode of transport that I'd love to make relevant in my personal pack.

**Comment by exaskye** [comment]
The Hyperspeed Furnace Minecart tweak is incompatible with Forge because Forge rewrites the minecart logic. No one has gotten around to *completely rewriting the feature from the ground up* to use Forge's APIs.

**Comment by anoomolu** [comment]
Oh okay, thanks for letting me know. idk why they'd do that but I guess that applies for lots of things when it comes to Forge
