### ISSUE TITLE
Add age to vines, sugar cane, bamboo, etc.

### ISSUE THREAD

**Issue by ZeekDaGeek** [FalsehoodMC/Fabrication#607]
Might not be the best place to suggest things, but the way Fabrication/Forgery does it's tweaks are so seamless and the client side optional design means I always include it in any pack I play, since it can always be added.

As of 1.18 Cave Vines and Kelp have a hidden age stat that makes it so as they grow the new section ages, once their old enough they no longer grow anymore resulting in oceans and caves with varying and interesting foliage, additionally you can right click on any Cave Vine or Kelp with a shear it causes the vines to stop growing.

**It would be great if there was a tweak that added the feature to Vanilla vines**, allowing you to right click with shears to stop growth and prevent things from getting out of control. Additionally if only the bottom of vines were able to spread sideways to prevent odd looking sideways vine creep.

The feature could also be implemented on Bamboo, and allow right clicking with an Axe to force the Bamboo to specific heights and add the bamboo "I'm done growing" topper.

A bonus for clients that could be nice would be a tapered bottom to vines that are max aged? Definitely not needed though.

Something similar could be added to Sugar Cane and Cactus for varying heights, but who knows.

Right now Vines are a blight on the edges of mountains and every jungle ends up with everything at max length.
![Vine Blight](https://github.com/FalsehoodMC/Fabrication/assets/1709288/d4d73007-7f6f-4c2c-847f-19da9ef552ec)
![Overgrown Jungle](https://github.com/FalsehoodMC/Fabrication/assets/1709288/9d738bcd-9e4b-4510-bac6-dad50a5c620b)

**Comment by SFort** [comment]
would be neat to have it, not adding it to fabrication though.
every way of doing this that stays vanilla compatible is waay to janky and would cause lots of issues, that i couldn't fix.

the best one for compat, that i can think of would probably be spawning an entity at the end of the vine? but that's also past my jank limit and is something more apropriate for a datapack. 
best solution for this is probably a standalone mod that replaces the vines with modded ones that look exactly the same
