### ISSUE TITLE
[1.16.5 Forge] Optifine Shaders cause Classic Block Drops to not render the item and render half shadows

### ISSUE THREAD

**Issue by NighthowlerStudios** [FalsehoodMC/Fabrication#609]
I assume this is because of the UV trick implemented.  What is strange is how it's affecting block drop normals in how they're projected against the shadow map.  Used Complementary Shaders 4.7.1 for this, but I believe the issue also appears in any BSL derived shader really.

**Comment by SFort** [comment]
Duplicate of #610

**Comment by NighthowlerStudios** [comment]
woah weird, I have no clue how this got duplicated.  i must have been dead asleepy...
