### ISSUE TITLE
Mob spawners make a sound when spawning a wave of mobs

### ISSUE THREAD

**Issue by yoannlr** [FalsehoodMC/Fabrication#61]
When spawning a new wave of mobs, spawners emit a sound - something similar to the sound you get when enchanting something in an enchanting table.

**Comment by exaskye** [comment]
I've received an overwhelming number of feature requests over the week and they are filling up the issue tracker and making it difficult to keep track of what is even going on. I've enabled [Discussions](https://github.com/unascribed/Fabrication/discussions) on the repo as a new location for feature requests. Unfortunately, GitHub has "temporarily" disabled the ability to convert issues to discussions, so I'm closing all feature request issues. However, I'm tracking all the closed issues in a Project board; despite being closed, they're still on my radar on the board. **All new feature requests *must* go to Discussions. Feature requests opened as issues going forward will be closed.**
