### ISSUE TITLE
Void fog at y0 instead of below y-64

### ISSUE THREAD

**Issue by Aceplante** [FalsehoodMC/Fabrication#615]
With the void fog option, the particles appear from about -10 to 0 instead of below -64, the new bottom of the world as of 1.18

forge 1.18.2

**Comment by SFort** [comment]
https://github.com/FalsehoodMC/Fabrication/assets/1879846/55daaf96-9eff-4e25-914c-42e2713ea302

seames to work,
maybe a mod conflict or maybe it's somehow caused by importing an old world?
please try to narrow down the cause

**Comment by Aceplante** [comment]
ah, good point, I should probably do more testing. sorry

**Comment by Aceplante** [comment]
If this happens again ill open with more info
