### ISSUE TITLE
Known issues that aren't likely to see a fix soon

### ISSUE THREAD

**Issue by SFort** [FalsehoodMC/Fabrication#616]
The features listed here are turned off

- `block_logo` doesn't render on 1.20+
- `end_portal_parallax` is glitchy on 1.16

The above applies to Fabrication, Forgery has a whole lot more added on top of that.

<details>
<summary> more todo's as a note to myself in case i get the time </summary>

- IMPORTANT: bring back the burnt coffe bean (in general.category have none,all,all+extra)
- Feature fail should store the failiure reason and display it in UI
- UI for certain features needs rework
- oh god forgery tools
- Internal injection stuff todo with other mods redirects #618 
- injection redirect stuff should be togglable, as it's been the source of every FabInject problem

</details>

**Comment by forkiesassds** [comment]
It may have to do with the shader used to render or something with model transformations not using some matrix point or something, not sure. Another mod which ported the old logo has fixed this issue.

**Comment by SFort** [comment]
Closing in favour of 639 (bug bounties)
