### ISSUE TITLE
Particle/sound effect when a mob spawns naturally in the world

### ISSUE THREAD

**Issue by yoannlr** [FalsehoodMC/Fabrication#62]
When a living entity naturally spawns in the world (a monster spawns at night, or an animal spawns), some particle effect - like smoke - accompanies the entity.
Some sound effect could also be played, such as a "pop" (egg) sound.

**Comment by torzod** [comment]
i vaguely remember the "flame" particles being associated with mobs spawns in older versions, though i could very well be misremembering. this was most noticeable in peaceful mode

**Comment by exaskye** [comment]
Flame particles are (were?) used for spawners, at least.

**Comment by torzod** [comment]
i'm aware of spawner particles, as well as the smoke clouds they make when spawning mobs, but i recall the torch particles appearing at the center of a mob when it naturally spawned.

**Comment by exaskye** [comment]
If so, it's not present in Beta 1.2_01 which is the current legacy version of Minecraft I have around and decompiled.

**Comment by torzod** [comment]
I was not playing the game in the beta stage, i'll check some versions later today and update this if I can find if it exists

**Comment by exaskye** [comment]
I've received an overwhelming number of feature requests over the week and they are filling up the issue tracker and making it difficult to keep track of what is even going on. I've enabled [Discussions](https://github.com/unascribed/Fabrication/discussions) on the repo as a new location for feature requests. Unfortunately, GitHub has "temporarily" disabled the ability to convert issues to discussions, so I'm closing all feature request issues. However, I'm tracking all the closed issues in a Project board; despite being closed, they're still on my radar on the board. **All new feature requests *must* go to Discussions. Feature requests opened as issues going forward will be closed.**
