### ISSUE TITLE
3.3.0 - Crashes on startup

### ISSUE THREAD

**Issue by Nincodedo** [FalsehoodMC/Fabrication#620]
Crashes with no other mods installed on Minecraft 1.20.1.

https://gist.github.com/Nincodedo/a2f51f1cf7c66572114b0c81204a4d33

**Comment by exaskye** [comment]
Multiple people are reporting 3.3.0 is broken, so I'm pulling the update.

Roll back to 3.2.7/3.2.8 until SFort has a chance to fix it.

**Comment by SFort** [comment]
please retest with [3.3.1](https://github.com/FalsehoodMC/Fabrication/releases/download/v3.3.1_test/fabrication-3.3.1+1.20.jar)

**Comment by Nincodedo** [comment]
I was able to start the game and load into a world with 3.3.1, no issues. Thank you!
