### ISSUE TITLE
Crash when loading world on Quilt 0.19.1 for 1.20

### ISSUE THREAD

**Issue by Fiopon** [FalsehoodMC/Fabrication#621]
https://gist.github.com/Fiopon/ccfd6a7399ec6da82f414a9ade942757

Only Quilt 0.19.1 for 1.20 with Quilt Fabric API & Fabrication

**Comment by SFort** [comment]
please retest with [3.3.1](https://github.com/FalsehoodMC/Fabrication/releases/download/v3.3.1_test/fabrication-3.3.1+1.20.jar)

**Comment by Fiopon** [comment]
Tested with no issues, thank you
