### ISSUE TITLE
[3.3.1+1.20] Crash to Desktop when placing signs or opening sign edit GUI

### ISSUE THREAD

**Issue by JoelZBub** [FalsehoodMC/Fabrication#622]
Minecraft 1.20.1
Forge 47.0.35
Forgery 3.3.1+1.20

Single Player game crashes when placing any sign or right clicking signs to edit. 
Issue is reproducible in single player with only Forgery installed.
Not tested on server.

No debug.log was provided by the game.

Link to generated crash report:
https://gist.github.com/JoelZBub/e3eeac96041de185433f2ecd41229aa4

Link to latest.log:
https://gist.github.com/JoelZBub/31db08cf7a4ac4db5622080e30762e96

**Comment by SFort** [comment]
set multi line sign paste to banned for now, will look at this later

**Comment by JoelZBub** [comment]
Acceptable workaround for now. thanks
