### ISSUE TITLE
fabrication crash on launch, 1.20.1 with quilt loader 0.20.0-beta.4

### ISSUE THREAD

**Issue by temyy** [FalsehoodMC/Fabrication#623]
https://gist.github.com/temyy/74e8247a934405d466f76462006fbd67

**Comment by SFort** [comment]
I'm just going to release a version that should catch this.
I've got no clue what's causing the actuall confict though so if you could narrow down which mods cause it that'd be great.

**Comment by temyy** [comment]
i went through the mods one by one and it just started working? i did clean some up so i mightve deleted whatever mod was the cause, and whatever it was it also clashed with another mod i have so it might not even be a fault on fabrications side x) thank you though!
