### ISSUE TITLE
Eliminate checks that require you to be fully submerged in the water in order to swim

### ISSUE THREAD

**Issue by moechakucha** [FalsehoodMC/Fabrication#627]
Like how swimming works in old Bedrock Edition versions (prior to 1.14.0).

I don't have an old Bedrock Edition version so I'm not able to replicate it, but I guess this is fairly easy to understand.

**Comment by SFort** [comment]
This is doable but if the server didn't have it enabled aswell (so vanilla).
the jank bellow is the result and i don't really wanna deal with syncing this.

https://github.com/FalsehoodMC/Fabrication/assets/1879846/d2fd1bf8-0e56-44bf-b61a-42d8fc3dfb07
