### ISSUE TITLE
Fabrication settings UI renders at smaller GUI Scale than regular Minecraft UI

### ISSUE THREAD

**Issue by kepstin** [FalsehoodMC/Fabrication#63]
Game log: https://gist.github.com/kepstin/b58f74078def7e94ae3cf484f261383a

Note that in order to reproduce this issue I have modmenu installed, since I don't know of any other way to access Fabrication settings UI.

I have the GUI Scale configured in the Minecraft graphics settings to 2× to achieve a comfortable/readable text size. However, the Fabrication settings UI renders using the 1× font instead, which is unreadably small.

It seems like for alll settings of GUI Scale >1×, Fabrication will instead use a font size one setting smaller:
* 2× scale results in 1× scale in Fabrication settings
* 3× scale results in 2× scale in Fabrication settings
* 4× scale results in 3× scale in Fabrication settings

and in my case, 'auto' is equivalent to 4×.

**Comment by exaskye** [comment]
This is because you have the game running in 4:3 which causes parts of the config screen that was designed for 16:9 to flow off the end of the screen. As a (bad) stopgap solution a while ago I added "scale compensation" that reduces the scale on narrow aspect ratios.

I need to fix this in a more proper way at some point.

**Comment by kepstin** [comment]
Ah, yes, I am playing Minecraft on a 4:3 CRT monitor here.

(I have another computer I use regularly where I play on a rotated widescreen monitor, so 9:16 aspect, but I have not yet installed Fabrication on that computer)

**Comment by exaskye** [comment]
![image](https://user-images.githubusercontent.com/6185037/104779181-7b638380-5733-11eb-8b13-053fc4fd7f90.png)
