### ISSUE TITLE
[Mod Incompatibility] Foliage creepers feature + ETF

### ISSUE THREAD

**Issue by EnderGirl1500** [FalsehoodMC/Fabrication#632]
This is now obvious for me after discovering the issue, and I don't think there would be a possible fix - at least on your side - but Entity Texture Features is incompatible with the `weird_tweaks.extra.foliage_creepers` feature.

When using ETF and turning Foliage Creepers on, the game freezes and you get the "is not responding" pop up.

Maybe aknowledging this in the wiki could help others not needing to spend 4h testing mods hehe

(I assume not only ETF but any other mod that affects entities' appearances, animations, etc., like CEM, would cause the issue as well).

**Comment by SFort** [comment]
In 1.19.3 minecraft changed to using a supplier for textures.
ETF should probably check if the supplier actually has anything before requesting an infinate amount.
will add a fix in fabrication.

please test with [3.3.10](https://github.com/FalsehoodMC/Fabrication/releases/tag/v3.3.10)
