### ISSUE TITLE
Bedrock-like impaling doesn't work right

### ISSUE THREAD

**Issue by GoldenTotem** [FalsehoodMC/Fabrication#634]
Minecraft 1.16.5  Forge 36.2.35  Forgery 3.3.7

1. Bedrock-like impaling only work when you throw it.
For example, open Bedrock-like impaling and then enchant your trident with impaling IV. Summon a creeper in water. If you throw the trident to it, it will take 8+10=18 damage, but if you attack it, it will only take 9 damage.

2. Impaling still work on aquatic mob.
In bedrock edition, impaling only detect whether mob is in water or rain, regardless of it's aquatic mob or not. For example, if a guardian on land, impaling will not work on it.

**Comment by SFort** [comment]
According to una:
1st is a bug (was never implemented)
2nd is intentional
