### ISSUE TITLE
Crawling still working when gui opening

### ISSUE THREAD

**Issue by GoldenTotem** [FalsehoodMC/Fabrication#636]
Minecraft 1.16.5  Forge 36.2.35  Forgery 3.3.7
Most control keys stop working when gui opening, for example, if you open your inventory, pressing shift will not make you sneak. But key of crawling(I set it to alt) still working, it means pressing alt can make you crawl even when you open gui.  
Only include inventory gui, exclude crafting table, chest...

**Comment by SFort** [comment]
Are you running any other mods?
as i'm not getting the issue holding the crawl key while opening inventory makes me stand again

**Comment by GoldenTotem** [comment]
> Are you running any other mods? as i'm not getting the issue holding the crawl key while opening inventory makes me stand again

I tested again with only forgery. The problem still exist. 
I means, you can crawl while opening inventory, this is a problem. Because if you are holding shift, opening inventory will make you stand up and stop sneaking, so opening inventory should make you stand up and stop crawling and you should not crawl until you close inventory.

**Comment by SFort** [comment]
ah i see, i missread the issue to mean "you wont un-crawl when opening inventories" not that "you can crawl while having an inventory open"

**Comment by GoldenTotem** [comment]
> ah i see, i missread the issue to mean "you wont un-crawl when opening inventories" not that "you can crawl while having an inventory open"

yes yes
