### ISSUE TITLE
(Not a request) *I* READ THE CHANGELOGS!

### ISSUE THREAD

**Issue by StygianEmperor** [FalsehoodMC/Fabrication#64]
I don't want to make a Twitch account so I don't know a better means of providing positive feedback: Just need to make sure you know **at least one person reads and very much appreciates changelogs** (and finds it incredibly annoying when mods don't provide them, such as TeamCoFH mods...).

Just started using this mod last night and individually activated almost every feature, thanks!

**Comment by exaskye** [comment]
I've received at least 4 other messages that people read the changelogs, so you're definitely not alone. :P

Thanks, I'm glad you like the mod!
