### ISSUE TITLE
1.20.1 Fabric server Can't keep up

### ISSUE THREAD

**Issue by Zano1999** [FalsehoodMC/Fabrication#642]
With your mod installed, my server has the problem below, I don't know what changed, but when I used it on 1.19.2 this didn't happen.
The problem only seems to appear with more than one player online.

![image](https://github.com/FalsehoodMC/Fabrication/assets/42555362/44612b63-e5e1-4563-8cc1-1c091b1c4377)

Mod list: https://pastebin.com/NEwdQt55
Server latest log: https://pastebin.com/MU21BqQg

**Comment by SFort** [comment]
I'm just gonna guess this is #638 related, please try that if the issue persists,
narrow down exactly which mods cause it please.

**Comment by Zano1999** [comment]
The issue persist

**Comment by SFort** [comment]
>  narrow down exactly which mods cause it please.

it's not feasable for me to look for a performance issue amongst 200 potential conflicts, that may be world dependant
