### ISSUE TITLE
Configurable hyperspeed_furnace_minecart Speed

### ISSUE THREAD

**Issue by StygianEmperor** [FalsehoodMC/Fabrication#65]
Would it be possible to change `hyperspeed_furnace_minecart` to a slider or custom numeric multiplier rather than true/false? I'd like to put furnace minecarts at an intermediate speed.

A more-complicated but possibly-cool option would be to make it interact with `furnace_minecart_any_fuel` in some way - perhaps the longer/shorter the non-coal fuel added would last in a normal furnace, instead it multiplies the minecart's speed by a configurable amount over coal's normal duration?

**Comment by exaskye** [comment]
Features like this one aren't configurable due to the config loader not really being designed for it, and the config screen relatedly not having a slider element available. This needs improving, but so far has been Good Enough.

**Comment by exaskye** [comment]
The only config option right now that isn't just `true`/`unset`/`false` is `general.profile`, and the implementation of that is a mess of special cases.

**Comment by StygianEmperor** [comment]
> The only config option right now that isn't just `true`/`unset`/`false` is `general.profile`, and the implementation of that is a mess of special cases.

Well, there’s the dimensional tools stuff and some others outside the in-game config but I’ll take your meaning to be, ultimately, *“adding a config for this would be more complicated than it’s worth/more complicated than you think,”* which is perfectly understandable.

I’m planning to get into modding beyond what data packs can accomplish eventually, so would it be okay if I just copied some minecart-speed code from Fabrication? I’d definitely give proper credit if I ended up uploading anything.

**Comment by exaskye** [comment]
I'm specifically referring to features.ini; it doesn't really make sense to dedicate an entire ini file to just one tiny feature with a single option.

Fabrication is MIT license; go nuts.

**Comment by StygianEmperor** [comment]
Ah, gotcha. Thanks!

**Comment by exaskye** [comment]
I didn't say I won't add it.

**Comment by exaskye** [comment]
I've received an overwhelming number of feature requests over the week and they are filling up the issue tracker and making it difficult to keep track of what is even going on. I've enabled [Discussions](https://github.com/unascribed/Fabrication/discussions) on the repo as a new location for feature requests. Unfortunately, GitHub has "temporarily" disabled the ability to convert issues to discussions, so I'm closing all feature request issues. However, I'm tracking all the closed issues in a Project board; despite being closed, they're still on my radar on the board. **All new feature requests *must* go to Discussions. Feature requests opened as issues going forward will be closed.**
