### ISSUE TITLE
collision_based_landing_pos is buggy

### ISSUE THREAD

**Issue by SaltSouls** [FalsehoodMC/Fabrication#652]
## Description:
I know that title doesn't say a lot, but it is the best way I can describe the issue here. When sprinting, the particles under the players feet will often times appear at the edges of the block, even if the player is in the center of it. Blocks that update when a player steps on them, redstone ore for example, don't update unless the player walks on the edge of the block. I can confirm that this is a Forgery issue as when removing the mod, the issue goes away.

### Versions:
- MC: 1.20.1
- Forge: 47.2.6
- Forgery: 3.4.0

## Log:
[latest](https://gist.github.com/SaltSouls/d905ba97cd2df245b30f5b4ef4bd0ddb) | [debug](https://gist.github.com/SaltSouls/97928acf1118273f20c5fc4d7e7a9f0d)

**Comment by SFort** [comment]
turn off `minor_mechanics.extra.collision_based_landing_pos` it's a bit of a buggy mess i haven't gotten around to fixing yet

i'm assuming it's that at least i haven't tested

**Comment by SaltSouls** [comment]
> turn off `minor_mechanics.extra.collision_based_landing_pos` it's a bit of a buggy mess i haven't gotten around to fixing yet
> 
> i'm assuming it's that at least i haven't tested

Yup, that seems to have fixed it.
