### ISSUE TITLE
Bug & Feature request

### ISSUE THREAD

**Issue by BioTechproject27** [FalsehoodMC/Fabrication#654]
>Server Only
>
>When adding enchants that would normally not be 
compatible it will instead get added in an inactive state. 
Conflicting enchants can be swapped on the go by right-clicking the 
item or pressing a keybind while sneaking. 
>
>
>Demonstration video: https://unascribed.com/fabrication/swap_conflicting_enchants.mp4
extra.swap_conflicting_enchants=
	
Bug:
	-Enchantments always swap when sneak-using, even if other keybind is set.
	-Also enchantments can't "be swapped on the go by right-clicking the item." Or perhaps this is a misinterpretation and it's supposed to be read like: "Conflicting enchants can be swapped on the go by right-clicking the item while sneaking or pressing a keybind while sneaking."
	
In which case this is a feature request to make sneak-using be replaced by the keybind.
	Also being able to see the other enchantments when e.g. having advanced tooltips enabled would be cool.

**Comment by SFort** [comment]
Added a dark gray tooltip.
Swap conflicing enchants is now scriptable which means it's available in taggable players and can also be configured to a fair degree. for example you can make it work on just rightclick/keybind or require the player to shift and be wet, up to you.

**Comment by BioTechproject27** [comment]
Nice, where can I find documentation on how to do so?

**Comment by SFort** [comment]
for the scripting part [fscript](https://legacy.curseforge.com/minecraft/mc-mods/fscript) needs to be installed.
then a button shows up to toggle only scriptable features and you can just click on them.

(also fscript isn't really made to have no conditions out of the box so for now you can just do something silly like (sneaky; !sneaky), in case you wish to use a script and taggable players simultaniously there's a taggable players codition added by fabrication)

https://github.com/FalsehoodMC/Fabrication/assets/1879846/5f7bef9d-6135-468a-8003-8c9198b3d517
