### ISSUE TITLE
Some kind of Bad type on operand stack crash when using forgery on 1.20.1 neoforge

### ISSUE THREAD

**Issue by YukiRainee** [FalsehoodMC/Fabrication#657]
[Debug.log](https://gist.github.com/Rainee4563/f1498978b7904551a20ed355e1914e57)

[Latest.log](https://gist.github.com/Rainee4563/63d840c7634083b8d5dcee304b41078c)

[Launcher Prism Logs](https://mclo.gs/jL8vwjJ)

1.20.1 Neoforge 47.1.81 

If it's not compatible I do apologize for wasting your time

**Comment by SFort** [comment]
either set `blaze_fertilizer` to banned for now or rollback 1 version
