### ISSUE TITLE
Cartographers infinitely reroll, quickly selling maps 10000+ blocks away

### ISSUE THREAD

**Issue by lumagatto** [FalsehoodMC/Fabrication#661]
With trade rerolling, they maybe should not reroll since it makes cartographers hardly useful, and they are usually needed for many structures (vanilla and modded). Maybe should be a separate option.

**Comment by SFort** [comment]
I have no idea how this functions, so if you could give me a referance to as to why re-rolling causes 10000 distant maps and vanilla doesn't (or modded), i'd apriciate it.

**Comment by lumagatto** [comment]
It doesn't reroll into super distant maps. It's just that every time that it rerolls it rolls a new map for a new structure, which has to be found, which means that every time it has to find a further and further structure.
There is a mod called Shifting Wares that does trade rerolling with this issue in mind, if you are interested. It's explained on their mod page:
> Cartographers can only generate one map of each type, because maps they create are never forgotten by the game, and lock their structures from appearing on other maps. Letting them generate more would cause issues with Daily Rerolls; they could generate a lot of maps that would never be sold, and prevent the player from acquiring maps to the closest structures.

**Comment by SFort** [comment]
there it should allow duplicate maps now. (it was either or spending way to much time figuring out how loot gen refrences work and i don't really like the solution that mod uses since it breaks as soon as you uninstall it)

**Comment by lumagatto** [comment]
> there it should allow duplicate maps now.

does that mean that a cartographer will always locate the nearest structure of the type? If that's the case, I like it.

**Comment by SFort** [comment]
> does that mean that a cartographer will always locate the nearest structure of the type

yup, should do

**Comment by lumagatto** [comment]
I will test if fabrication's resetting trades are compatible with VillagerConfig, but if Shifting Wares breaks everything when uninstalled, I will have to keep it for the duration of this server \*~\*

**Comment by SFort** [comment]
well as i skimmed it at least. (note skimmed, not studied)

Shifting Wares stores the discarded maps and re-cycles them.
so if you go from shifting wares -> vanilla, you'll loose some maps (so not really a hard breakage i was exaggerating)
if you go from shifting wares to the new fabrication patch it should just be nearest always.
