### ISSUE TITLE
Some way of making entities wet (fscript or command)

### ISSUE THREAD

**Issue by lumagatto** [FalsehoodMC/Fabrication#664]

**Comment by SFort** [comment]
.... you want a way to make entities perma / coditionally wet? why?

**Comment by lumagatto** [comment]
Well it could be useful, but it needs tridents to be usable while wet to be useful for my server. So at the moment I don't really need it. Maybe it confuses you why i opened the issues in this order and not in reverse and to be honest i'm not sure why I did it.

To answer your question: there is a special (unique item) trident in my server that i wanted to be able to be used anywhere, because it is supposed to keep you "watery". I had this design before i started using fabrication, but it was just aesthetic.

**Comment by SFort** [comment]
The ordering doesn't confuse me as much as openening this issue after the first one was rejected. as i understand it you're requesting a feature that you won't use...

(p.s. i think you're the 1st person to directly request fscript in a fabrication issue, so neat to see it's getting use (i assume))

**Comment by lumagatto** [comment]
Yeah lol when i opened this I didn't notice you rejected the other, sorry for the confusion, I was playing and talking with friends while making the issues

And yes fscript has a lot of potential, thought currently im using it only for no phantoms (if health is at max) and less clutter (no crosshair if no items in hands)
