### ISSUE TITLE
Balance - Villagers don't sell diamond items

### ISSUE THREAD

**Issue by lumagatto** [FalsehoodMC/Fabrication#666]
Makes sense. Diamond items in trades make obtaining diamond important only for netherite upgrades and armor trims.

**Comment by SFort** [comment]
https://www.curseforge.com/minecraft/mc-mods/data-trades
https://www.curseforge.com/minecraft/mc-mods/custom-villager-trades-fabric
there seam to be plenty of mods that's allow customizing this already.
