### ISSUE TITLE
"*.enviromentally_friendly_creepers" doesn't work with Creeper Overhaul

### ISSUE THREAD

**Issue by Puggicorn** [FalsehoodMC/Fabrication#667]
Tested with Neoforge - 1.20.1

Creeper overhaul - 3.0.1

Forgery - 3.4.0+1.20

**Comment by SFort** [comment]
The feature was never ported to 1.20 forge. which should be visable in ui. (at least it is on the latest version)
![screenshot](https://github.com/FalsehoodMC/Fabrication/assets/1879846/34b76c26-696f-408c-b9a9-0650540ff68a)
