### ISSUE TITLE
Configurable night/cave darkness

### ISSUE THREAD

**Issue by K0-RR** [FalsehoodMC/Fabrication#67]
Would this be possible server-side? An option to change the minimum brightness level for nights (different brightness based on the moon phase would be nice) and a pitch-black option for caves.

**Comment by exaskye** [comment]
> Would this be possible server-side?

No, skylight is calculated by the client.

**Comment by K0-RR** [comment]
Still, could you add this on the client?

**Comment by exaskye** [comment]
Yes, hence not closing it.

**Comment by exaskye** [comment]
I've received an overwhelming number of feature requests over the week and they are filling up the issue tracker and making it difficult to keep track of what is even going on. I've enabled [Discussions](https://github.com/unascribed/Fabrication/discussions) on the repo as a new location for feature requests. Unfortunately, GitHub has "temporarily" disabled the ability to convert issues to discussions, so I'm closing all feature request issues. However, I'm tracking all the closed issues in a Project board; despite being closed, they're still on my radar on the board. **All new feature requests *must* go to Discussions. Feature requests opened as issues going forward will be closed.**
