### ISSUE TITLE
disable_lightning_fire still causes entities to catch fire

### ISSUE THREAD

**Issue by anoomolu** [FalsehoodMC/Fabrication#670]
Most noticeable when ran alongside the creeper ignition tweak. There's not rly any info in the log but I was able to reproduce it with just Fabrication + a few performance mods, none of which affecting gameplay.

https://mclo.gs/FgGhIAM

**Comment by SFort** [comment]
Sometimes it is kindof impossible to tell if something is a defect or a request
(the reason i'm considering it a request is because the original intent behind the feature was to stop houses from buring, which player fires don't do)

**Comment by anoomolu** [comment]
That’s fair, I was on the fence because the description seemed to only mention block fire ^^
