### ISSUE TITLE
server doesn't have fabrication??

### ISSUE THREAD

**Issue by rvaem** [FalsehoodMC/Fabrication#671]
Hello!

I'm new to opening issues so I dont know if this is the correct label ..

My friends and I have downloaded Fabrication for our server. We have installed the mod on the server and locally on our files. Client-wise it works, but server-wise it doesn't. 

It says "This server doesn't have Fabrication. Changes will apply to the CLIENT." in the config GUI accessed through Mod Menu. 
 
Is there a fix for this? Any help would be gladly appreciated.

**Comment by SFort** [comment]
i just checked and looks like fabrication is working fine.
try and see if the "/fabrication" command is there when connected to the server.
if it's not you probably didn't install the mod or maybe didn't reboot the server after installing it.
