### ISSUE TITLE
Adjust position of map ID / consistency between annotations on items

### ISSUE THREAD

**Issue by anoomolu** [FalsehoodMC/Fabrication#676]
The bottom right number on an item is almost always used to show number of items in a stack, and with the map ID tweak enabled, it seems like you have a stack of 3 maps in one slot.
![image](https://github.com/FalsehoodMC/Fabrication/assets/77850233/dc13ea43-a5d1-4b54-ba14-01a7472d4a88)

Since the important enchant label is in the top left of an item slot, enchanted book is in the bottom left and bee count is in the top right, I'm not sure which corner would be appropriate - maybe the position of all the info on items should be consistent? My vote would be for the top left.

Thanks for the quick responses to issues! I hope you have a lovely new year.

**Comment by SFort** [comment]
Position has been changed to right top n a happy new year to you too.
