### ISSUE TITLE
Crashes with "End's Phantasm"

### ISSUE THREAD

**Issue by Anewri32** [FalsehoodMC/Fabrication#679]
The game crashes when trying to start it, the registry indicates that it has to do with "Moonlight" and although removing this mod the problem is solved, it turns out that in a new instance with "Fabrication" and "Moonlight" both work in harmony which could indicate that the error is produced by another mod that intervenes but I don't know what it is.

Full log: Deleted, see log below

If you need more information let me know, this problem is present from version 3.4.5 to the current 3.4.8 (probably also crashed in previous versions) for fabric modloader 0.15.3 minecraft version 1.20.1

**Comment by Anewri32** [comment]
Sorry, I did find the mod, it's called "End`s Phantoms", I created a separate instance with these and the result was the same, here is the full log: https://mclo.gs/pgTOaAk

**Comment by SFort** [comment]
`no_dinnerlava` causes this, set it to "banned" for now and it should work

**Comment by Anewri32** [comment]
It works, it doesn't crash anymore.

**Comment by SFort** [comment]
no_dinnerlava will be removed from 1.19.3 onwards
