### ISSUE TITLE
Utility - Yeet recipes is borked

### ISSUE THREAD

**Issue by anoomolu** [FalsehoodMC/Fabrication#681]
Seems like disabling recipes via the json doesn't actually disable them. I put the following in the yeet_recipes.ini:

[minecraft:]
crafting_table=true

The in-game result after restarting:
![image](https://github.com/FalsehoodMC/Fabrication/assets/77850233/9a7a1798-ba80-40d3-ba67-e447cd40c5dc)

Using Fabrication 3.4.8+1.20.

**Comment by SFort** [comment]
Tried on 1.18, 1.20, 1.20.4. Please try to narrow down what causes it.
(maybe you don't have the feature turned on?)

**Comment by anoomolu** [comment]
Never mind, I'm not sure what the issue was but regenerating the .ini file and rewriting the recipes seemed to do the job. Sorry for the false alarm.

fwiw I definitely had the feature on and the formatting seemed fine, I think it might have been that I placed some recipes within the commented out lines?
