### ISSUE TITLE
How to make the configs apply to every world?

### ISSUE THREAD

**Issue by mxnmnm** [FalsehoodMC/Fabrication#683]
I tried setting the configs but they apply only to the client and I was wondering if there is a way to apply the server-side configs automatically to a new world. Forgery has its own folder in the world file so I can't put in default configs, so is there some other way or something I'm missing? Or is it just not an option?

**Comment by SFort** [comment]
you can copy .minecraft/config/forgery to server/config/forgery.
or when on the server click configure server in the top right.

the world settings are just a bit of a bonus, you can just ignore them and stick to the default ones in the config folder. (or use the ui while on the server)

**Comment by mxnmnm** [comment]
What about in newly created singleplayer worlds?

**Comment by SFort** [comment]
Sorry i got a bit confused about what was being asked. (and i might still be?)

In Vanilla terms the features are by default like keybinds and not gamerules.

When you open the ui and configure what features you want those settings will apply to all old / new worlds on your client.

Settings are not saved to the world by default, but to the client.
(You can change it so their saved to world or server, but by default it's for the entire client for all worlds)

https://github.com/FalsehoodMC/Fabrication/assets/1879846/468008b9-843f-430c-a21d-d81562256e89

the settings are saved in
- `.minecraft/config/forgery` by default on the client.
- `.minecraft/saves/world/forgery` if you chose to save it to a world.
- `server/config/forgery` by default on the server.

It's all the same config that you can trasfer if you like

**Comment by mxnmnm** [comment]
Ok so my question is for .minecraft/saves/world/forgery every time I make a world this ends up being reset, is there a way to make it so that isn't the case (like a default template sorta like how the defaultconfigs folder works aka moving the configs from the save into that folder and new worlds end up being made with the new settings)? If I use it on a server ik it'll automatically be setup (based on what you're saying) but what about singleplayer worlds? It's kinda annoying to have to redo the configs and if I want to release my pack it doesn't make sense to have people mess around with the configs.

**Comment by SFort** [comment]
you can just ignore word settings, especially when making a pack.
because world settings all default to unset.
so if i load a new world it will be 

`.minecraft/config/forgery`: `crunchy_cake` = `true`
`.minecraft/saves/world/forgery`: `crunchy_cake` = `unset`

and crunchy cake will be on in every world.
only when you change world settings do they actually effect the game, if you don't touch them it uses the global client value.

**Comment by mxnmnm** [comment]
Ohhhhh, I thought client was client only and had no impact on the world setting. Ok ty

**Comment by SFort** [comment]
also once you're done making a pack i'd recommend limit_runtime_configs since fabrication has a silly amount of features and it'll prevent unused ones from loading
