### ISSUE TITLE
End Portal Parallax for Forge

### ISSUE THREAD

**Issue by mxnmnm** [FalsehoodMC/Fabrication#684]
I see that this feature isn't ported on forge/neoforge but it seems someone else has this feature (of course they don't have it for 1.20.1 -_-) but hopefully this would make it easier to port especially because it's mit license as well so yea

**Comment by mxnmnm** [comment]
https://www.curseforge.com/minecraft/mc-mods/end-portal-parallax

**Comment by SFort** [comment]
Dear god...
 @unascribed you might wanna see this, not certain but i think  someone actually managed to rewrite it as a shader.
amazing.

**Comment by SFort** [comment]
The shader you linked has an issues on some versions that i'm not up to fixing and i really don't want to use diffrent  backends for this feature in particular
