### ISSUE TITLE
Faster Obsidian - make items taggable?

### ISSUE THREAD

**Issue by anoomolu** [FalsehoodMC/Fabrication#686]
It might be nice to make this feature data-driven, so players/packmakers can add modded blocks to the existing set of blocks that are mined faster. For my use case, I've made end portal frames breakable with a pickaxe, and their recipe includes obsidian and so would probably benefit from the tweak.

Alternatively, the tweak could just apply to items in the _needs_diamond_tool_ block tag.

**Comment by SFort** [comment]
faster obsidian is one of those hacks that probably shouldn't have been added and i really don't want to expand on it.
