### ISSUE TITLE
Not ported features to 1.20.1?

### ISSUE THREAD

**Issue by Aceplante** [FalsehoodMC/Fabrication#689]
Title, there are a few such as interrupting damage, and sinking in falling liquids that I would love to see on the latest version

**Comment by SFort** [comment]
I think these might of never been ported to forge on any version.
and i won't get to it unless i suddenly get lots of time, sorry.

**Comment by Aceplante** [comment]
Both of them definitely were on forge in 1.19.2 and 1.18.2 respectively, but fair enough thank you

**Comment by SFort** [comment]
checked 1.19.2/1.18.2 neither have interrupting damage?
i mean it's possible i ported it forgot and tagged it as not ported at some point but i doubt it
