### ISSUE TITLE
WOINA - 1.8-style natural regeneration

### ISSUE THREAD

**Issue by anoomolu** [FalsehoodMC/Fabrication#696]
Hiya. One mechanic I find myself missing is the older style of health regeneration, 1 point every 4 seconds. From 1.9 onwards, high-saturation foods act like regen potions - holding a golden carrot in hand with Appleskin enabled shows at least half the healthbar being quickly restorable. fwiw I'm on Fabric 1.20.1

I wonder if it'd be possible to have a tweak for enabling this.

**Comment by SFort** [comment]
https://legacy.curseforge.com/minecraft/mc-mods/good-ol-regen
this is one of those features that is really nice with a detailed config something fabrication isn''t good at doing atm so for now it's not getting  merged.

**Comment by anoomolu** [comment]
Makes sense, thanks for the link ^^
