### ISSUE TITLE
serverside waterlogging/waterbucketing, shooting arrows, etc instead of client? atleast please give an option to turn it off.

### ISSUE THREAD

**Issue by ReapDaReaper** [FalsehoodMC/Fabrication#697]
me and my friend had a delay on aternos and before we imported forgery into our world everything was fine and my friend could water bucket jump. but after I imported the forgery mod everything clientside is delayed as if it was now serversided. could it be possible to add a config tag to turn that back into clientside?

**Comment by SFort** [comment]
something is probably just screwing with performance? forgery has a silly amount of features and not all of them very optimal.
features like `entities_sink_in_falling_fluids`,`collision_based_landing_pos` probably being at fault.
also should enable `general.limit_runtime_configs`
could also be that you have `balance.extra.velocity_based_fall_damage_reset` on which would prevent water bucket jumping.

**Comment by SFort** [comment]
i'm just going to assume that was it.
