### ISSUE TITLE
Modern textures that don't downgrade to match Programmer Art

### ISSUE THREAD

**Issue by saltyseadoggo** [FalsehoodMC/Fabrication#70]
While I don't use it personally, I know that some fans of the pre-Jappa textures who use the vanilla *Programmer Art* resource pack were a bit miffed when Mojang said that they wouldn't be "downgrading" textures such as the honey bottle, crimson and warped nylium, Nether gold ore or the respawn anchor to match the old textures for this resource pack. This has led to packs such as [this one](https://www.curseforge.com/minecraft/texture-packs/programmer-art-fix) attempting to fix these issues. I thought that you might like to include similar fixes in Fabrication/Forgery.

Exactly which textures you wish to add downgrades for is, of course, up to your discretion, and you can look at the above pack to see all of the issues that its dev has taken; they seem to be pretty thorough.

This is a disclaimer that I honestly dislike the old textures and do not use the Programmer Art pack. I simply thought that I would bring this up if you were interested in it for WOINA.

**Comment by exaskye** [comment]
I don't use or care for the Programmer Art pack either and it's probably not worth the work to implement this if others have already made resource packs to fix this.
