### ISSUE TITLE
Unknown incompatibility with shields

### ISSUE THREAD

**Issue by Barerock** [FalsehoodMC/Fabrication#701]
![image](https://github.com/FalsehoodMC/Fabrication/assets/38869993/706a8597-1ddd-473f-9a14-5cf27549b777)
Items are invisible in the hotbar, but not in the inventory
![image](https://github.com/FalsehoodMC/Fabrication/assets/38869993/c318ea92-3902-4a05-b1f9-a6bcba03056c)

This isn't linked to MB-3D, the 3D items pack I have on, only the HUD and UI resource pack.
When mod is removed items show normally and when the resource pack is removed items show up, but not normally.
![image](https://github.com/FalsehoodMC/Fabrication/assets/38869993/67b6c7c7-85d2-48ae-95b0-cf01d415ddde)

Items are weirdly transparent. I've looked through the obvious inventory modifications from this mod and tested each, but none seem to change this behavior, so my entire config profile is loaded right now.

I used a test profile to load my mods 10 by 10 and reached the end of the list without replicating the issue. Shaders are on in that profile as well. I've disabled all my resource packs too. Issue is still present in the survival instance. I also copied over my config folder to replicate settings that may cause this.

**Comment by Barerock** [comment]
Latest log for original instance: 
[latest.log](https://github.com/FalsehoodMC/Fabrication/files/14565086/latest.log)

Latest log for test instance:
[latest.log](https://github.com/FalsehoodMC/Fabrication/files/14565091/latest.log)

There are many mods loaded, but I just couldn't reproduce the issue at all.

**Comment by Barerock** [comment]
If I copy my testing world over to the test profile the same issue occurs. So there's something wrong with the world I guess. Making a NEW world with all mods loaded eliminates the issue. Time to pinpoint what is wrong with the other world I guess.

**Comment by Barerock** [comment]
HOLDING A SHIELD!
![image](https://github.com/FalsehoodMC/Fabrication/assets/38869993/aa5fff4b-39fe-4fbc-9791-3c9024df2227)

Specifically THIS one. I will test further.

**Comment by Barerock** [comment]
Shields with banners on them turn invisible on the hotbar, and if equipped they turn all tools invisible. This takes the form of weird transparency issues on the hotbar. I will test a couple mods now.

**Comment by Barerock** [comment]
Definitely a mod incompatibility, this doesn't occur with no other mods. Continue testing. It is immediately apparent that disabling full res banner shields fixes this. I know it would be convenient for you to know what mod this is incompatible with, but I've been doing this for 2.5 hours now and I'm kinda sick of it. Lemme know if you want me to continue testing.

I did already test "Combat Nouveau," which implements shield mechanic changes. It doesn't affect this issue on/off.

**Comment by SFort** [comment]
I can't reasonably debug an incompatability with 266 mods.
Currently i'm also fairly limited on time. this probably won't see a fix anytime soon.
Even if i did know what causes it, forgery defects tend to just be bit much to make time for atm, sorry.
still try to make time for fabrication defects so if this is one it'll at least be higher priority.

**Comment by SFort** [comment]
please re-open if you findout what's causing it
