### ISSUE TITLE
Some quirks with No Hunger tweak

### ISSUE THREAD

**Issue by anoomolu** [FalsehoodMC/Fabrication#705]
Hiya, hope you're doing well.

I've encountered what I believe are two bugs related to the No Hunger tweak. First found on Forgery 1.16, also had it happen on Fabrication 1.19.2:

- Some low quality foods don't heal any hunger (Pufferfish, Tropical Fish, Dried Kelp, Potatoes), as well as Cake for some reason.
- The hunger bar isn't hidden, unlike the No Experience tweak where the bar is usually hidden. Not sure if this is expected behaviour.

Log: https://mclo.gs/nKjuqkI

edit: loosely related, but I wonder if Fabrication/Forgery could hook into Appleskin to make it display the correct healing values when the tweak is enabled.

**Comment by SFort** [comment]
i guess the bar _could_ be hidden as an enchancment? but some of those foods would just be silly if there was a minimum health given.

**Comment by SFort** [comment]
Actually nvm, hunger hurts you so it's still usefull as an indicator

**Comment by anoomolu** [comment]
Bit of a shame that Cake is made a bit useless by the tweak but I get the rationale, cheers for the quick response.

**Comment by SFort** [comment]
> edit: loosely related, but I wonder if Fabrication/Forgery could hook into Appleskin to make it display the correct healing values when the tweak is enabled.

if you really want to you can make a feature request but currently i'm really sticking to only making time for fabrication defects / severe forgery defects

i haven't checked but it might give you a fraction of a health point? did you try eating alot

**Comment by anoomolu** [comment]
Tried eating a few in a row and no health increase, it's strange because cookies have the exact same stats but restore 1/2 a heart, so maybe it's the fact that cake isn't eaten in the conventional manner?

re. the feature request I'll probably leave it for another time, I've made too many already 😭 sorry

**Comment by SFort** [comment]
i would like to see those feature requests comlpeated, but honestly what little dev time i have i'd like to put into making a game. i've been told that this is a pretty standard minecraft mod developer lifecycle.
