### ISSUE TITLE
"Invincible" item_despawn.ini tag bug in 3.4.11 is worse than before

### ISSUE THREAD

**Issue by Abalieno** [FalsehoodMC/Fabrication#709]
As written here (and documented extensively on discord, since this took me several hours to troubleshoot to this point):
https://github.com/FalsehoodMC/Fabrication/commit/6d468f81aff74e3aa53857dae49fd8bc5b3e10db

Obviously -32 - -64 = +32

I tagged amethyst shards to use the "forever" feature and noticed they didn't drop. Long story short, they did drop, but as long a cluster was below y = 32, then the drop would only appear at y = 1

That's what the code does.

If that piece of code is meant to port back to y = 1 those items that fall 32 blocks UNDER bedrock, then at the very least it should be -32 + world.getBottomY()

Because being world bottom negative, the subtraction makes the result positive, rather than being added to negative.

**Comment by SFort** [comment]
sorry

**Comment by Abalieno** [comment]
Could you publish on CF? I need to be able to distribute the fix (and test it, even if it seems fine).

**Comment by SFort** [comment]
I just realized that the really item should teleport to -63 and not to 1 so expect another release
