### ISSUE TITLE
Conflict with Obfuscate

### ISSUE THREAD

**Issue by WenXin20** [FalsehoodMC/Fabrication#71]
`Forgery v1.2.11_01`
`Minecraft v1.16.4`
`Forge v35.1.37`

The game crashed on launch with my modpack. The debug log was not created, but I've provided the latest.log. It looks like it may be an incompatibility with ~Sophisticated Backpacks~ [Obfuscate](https://www.curseforge.com/minecraft/mc-mods/obfuscate).
[Crash Report](https://gist.github.com/WenXin20/166b19796259d5654d973f7f6747959a)
[Latest Log](https://gist.github.com/WenXin20/f96e044b70a72115d00c6455adde059c)

**Comment by exaskye** [comment]
This is actually a conflict with Obfuscate. It's odd that my mixin error handling stuff can't catch Redirect conflicts.

**Comment by exaskye** [comment]
It can't catch Redirect conflicts and most other kinds of conflicts because they're considered a "critical injection failure" and don't notify error handlers. Grr..
