### ISSUE TITLE
Strange Graphical Error

### ISSUE THREAD

**Issue by AnomalousLad** [FalsehoodMC/Fabrication#711]
[debug log](https://gist.github.com/AnomalousLad/49fde5a2f462d4a576eb4a85782b8424)

After clicking on anything in the in-game mod menu (the one accessible from the Mods tab on the menu) at all, almost all text in both the mod menu as well as the game itself become scratchy and low-resolution. Sometimes it resolves itself seemingly at random, other times it takes closing the game entirely to fix it. Regardless, this makes navigating the mod menu somewhat irritating to the eyes.

![Screenshot (6)](https://github.com/FalsehoodMC/Fabrication/assets/168119824/80c83f1f-984f-4865-832f-4c8a950b678a)

**Comment by SFort** [comment]
are you using optifine?

**Comment by SFort** [comment]
just realized you posted a log.
ye it's optifine

**Comment by AnomalousLad** [comment]
Yes. Does Optifine always cause this issue, or is there a way to fix this on my end?

**Comment by SFort** [comment]
i have no idea. i've noticed it when testing forgery ages ago. but Una policy was no touch optifine issues (persumably because their all a nightmare to deal with). and considering i'm much worse at render code i fully support it.

sorry, you could try optifine dev i guess?

**Comment by AnomalousLad** [comment]
It's all fine, no need to apologize. I'm using the latest Optifine version for MC 1.20.1, so presumably there's not much I can do. If it's ok to ask here, do you know any alternatives that'd let me use Complementary Shaders?

**Comment by SFort** [comment]
looks like iris/sodium ports for forge exist and are called oculus and rubidium. so try those i guess? not up to date on the current mc stuff though, just figured out 1.20.5 exists looking for an iris port.
