### ISSUE TITLE
Incompatible with Dangerclose on the latest 1.19.2 forge ver of DangerClose

### ISSUE THREAD

**Issue by SoimuBadass** [FalsehoodMC/Fabrication#716]
Incompatible with Dangerclose on the latest 1.19.2 forge ver of DangerClose because campfire priority when liting entities.

Still crashes when disabling the feature in forgery confing.

https://gist.github.com/SoimuBadass/b20f5344215f2241ab2678ff43f4111a

**Comment by SFort** [comment]
features still load when disabled you have to ban them or have limit runtime configs on.

I just tested it and dangerclose and forgery aren't in conflict, also at a quick glance dangerclose really dosn't do anything that would cause this.

this crash really should never happen the feature should just get automaticly disabled.
please narrow down what mod forgery is conflicting with. i cannot reasonably download and debug 170 mods

**Comment by SFort** [comment]
please re-open if you findout what's causing it
