### ISSUE TITLE
New enchantments.

### ISSUE THREAD

**Issue by K0-RR** [FalsehoodMC/Fabrication#72]
- BAD
<details>

[Chestplate] **Discomfort** - reduces the amount of air that can fit in the lungs.
[Leggings] **Impediment** - slows user in water.
[Pickaxe] [Axe] **Fumbling**/**Inefficiency** - causes the tool to mine blocks slower.
[Bow] **Clumsy**/**Slippery** **Fingers** - increases the bow charge time.
[Weapon] **Curse of Dullness** / **Dullness** - lowers the damage.
[Any] **Curse of Fragility** - causes the durability of the item to deplete faster, by making it lose one more level of durability every third/fifth use.
[Any] **Curse of Obedience** / **Binding** - binds itself to the first user that holds it. Prevents everyone else from using it.
[Helmet] **Curse of Echos** - causes the wearer to hallucinate the sounds of random hostile mobs.
[Helmet] **Curse of Blindness** - lowers the vision of the user.
[Any] **Curse of Ruin** - prevents items from being repaired in an anvil.
[Weapon] **Curse of Clearing** - a small chance to vanish other enchantment when the tool is used.
[Pickaxe] **Curse of Distraction** - a chance to cancel the block mining process.
[Weapon] **Curse of Duality** / **Daintiness** - damages alive mobs/players like normal but heals undead.
[Armor] **Curse of Illness** - disables natural health regeneration when equipped.
[Armor] **Curse of Hostility** - makes wolves, llamas, and spiders attack you in the daytime, makes mobs target you from twice as far.
[Sword] **Flint and Steel** - causes creepers to explode when hit.
</details>

 - GOOD
<details>

[Weapon] **Disarm** - a chance that a mob/player struck with it will drop their weapon.
[Weapon] **Critical hit** - higher critical damage.
[Weapon] **Bane of Endermen** - similar to Bane of Arthropods - deals additional damage to the Endermen.
[Weapon] **Heavy weight** - reduces attack speed.
[Weapon] **Weaken** - a chance to apply weakness effect lasting 40/60/80 ticks.
[Axe] **Combo** - increases damage with each successful strike, resets if it hits air or blocks.
[Axe] **Beheading** -  a chance to get a mob's/player's head after the kill.
[Sword] **Paralysis** - mob/player struck with it will be unable to move, jump or attack for 1 second.
[Sword] **Lightning Strike** - a small chance to summon lightning.
[Bow] [Crossbow] **True Shot** - arrows will not be affected by gravity.
[Bow] **Quick Draw** - decreases the bow charge time.
[Bow] [Crossbow] **Homing**/**Magnetism** - arrows will bend the trajectory towards the mob/player pointed by the cursor when firing.
[Bow] [Crossbow] **Exploding** - arrows create a small explosion on contact with a mob/player/block, too weak to destroy blocks.
[Armor] **Deflect** - a chance to deflect arrows.
[Helmet] **Skylight**/**Emmissive** - wearer glows (low level of light)
[Fishing rod] **Snatching**/**Hitch** - a chance to pull off a piece of the armor of whatever mob/player it hit.
[Shears] **Precision** - unbreaking for shears (needs to be checked if you can enchant shears with unbreaking first coz idk)
</details>

- Extra
 <details>

-Changes to the Infinity enchantment -  each arrow has a 30/50/70% chance to not disappear.
-Make Crossbows accept Flame, Power, Infinity enchantments.
-Make Shields accept Thorns enchantment.
</details>

Some of them need a better name. Also, I can provide Polish translations for these names.

**Comment by exaskye** [comment]
This requires implementing a server-side only enchant system, which I already would like to do to add some of my own custom enchants, but is a lot of work.

**Comment by exaskye** [comment]
I've received an overwhelming number of feature requests over the week and they are filling up the issue tracker and making it difficult to keep track of what is even going on. I've enabled [Discussions](https://github.com/unascribed/Fabrication/discussions) on the repo as a new location for feature requests. Unfortunately, GitHub has "temporarily" disabled the ability to convert issues to discussions, so I'm closing all feature request issues. However, I'm tracking all the closed issues in a Project board; despite being closed, they're still on my radar on the board. **All new feature requests *must* go to Discussions. Feature requests opened as issues going forward will be closed.**
