### ISSUE TITLE
not understanding client / server config

### ISSUE THREAD

**Issue by QwertRvg** [FalsehoodMC/Fabrication#720]
I am creating a modpack and have changed the setting of every single config option: either banning them or enabling them.
But the Client / Server thing does confuse me.
I wanna make sure that when someone plays my modpack, that every world uses the exact settings that I have set-up, how do I make sure of that?

**Comment by SFort** [comment]
Client are settings that are across all worlds on the the minecraft instance you're running.
Server settings are the settings of a dedicated server. 
World settings only show when you're in a singleplayer world and only apply to that world.

So when creating a modpack just set the client settings and then copy over `configs/fabrication` if on fabrication or `configs/forgery` if on forgery.
to the dedicated server if you're playing multiplayer.  (or if releasing a seperate dedicated server pack)

I've really only used tools i made for making modpacks, so not certain how it functions with whatever you're using.
But i assume that you don't need to make a seperate server pack.
So just set the settings on the client

**Comment by QwertRvg** [comment]
okay but some config options are client only while some also need to be enabled on the world, right?
i want those world configs to be default configs

for other mods the "server" config is the world config and in forge can be put into the 'defaultconfig' folder, to get auto-applied to every new world

i would like to do the same with forgery but am very confused on how to do it

**Comment by SFort** [comment]
anything in `configs/forgery` applies to every world.

when making a pack you can ignore the right top "client/server/world" and just use "client".
it will save both client-side and server-side features in `configs/forgery` which i assume you will move to `defaultconfig/forgery`.


the button in the top right has nothing todo with what kind of features you are editing but where they are being edited.
so if i host a server on my pc, and you run minecraft on your pc.
you click multiplayer and connect to my server.
only now the button in the right top is usefull.
if it's set to "client" it will read / save the configs on your pc.
if it's set to "server" it will read / save the configs on my pc.

**Comment by QwertRvg** [comment]
alright, thanks a lot for clearing that up
i did the entire config while client was selected
so i just move that to defaultconfig then?

**Comment by SFort** [comment]
ye
