### ISSUE TITLE
Deja void - falling with a mount instakills when teleported back to land

### ISSUE THREAD

**Issue by anoomolu** [FalsehoodMC/Fabrication#726]
Hiya. Bit of a weird one - with _deja void_ enabled, falling into the void while on a mount (e.g. minecart or horse) leads to the player dying when they are teleported back to safe land, even if they were full health to start. Might be to do with the y-offset of the player when on something. Not a problem if this is too niche to bother fixing.

Log: https://mclo.gs/EQL1Thv

To reproduce, use default Fabrication config with deja void enabled, and ride off the edge of a platform into the void with a minecart, boat or horse.

**Comment by SFort** [comment]
i couldn't reproduce the bug. (tried on 1.18/1.20.1)
but the player movement not being tracked when in a vehicle is a bug. and maybe fixing it will fix this aswell
i'll just give you a version to test in 30 ish min i have to go and do something then i'll finnish merging the patch across the branches

**Comment by SFort** [comment]
[3.4.19.zip](https://github.com/user-attachments/files/16767722/3.4.19.zip)

**Comment by anoomolu** [comment]
Will try in a sec.

Boat seems fine, horse and minecart still cause player to glitch out on rewind causing death. Tested on 1.20.1 using the void world superflat preset, which is at y=-60 if that affects anything.

**Comment by SFort** [comment]
ok, couldn't do it with the minecart but, managed with the horse

**Comment by SFort** [comment]
[test.zip](https://github.com/user-attachments/files/16770380/test.zip)
just in case please check with the new patch and then i'll do a release

**Comment by anoomolu** [comment]
Works perfectly, thanks!
