### ISSUE TITLE
Forgery 3.4.19 Crashing with mods

### ISSUE THREAD

**Issue by mxnmnm** [FalsehoodMC/Fabrication#727]
When using the replay mod with sinytra connector and forgery 3.4.19 I get crashes. This does not happen with forgery 3.4.18 

Here is the debug log: https://gist.github.com/mxnmnm/bcbde41406b842be5d6f9eb63933508b

**Comment by SFort** [comment]
i have no idea so far what would cause that.
try setting fixes > fix_dragon_egg_trails to banned ??

**Comment by mxnmnm** [comment]
ok that fixed it

**Comment by mxnmnm** [comment]
I'll still leave this open in-case there is some fix you wanna put in so the feature can be used otherwise you can just close this issue

**Comment by SFort** [comment]
i'm just gonna disable the feature on forgery...
i'm really not enthused for a forgery debug session
