### ISSUE TITLE
No Hunger - hide hunger bar

### ISSUE THREAD

**Issue by anoomolu** [FalsehoodMC/Fabrication#730]
Hiya. I noticed that receiving the Hunger effect when the No Hunger tweak is enabled causes the bar to completely empty, which is probably by design to cause starvation damage. However, it feels a little odd for the entire bar to just get obliterated upon eating Rotten Flesh or the like, so I wanted to suggest hiding the hunger bar completely if the tweak is enabled.

The hunger effect is conveyed clearly enough by the potion effect icon imo so it's not an issue of clarity - having the bar despite the mechanic being pretty much disabled seems like clutter. [Hearty Meals](https://modrinth.com/mod/hearty-meals) seems to solve this nicely by moving around bars.  Just wanted to mention also that upon clearing the Hunger effect, the hunger bar doesn't go back to full, which seems to go against what the tweak name implies.

![image](https://github.com/user-attachments/assets/0138dc26-75cb-4db0-af05-0e399f2b5453)
![image](https://github.com/user-attachments/assets/8d4119c6-009b-442d-a0ae-df8c8293f732)

**Comment by SFort** [comment]
the hunger bar in only full if you have full health.

**Comment by anoomolu** [comment]
Just for anyone else reading, [Better Hunger](https://legacy.curseforge.com/minecraft/mc-mods/better-hunger) works great with this to hide the food bar and move the bubble bar down to replace it.
