### ISSUE TITLE
Sleeping - health and hunger mechanics.

### ISSUE THREAD

**Issue by K0-RR** [FalsehoodMC/Fabrication#74]
Sleeping in bed decreases hunger by 8 levels (out of 20 - 4 icons). You can't sleep if your hunger is below 8 levels.
Sleeping removes any status effects from the player. Sleeping with hunger at level 18 or more regenerates two hearts.

**Comment by exaskye** [comment]
I've received an overwhelming number of feature requests over the week and they are filling up the issue tracker and making it difficult to keep track of what is even going on. I've enabled [Discussions](https://github.com/unascribed/Fabrication/discussions) on the repo as a new location for feature requests. Unfortunately, GitHub has "temporarily" disabled the ability to convert issues to discussions, so I'm closing all feature request issues. However, I'm tracking all the closed issues in a Project board; despite being closed, they're still on my radar on the board. **All new feature requests *must* go to Discussions. Feature requests opened as issues going forward will be closed.**
