### ISSUE TITLE
[1.16.5 Bug] DropMoreExperienceonDeath works wrong

### ISSUE THREAD

**Issue by GoldenTotem** [FalsehoodMC/Fabrication#740]
Minecraft 1.16.5  Forge 36.2.35  Mod 3.4.19

Player will get 1 xp less than expected.

1. Enable DropMoreExperienceonDeath.
2. Run command `/xp add @s 10000` `/kill` 
3. PIck up all exp orbs, and run command `/data get entity @s XpTotal`

Player will have 7999 xp, not 10000*0.8=8000.

**Comment by SFort** [comment]
i think you may be checking score which is not the same, i'm pretty sure the xp is correct. either way though code isn't getting changed

**Comment by GoldenTotem** [comment]
> i think you may be checking score which is not the same, i'm pretty sure the xp is correct. either way though code isn't getting changed

I don't think I made a mistake, the Xptotal nbt of player do shows the how much xp a player have. I guess maybe the floor function of xp cause this problem.
