### ISSUE TITLE
Collision Based Landing Pos doesn't work with the velocity multiplier of blocks

### ISSUE THREAD

**Issue by GoldenTotem** [FalsehoodMC/Fabrication#742]
Minecraft 1.16.5 Forge 36.2.35 Mod 3.4.19

Collision Based Landing Pos only affect slime block. If you stand on the edge of ice, honey block, soul sand. The movement of player will act like normal block.

**Comment by SFort** [comment]
works with magma blocks.
this is probably something bugged with the may walk velocity interacts with blocks specificly
