### ISSUE TITLE
server crash

### ISSUE THREAD

**Issue by scamish76** [FalsehoodMC/Fabrication#743]
server crashes with Fabrication installed. no other mods, resourcepacks, or shaderpacks installed. Fabric api, and fabrication on both the client and the server. 

Fabric 1.21 with loader 0.16.9 (also tried 0.16.7).
fabrication 3.5.1 (3.5.0 crashes also)

[client-latest.log](https://github.com/user-attachments/files/17792118/client-latest.log)
[server-latest.log](https://github.com/user-attachments/files/17792119/server-latest.log)

**Comment by SFort** [comment]
setting ping_privacy to banned in the configs will probably fix this for now

**Comment by scamish76** [comment]
That did the trick. Thank you for the quick response. I appreciate you.
