### ISSUE TITLE
1.21.2+ support

### ISSUE THREAD

**Issue by nenamoree9** [FalsehoodMC/Fabrication#752]
So fabrication wasn't updated for 1 month already and 1.21.2, 1.21.3, and 1.21.4 has released since then. So maybe you can add 1.21.2+ support in the next update if you're still updating it then.

**Comment by SFort** [comment]
No i'm not doing ports

if you want you can get the standard disgruntled modder rant about mojang. i'm not happy to say it. but my annoyance of mojang has surpassed my wish to keep projects i like going*.

if someone opens a pr, like unilock did for 1.21, i'll gladly help.

\* - on minecraft
