### ISSUE TITLE
"Instant Pickup" does not activate when breaking top block of tall flowers

### ISSUE THREAD

**Issue by Abbie5** [FalsehoodMC/Fabrication#753]
https://gist.github.com/Abbie5/63b10462f9ce6be28ce9270a3db5d8aa

**Comment by SFort** [comment]
So... the topblock techincly doesn't drop anythting, but since the top block is gone. the bottom block breaks itself.
... therefore technicly the player doesn't break anything that drops items.

fantastic

**Comment by Abbie5** [comment]
Why wontfix?

**Comment by SFort** [comment]
mainly because every way i thought of fixing this was extreamly hacky and may cause bigger issues.

also this is a defect of minecraft. for instance a datapack that makes fortune work on flowers would have this exact same issue.
