### ISSUE TITLE
Fixes for cauldrons.

### ISSUE THREAD

**Issue by K0-RR** [FalsehoodMC/Fabrication#77]
Cauldrons can't be filled with water in the Nether.
Falling into a water-filled cauldron will save you from fall damage just like normal water.
Should contain a fix for water in cauldrons rendering as opaque - make water render as translucent as intended

I not sure if this counts as bulk requests in one issue. If you consider it as three in one then I'm sorry, you can close it and I will make it separate. Also, do I open too many feature requests?

**Comment by exaskye** [comment]
I've received an overwhelming number of feature requests over the week and they are filling up the issue tracker and making it difficult to keep track of what is even going on. I've enabled [Discussions](https://github.com/unascribed/Fabrication/discussions) on the repo as a new location for feature requests. Unfortunately, GitHub has "temporarily" disabled the ability to convert issues to discussions, so I'm closing all feature request issues. However, I'm tracking all the closed issues in a Project board; despite being closed, they're still on my radar on the board. **All new feature requests *must* go to Discussions. Feature requests opened as issues going forward will be closed.**
