### ISSUE TITLE
See how many bees are in a bee nest/hive in the inventory

### ISSUE THREAD

**Issue by saltyseadoggo** [FalsehoodMC/Fabrication#85]
There are other mods for this, such as Beenfo, but that one in particular adds brand new interfaces that feel completely unnecessary when simply adding a *Bees: 0/1/2/3* lore text line to the bee nest/hive items themselves would make much more sense. This is assuming that adding lore text to the items could be done on the client side only. I would like this feature to work exclusively on the client side so that it may be used on vanilla servers.~

**Comment by exaskye** [comment]
I've received an overwhelming number of feature requests over the week and they are filling up the issue tracker and making it difficult to keep track of what is even going on. I've enabled [Discussions](https://github.com/unascribed/Fabrication/discussions) on the repo as a new location for feature requests. Unfortunately, GitHub has "temporarily" disabled the ability to convert issues to discussions, so I'm closing all feature request issues. However, I'm tracking all the closed issues in a Project board; despite being closed, they're still on my radar on the board. **All new feature requests *must* go to Discussions. Feature requests opened as issues going forward will be closed.**
