### ISSUE TITLE
When full dispenser harvests honey/comb from bee nest/hive, transfer to hopper below nest/hive instead of creating drop

### ISSUE THREAD

**Issue by saltyseadoggo** [FalsehoodMC/Fabrication#86]
Automatic honey bottle/honeycomb gathering machines typically rely on the dispenser that is doing the harvesting being full of bottles/shears, so as to force the honey bottles/honeycombs to drop as item entities inside of the bee nest/hive, where they can ideally be absorbed by a hopper. This *usually* works, but can occasionally lose items, and I would guess also have a performance impact.

I would like to suggest a tweak in which dispensers that harvest honey bottles/honeycombs when full check for a hopper below the bee nest/hive they harvested from, and, if one is found, add the honey bottles/honeycombs to its inventory directly instead of creating item entities. This would function largely the same, but without losses or entity creation.~

**Comment by exaskye** [comment]
I've received an overwhelming number of feature requests over the week and they are filling up the issue tracker and making it difficult to keep track of what is even going on. I've enabled [Discussions](https://github.com/unascribed/Fabrication/discussions) on the repo as a new location for feature requests. Unfortunately, GitHub has "temporarily" disabled the ability to convert issues to discussions, so I'm closing all feature request issues. However, I'm tracking all the closed issues in a Project board; despite being closed, they're still on my radar on the board. **All new feature requests *must* go to Discussions. Feature requests opened as issues going forward will be closed.**
