### ISSUE TITLE
Game Crashes during launch with Mini Tweaks installed

### ISSUE THREAD

**Issue by torzod** [FalsehoodMC/Fabrication#87]
Fabrication seems to be incompatible with https://github.com/manyrandomthings/minitweaks, as it crashes during boot. Crash log is [here](https://gist.github.com/torzod/a5f97f5487a2bdad21c3893109506716#file-crash-log).

**Comment by torzod** [comment]
I should note that this does not happen with any other carpet-extension mods.

**Comment by SFort** [comment]
@unascribed this seems to be fixed in dev version

**Comment by exaskye** [comment]
Yeah, failing redirects no longer cause game crashes.
