### ISSUE TITLE
Wart blocks decay

### ISSUE THREAD

**Issue by saltyseadoggo** [FalsehoodMC/Fabrication#88]
Logging the large crimson and warped fungi is a bit annoying due to the fact that the Nether and warped wart blocks that make up their caps do not decay like leaves do, and so they need to be whacked down with a tool that you don't typically have on you, the hoe, to clear them up. I would like to see a tweak that makes wart blocks decay when they lack support from a stem, unless they are placed by the player, as vanilla leaves do.

**Comment by exaskye** [comment]
I've received an overwhelming number of feature requests over the week and they are filling up the issue tracker and making it difficult to keep track of what is even going on. I've enabled [Discussions](https://github.com/unascribed/Fabrication/discussions) on the repo as a new location for feature requests. Unfortunately, GitHub has "temporarily" disabled the ability to convert issues to discussions, so I'm closing all feature request issues. However, I'm tracking all the closed issues in a Project board; despite being closed, they're still on my radar on the board. **All new feature requests *must* go to Discussions. Feature requests opened as issues going forward will be closed.**
