### ISSUE TITLE
Incompatability with faster-minecarts

### ISSUE THREAD

**Issue by SFort** [FalsehoodMC/Fabrication#89]
When [faster-minecarts](https://github.com/ndrp/faster-minecarts/) is installed and z_combined/furnace_minecart/MixinFurnaceMinecartEntity is eligible
furnace carts tend to bounce between turns
![](https://user-images.githubusercontent.com/1879846/105021580-976f6980-5a40-11eb-84cd-032a01a36cd9.gif)

**Comment by exaskye** [comment]
I'll try and replace some of the Overwrites; did it like that just to make things easier initially and because I figured furnace minecarts were basically forgotten and nobody else was patching them.

The bouncing actually happens sometimes with just Fabrication, too.
