### ISSUE TITLE
Classic block drop textures break with shaders

### ISSUE THREAD

**Issue by egshels** [FalsehoodMC/Fabrication#92]
https://gist.github.com/egshels/495a1d71d9fc59477249634c0a5ccc1c
![image](https://user-images.githubusercontent.com/31183838/105257302-819f9880-5b55-11eb-85e0-6c743f528096.png)
Currently using Complementary shaders, however these break with literally all shaderpacks

**Comment by exaskye** [comment]
Without the ability to look into how OptiFine's shader pipeline works, I can't really figure out what is different let alone why this is broken.
