### ISSUE TITLE
Cure Zombified Piglins

### ISSUE THREAD

**Issue by saltyseadoggo** [FalsehoodMC/Fabrication#93]
A thought I've had before is for Zombified Piglins to be curable using a golden apple and any source of the weakness effect, akin to zombified villagers. Once cured, the resulting Piglin's biology would be affected in such away that it would become immune to further zombification, allowing it to exist in the Overworld or the End.

This would allow for Overworld or End bartering farms, and would also reallow mob zoos/museums to contain all mobs in one dimension, which was possible in the End prior to 20w19a.

It could also affect Zoglins, if you deem so fit, for the latter application. Cured Hoglins that breed may or may not birth non-zombifiable offspring, depending on whether you see it fit to allow or disallow breeding them outside of the Nether.~

**Comment by exaskye** [comment]
I've received an overwhelming number of feature requests over the week and they are filling up the issue tracker and making it difficult to keep track of what is even going on. I've enabled [Discussions](https://github.com/unascribed/Fabrication/discussions) on the repo as a new location for feature requests. Unfortunately, GitHub has "temporarily" disabled the ability to convert issues to discussions, so I'm closing all feature request issues. However, I'm tracking all the closed issues in a Project board; despite being closed, they're still on my radar on the board. **All new feature requests *must* go to Discussions. Feature requests opened as issues going forward will be closed.**
