### ISSUE TITLE
Sneak through Sweet Berry Bushes without taking damage.

### ISSUE THREAD

**Issue by K0-RR** [FalsehoodMC/Fabrication#96]

**Comment by SFort** [comment]
[curseforge](https://www.curseforge.com/minecraft/mc-mods/sneak-through-berries-fabric) / [github](https://github.com/Trikzon/Sneak-Through-Berries)

**Comment by K0-RR** [comment]
Yes, That’s from where my idea comes from. I just don’t like to download whole another mod to have one more feature.

**Comment by SFort** [comment]
~~Seems a bit silly to take the time to submit a issue so that a developer has to take the time to re develop and maintain it just so you can go and enable it in a config, in my opinion~~
Since re-implementing litterally has no benefit in this case
This is just issue spam

**Comment by exaskye** [comment]
I've received an overwhelming number of feature requests over the week and they are filling up the issue tracker and making it difficult to keep track of what is even going on. I've enabled [Discussions](https://github.com/unascribed/Fabrication/discussions) on the repo as a new location for feature requests. Unfortunately, GitHub has "temporarily" disabled the ability to convert issues to discussions, so I'm closing all feature request issues. However, I'm tracking all the closed issues in a Project board; despite being closed, they're still on my radar on the board. **All new feature requests *must* go to Discussions. Feature requests opened as issues going forward will be closed.**
